In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
"""
list_data =[]
list_weeks = ['160102', '160109', '160116','160130','160206','160213',
              '160220','160227','160305','160312','160319','160326','160402']
for u in list_weeks:
    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'
    print(url)
    list_data.append(pd.read_csv(url))

data = pd.concat(list_data)
del list_data"""

"\nlist_data =[]\nlist_weeks = ['160102', '160109', '160116','160130','160206','160213',\n              '160220','160227','160305','160312','160319','160326','160402']\nfor u in list_weeks:\n    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'\n    print(url)\n    list_data.append(pd.read_csv(url))\n\ndata = pd.concat(list_data)\ndel list_data"

In [3]:
data = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_160116.txt")

In [4]:
data.columns = [column.strip() for column in data.columns]
data.columns

Index([u'C/A', u'UNIT', u'SCP', u'STATION', u'LINENAME', u'DIVISION', u'DATE',
       u'TIME', u'DESC', u'ENTRIES', u'EXITS'],
      dtype='object')

In [5]:
data.rename(columns={"EXITS": "EXIT", "ENTRIES": "ENTRY"}, inplace=True)

In [6]:
data['dENTRY'] = 0
data['dEXIT'] = 0

In [7]:
data['dENTRY'] = data.ENTRY.shift(-1) - data.ENTRY
data['dEXIT'] = data.EXIT.shift(-1) - data.EXIT
data['dTOTAL'] = data.dENTRY + data.dEXIT

In [8]:
#diff = data['ENTRY'].iloc[1:].values - data['ENTRY'].iloc[:-1].values
#data['DENTRY'][1:] = diff
#diff = data['EXIT'].iloc[:-1].values - data['EXIT'].iloc[1:].values
#data['DEXIT'][1:] = diff

In [9]:
data['DATETIME'] = pd.to_datetime(data.DATE + data.TIME, format='%m/%d/%Y%H:%M:%S')
data['HOUR'] = data['DATETIME'].apply(lambda x: x.hour)

In [10]:
data['WEEKDAY']=data.DATETIME.apply(lambda x: 'Weekday' if 0<=x.weekday()<5 else 'Weekend')

In [11]:
daysofweek = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

whatdayofweek = lambda x: daysofweek[x.weekday()]


data['DAYOFWEEK'] = data.DATETIME.apply(whatdayofweek)

In [12]:
data_cleaned = data[(data['dENTRY'] >= 0) & (data['dENTRY'] <= 5000) & (data['dEXIT'] >= 0) & (data['dEXIT'] <= 5000)]

In [13]:
data_0to4 = data_cleaned[(data_cleaned.HOUR ==0)|(data_cleaned.HOUR==1)]

In [14]:
data_0to4

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,DATETIME,HOUR,WEEKDAY,DAYOFWEEK
504,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/09/2016,01:00:00,REGULAR,2040807,3599676,19,10,29,2016-01-09 01:00:00,1,Weekend,Saturday
510,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/10/2016,01:00:00,REGULAR,2041839,3601224,20,15,35,2016-01-10 01:00:00,1,Weekend,Sunday
516,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/11/2016,01:00:00,REGULAR,2042576,3602312,11,16,27,2016-01-11 01:00:00,1,Weekday,Monday
522,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/12/2016,01:00:00,REGULAR,2044373,3605334,17,10,27,2016-01-12 01:00:00,1,Weekday,Tuesday
528,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/13/2016,01:00:00,REGULAR,2046161,3608424,0,1,1,2016-01-13 01:00:00,1,Weekday,Wednesday
534,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/14/2016,01:00:00,REGULAR,2047916,3611398,0,2,2,2016-01-14 01:00:00,1,Weekday,Thursday
540,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/15/2016,01:00:00,REGULAR,2049639,3614351,0,2,2,2016-01-15 01:00:00,1,Weekday,Friday
546,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/09/2016,01:00:00,REGULAR,3309511,2164953,11,1,12,2016-01-09 01:00:00,1,Weekend,Saturday
552,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/10/2016,01:00:00,REGULAR,3310418,2165464,17,2,19,2016-01-10 01:00:00,1,Weekend,Sunday
558,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/11/2016,01:00:00,REGULAR,3311063,2165773,4,4,8,2016-01-11 01:00:00,1,Weekday,Monday
564,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/12/2016,01:00:00,REGULAR,3312806,2166602,12,3,15,2016-01-12 01:00:00,1,Weekday,Tuesday
570,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/13/2016,01:00:00,REGULAR,3314620,2167467,0,0,0,2016-01-13 01:00:00,1,Weekday,Wednesday
576,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/14/2016,01:00:00,REGULAR,3316339,2168342,0,0,0,2016-01-14 01:00:00,1,Weekday,Thursday
582,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/15/2016,01:00:00,REGULAR,3318004,2169209,0,0,0,2016-01-15 01:00:00,1,Weekday,Friday
588,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/09/2016,01:00:00,REGULAR,7204633,3200227,9,1,10,2016-01-09 01:00:00,1,Weekend,Saturday
594,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/10/2016,01:00:00,REGULAR,7205275,3200466,12,4,16,2016-01-10 01:00:00,1,Weekend,Sunday
600,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/11/2016,01:00:00,REGULAR,7205689,3200632,7,1,8,2016-01-11 01:00:00,1,Weekday,Monday
606,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/12/2016,01:00:00,REGULAR,7206974,3201138,3,3,6,2016-01-12 01:00:00,1,Weekday,Tuesday
612,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/13/2016,01:00:00,REGULAR,7208256,3201635,0,0,0,2016-01-13 01:00:00,1,Weekday,Wednesday
618,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/14/2016,01:00:00,REGULAR,7209536,3202123,0,0,0,2016-01-14 01:00:00,1,Weekday,Thursday
624,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/15/2016,01:00:00,REGULAR,7210825,3202677,0,0,0,2016-01-15 01:00:00,1,Weekday,Friday
630,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/09/2016,01:00:00,REGULAR,1890585,710424,6,3,9,2016-01-09 01:00:00,1,Weekend,Saturday
636,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/10/2016,01:00:00,REGULAR,1891092,710602,10,0,10,2016-01-10 01:00:00,1,Weekend,Sunday
642,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/11/2016,01:00:00,REGULAR,1891397,710702,12,0,12,2016-01-11 01:00:00,1,Weekday,Monday
648,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/12/2016,01:00:00,REGULAR,1892487,711091,3,1,4,2016-01-12 01:00:00,1,Weekday,Tuesday
654,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/13/2016,01:00:00,REGULAR,1893533,711492,0,0,0,2016-01-13 01:00:00,1,Weekday,Wednesday
660,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/14/2016,01:00:00,REGULAR,1894558,711890,0,0,0,2016-01-14 01:00:00,1,Weekday,Thursday
666,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/15/2016,01:00:00,REGULAR,1895640,712311,0,0,0,2016-01-15 01:00:00,1,Weekday,Friday
672,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,01/09/2016,01:00:00,REGULAR,6614986,2934031,4,2,6,2016-01-09 01:00:00,1,Weekend,Saturday
678,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,01/10/2016,01:00:00,REGULAR,6615420,2934221,12,2,14,2016-01-10 01:00:00,1,Weekend,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192984,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,01/14/2016,00:00:00,REGULAR,1436231,14820,3,1,4,2016-01-14 00:00:00,0,Weekday,Thursday
192990,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,01/15/2016,00:00:00,REGULAR,1437597,14832,4,4,8,2016-01-15 00:00:00,0,Weekday,Friday
192996,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/09/2016,00:00:00,REGULAR,275969,11262,0,1,1,2016-01-09 00:00:00,0,Weekend,Saturday
193002,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/10/2016,00:00:00,REGULAR,276181,11266,2,1,3,2016-01-10 00:00:00,0,Weekend,Sunday
193008,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/11/2016,00:00:00,REGULAR,276323,11271,2,2,4,2016-01-11 00:00:00,0,Weekday,Monday
193014,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/12/2016,00:00:00,REGULAR,276479,11278,1,0,1,2016-01-12 00:00:00,0,Weekday,Tuesday
193020,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/13/2016,00:00:00,REGULAR,276635,11281,0,0,0,2016-01-13 00:00:00,0,Weekday,Wednesday
193026,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/14/2016,00:00:00,REGULAR,276798,11284,0,0,0,2016-01-14 00:00:00,0,Weekday,Thursday
193032,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/15/2016,00:00:00,REGULAR,276965,11288,0,1,1,2016-01-15 00:00:00,0,Weekday,Friday
193038,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/09/2016,00:00:00,REGULAR,2587312,375884,0,0,0,2016-01-09 00:00:00,0,Weekend,Saturday
193044,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/10/2016,00:00:00,REGULAR,2587560,375895,1,0,1,2016-01-10 00:00:00,0,Weekend,Sunday
193050,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/11/2016,00:00:00,REGULAR,2587723,375902,2,0,2,2016-01-11 00:00:00,0,Weekday,Monday
193056,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/12/2016,00:00:00,REGULAR,2587915,375910,1,2,3,2016-01-12 00:00:00,0,Weekday,Tuesday
193062,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/13/2016,00:00:00,REGULAR,2588071,375920,2,1,3,2016-01-13 00:00:00,0,Weekday,Wednesday
193068,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/14/2016,00:00:00,REGULAR,2588274,375929,0,0,0,2016-01-14 00:00:00,0,Weekday,Thursday
193074,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/15/2016,00:00:00,REGULAR,2588486,375940,0,0,0,2016-01-15 00:00:00,0,Weekday,Friday
193080,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/09/2016,00:00:00,REGULAR,2056,62,0,0,0,2016-01-09 00:00:00,0,Weekend,Saturday
193086,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/10/2016,00:00:00,REGULAR,2056,62,0,0,0,2016-01-10 00:00:00,0,Weekend,Sunday
193092,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/11/2016,00:00:00,REGULAR,2056,62,0,0,0,2016-01-11 00:00:00,0,Weekday,Monday
193098,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/12/2016,00:00:00,REGULAR,2057,62,0,0,0,2016-01-12 00:00:00,0,Weekday,Tuesday
193104,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/13/2016,00:00:00,REGULAR,2058,62,0,0,0,2016-01-13 00:00:00,0,Weekday,Wednesday
193110,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/14/2016,00:00:00,REGULAR,2059,62,0,0,0,2016-01-14 00:00:00,0,Weekday,Thursday
193116,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/15/2016,00:00:00,REGULAR,2059,62,0,0,0,2016-01-15 00:00:00,0,Weekday,Friday
193122,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/09/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-09 00:00:00,0,Weekend,Saturday
193128,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/10/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-10 00:00:00,0,Weekend,Sunday
193134,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/11/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-11 00:00:00,0,Weekday,Monday
193140,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/12/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-12 00:00:00,0,Weekday,Tuesday
193146,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/13/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-13 00:00:00,0,Weekday,Wednesday
193152,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/14/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-14 00:00:00,0,Weekday,Thursday
193158,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/15/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-15 00:00:00,0,Weekday,Friday

In [15]:
data_grouped = data_0to4.groupby(['DATE','STATION']).sum()

In [16]:
data_grouped

                                 ENTRY        EXIT  dENTRY  dEXIT  dTOTAL  \
DATE       STATION
01/09/2016 103 ST            124492575    97229577     534   1009    1543
           111 ST             56029870    20705345       9     10      19
           116 ST            434275136   443385359     748    802    1550
           116 ST-COLUMBIA  1209370889   255792814     132    106     238
           125 ST            149534851   109000811    1024   1034    2058
           135 ST            202862426    30332331      58    136     194
           137 ST CITY COL    51679522    40934940     180    685     865
           14 ST             263859017    52719411     903    348    1251
           14 ST-UNION SQ   1296505129   499311855    5444   1366    6810
           14TH STREET         1981999     3478288      36     57      93
           155 ST             30777617    23534810     109    364     473
           157 ST             31553409    21181762     184    679     863
           163 ST-AMSTERDM  1969187876   675554453      48    143     191
           170 ST           1284591469  2348573377     114    175     289
           174 ST             21613469    14439064     123    337     460
           18 AV              20577667    21111666      30    174     204
           181 ST             51447596    42788092      94    571     665
           21 ST               5592622     6329171     119     90     209
           219 ST              9593784     5896405      73     87     160
           225 ST             14095329     7777944      73    110     183
           23 ST            2188509531  1831244287    1054    455    1509
           233 ST             95249787     4519905      69     82     151
           238 ST             18978570      874353      66      4      70
           25 AV               3675994     1241502      67     78     145
           28 ST            1511820984  2081942930    1151    506    1657
           3 AV 138 ST        17515164    14954734     188    455     643
           33 ST             345268026   136365992     917    383    1300
           34 ST-PENN STA   1882620543  1220079918     645    534    1179
           36 ST              58651430   159537297     330    626     956
           42 ST-PORT AUTH   322731499   102210135    2330    815    3145
...                                ...         ...     ...    ...     ...
01/15/2016 RALPH AV           20998947    16703657      95    186     281
           RIT-MANHATTAN       4296430       69579      51      3      54
           RIT-ROOSEVELT       7231490      443801      17      5      22
           ROCKAWAY AV       716621750    42302163      74    208     282
           ROCKAWAY BLVD     271337923    12948795      87     87     174
           ROCKAWAY PARK B   105083402    10833968      11     38      49
           SENECA AVE          5098068     5692456      16    103     119
           SHEEPSHEAD BAY     39672120    35839664     126    312     438
           SHEPHERD AV        16728432    14353539      46    126     172
           SIMPSON ST         37118823    10262488     127     38     165
           SOUTH FERRY        35080646    30771341     139    383     522
           SUTPHIN BLVD       17920686     9645249      41    119     160
           SUTPHIN-ARCHER       475823      460016     183    349     532
           SUTTER AV          11167420    14962596      84    217     301
           THIRTY ST           2444553     2915353      89    107     196
           THIRTY THIRD ST     4006799     3153997      67      3      70
           TREMONT AV        128941346    10729741     133    425     558
           TWENTY THIRD ST     2433467     1248981      24     56      80
           UTICA AV          102583480    49880424     231    586     817
           VAN SICLEN AV      12196940    11952821      52    115     167
           VAN SICLEN AVE     13222013    13728517      56    165     221
           W 4 ST-WASH SQ    802837320   895474237    1773    560    2333
           WAKEFIELD/241      16068022    16623214     107    283     390
           WALL ST           533109588   277824574       0      9       9
           WEST FARMS SQ     438108391    72839616     156    223     379
           WHITEHALL S-FRY   131714227    12029589     284    266     550
           WINTHROP ST        31408996     5551196      55     39      94
           WOODHAVEN BLVD     54958437    36385037     136    341     477
           YORK ST            31357951    28758557     112    101     213
           ZEREGA AV          53499670      489835      20     77      97

                            HOUR
DATE       STATION
01/09/2016 103 ST              0
           111 ST              0
           116 ST              0
           116 ST-COLUMBIA     0
           125 ST              0
           135 ST              0
           137 ST CITY COL     0
           14 ST               0
           14 ST-UNION SQ      0
           14TH STREET         3
           155 ST              0
           157 ST              0
           163 ST-AMSTERDM     0
           170 ST              0
           174 ST              0
           18 AV               0
           181 ST              0
           21 ST               0
           219 ST              0
           225 ST              0
           23 ST               0
           233 ST              0
           238 ST              0
           25 AV               0
           28 ST               0
           3 AV 138 ST         0
           33 ST               0
           34 ST-PENN STA     21
           36 ST               0
           42 ST-PORT AUTH    19
...                          ...
01/15/2016 RALPH AV            0
           RIT-MANHATTAN       0
           RIT-ROOSEVELT       0
           ROCKAWAY AV         0
           ROCKAWAY BLVD       0
           ROCKAWAY PARK B     0
           SENECA AVE          0
           SHEEPSHEAD BAY      0
           SHEPHERD AV         0
           SIMPSON ST          0
           SOUTH FERRY         0
           SUTPHIN BLVD        0
           SUTPHIN-ARCHER      0
           SUTTER AV           0
           THIRTY ST           5
           THIRTY THIRD ST     2
           TREMONT AV          0
           TWENTY THIRD ST     5
           UTICA AV            0
           VAN SICLEN AV       0
           VAN SICLEN AVE      0
           W 4 ST-WASH SQ      0
           WAKEFIELD/241       0
           WALL ST            28
           WEST FARMS SQ       0
           WHITEHALL S-FRY     0
           WINTHROP ST         0
           WOODHAVEN BLVD      0
           YORK ST             0
           ZEREGA AV           0

[1376 rows x 6 columns]

In [19]:
data_reset = (data_grouped
    .reset_index()
    .sort_values(['dTOTAL'], ascending=(False))
)
data_reset

,DATE,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR
205,01/10/2016,14 ST-UNION SQ,1296576062,499378628,5411,1657,7068,0
8,01/09/2016,14 ST-UNION SQ,1296505129,499311855,5444,1366,6810,0
385,01/10/2016,W 4 ST-WASH SQ,802660314,895309093,3890,1235,5125,0
188,01/09/2016,W 4 ST-WASH SQ,802630694,895276998,3878,1147,5025,0
1186,01/15/2016,14 ST-UNION SQ,1297039905,499781940,3034,1817,4851,0
287,01/10/2016,DELANCEY/ESSEX,1710962474,1111138713,2657,1111,3768,0
242,01/10/2016,8 AV,197408492,90974225,2552,923,3475,0
89,01/09/2016,DELANCEY/ESSEX,1710942406,1111120360,2437,925,3362,0
227,01/10/2016,42 ST-PORT AUTH,322759837,102230209,2491,729,3220,19
248,01/10/2016,96 ST,770267952,1416186276,1235,1948,3183,0
29,01/09/2016,42 ST-PORT AUTH,322731499,102210135,2330,815,3145,19
44,01/09/2016,8 AV,197379936,90951309,2216,856,3072,0
50,01/09/2016,96 ST,770228172,1416157151,1158,1641,2799,0
796,01/13/2016,14 ST-UNION SQ,1296833061,499603344,2165,617,2782,0
600,01/12/2016,14 ST-UNION SQ,1296730850,499514712,2019,573,2592,0
990,01/14/2016,14 ST-UNION SQ,1296936903,499692350,2012,579,2591,0
1367,01/15/2016,W 4 ST-WASH SQ,802837320,895474237,1773,560,2333,0
1307,01/15/2016,KINGSBRIDGE RD,54029849,38247298,1548,781,2329,0
1269,01/15/2016,DELANCEY/ESSEX,1711078643,1111232538,954,1333,2287,0
201,01/10/2016,125 ST,149557951,109019317,1043,1092,2135,0
1170,01/14/2016,W 4 ST-WASH SQ,802797449,895436852,1603,493,2096,0
683,01/12/2016,DELANCEY/ESSEX,1711002228,1111168414,759,1328,2087,0
402,01/11/2016,14 ST-UNION SQ,1296631655,499428346,1544,535,2079,0
4,01/09/2016,125 ST,149534851,109000811,1024,1034,2058,0
1208,01/15/2016,42 ST-PORT AUTH,322906397,102346996,1364,604,1968,19
110,01/09/2016,GRD CNTRL-42 ST,2645616542,624878722,1391,547,1938,0
239,01/10/2016,72 ST,1607868735,983264717,1153,739,1892,0
780,01/12/2016,W 4 ST-WASH SQ,802719447,895364349,1420,468,1888,0
974,01/13/2016,W 4 ST-WASH SQ,802758100,895400287,1402,479,1881,0
335,01/10/2016,METROPOLITAN AV,29364390,21828099,1296,565,1861,0
...,...,...,...,...,...,...,...,...
976,01/13/2016,WALL ST,533063052,277787108,1,10,11,28
1046,01/14/2016,BEACH 105 ST,118566212,1587224,2,9,11,0
464,01/11/2016,BROAD CHANNEL,1758255,604566,5,6,11,0
1172,01/14/2016,WALL ST,533086382,277805670,0,10,10,28
395,01/11/2016,111 ST,2107292,2290163,4,6,10,0
712,01/12/2016,HUNTERS PT AV,2101424394,858729273,0,10,10,0
656,01/12/2016,BEACH 105 ST,118565655,1586553,2,7,9,0
1249,01/15/2016,BROAD ST,21652837,12897399,3,6,9,0
1248,01/15/2016,BROAD CHANNEL,1759623,604919,6,3,9,0
1369,01/15/2016,WALL ST,533109588,277824574,0,9,9,28
69,01/09/2016,BROAD CHANNEL,1758045,604425,6,3,9,0
799,01/13/2016,157 ST,31590024,21206934,3,6,9,0
1151,01/14/2016,RIT-ROOSEVELT,7228321,443767,7,1,8,0
782,01/12/2016,WALL ST,533039894,277769106,3,5,8,28
1133,01/14/2016,NEWARK C,2187916,272634,4,3,7,9
198,01/10/2016,111 ST,2107207,2290110,0,7,7,0
267,01/10/2016,BROAD CHANNEL,1758161,604510,6,1,7,0
603,01/12/2016,157 ST,31579273,21199886,3,3,6,0
1053,01/14/2016,BROAD ST,21645250,12894870,4,2,6,0
1015,01/14/2016,5 AV/59 ST,173209564,41371787,1,5,6,14
1211,01/15/2016,5 AV/59 ST,173226269,41383406,1,4,5,14
821,01/13/2016,5 AV/59 ST,173193045,41360005,2,2,4,14
578,01/11/2016,TOMPKINSVILLE,8618418,2414988,4,0,4,7
426,01/11/2016,5 AV/53 ST,83460043,89841442,0,2,2,21
811,01/13/2016,238 ST,18991268,874687,0,2,2,0
149,01/09/2016,NEWARK C,509472,32809,0,0,0,0
615,01/12/2016,238 ST,18987059,874599,0,0,0,0
938,01/13/2016,NEWARK C,1223937,79149,0,0,0,0
184,01/09/2016,TWENTY THIRD ST,4384,143422,0,0,0,0
347,01/10/2016,NEWARK C,2347131,155766,0,0,0,2

In [18]:
for r in range(data_reset.shape[0]):
    if data_reset.ix[r,'WEEKDAY'] =='Weekday':
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(5)
    else:
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(2)

KeyError: 'WEEKDAY'

In [ ]:
data_reset

In [ ]:
testweekend = data_reset[(data_reset.WEEKDAY == 'Weekday')]

In [ ]:
testweekend

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#data_reset[data_reset.STATION=='WORLD TRADE CTR'].dTOTAL.plot(kind='bar');
data_reset[data_reset.STATION=='WORLD TRADE CTR'].hist(by = data_reset.DATE, bins = 25, figsize = (100,50));