In [4]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
"""
list_data =[]
list_weeks = ['160102', '160109', '160116','160130','160206','160213',
              '160220','160227','160305','160312','160319','160326','160402']
for u in list_weeks:
    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'
    print(url)
    list_data.append(pd.read_csv(url))

data = pd.concat(list_data)
del list_data"""

"\nlist_data =[]\nlist_weeks = ['160102', '160109', '160116','160130','160206','160213',\n              '160220','160227','160305','160312','160319','160326','160402']\nfor u in list_weeks:\n    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'\n    print(url)\n    list_data.append(pd.read_csv(url))\n\ndata = pd.concat(list_data)\ndel list_data"

In [6]:
data = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_160102.txt")

In [7]:
data.columns = [column.strip() for column in data.columns]
data.columns

Index([u'C/A', u'UNIT', u'SCP', u'STATION', u'LINENAME', u'DIVISION', u'DATE',
       u'TIME', u'DESC', u'ENTRIES', u'EXITS'],
      dtype='object')

In [8]:
data.rename(columns={"EXITS": "EXIT", "ENTRIES": "ENTRY"}, inplace=True)

In [9]:
data['dENTRY'] = 0
data['dEXIT'] = 0

In [10]:
data['dENTRY'] = data.ENTRY.shift(-1) - data.ENTRY
data['dEXIT'] = data.EXIT.shift(-1) - data.EXIT
data['dTOTAL'] = data.dENTRY + data.dEXIT

In [11]:
#diff = data['ENTRY'].iloc[1:].values - data['ENTRY'].iloc[:-1].values
#data['DENTRY'][1:] = diff
#diff = data['EXIT'].iloc[:-1].values - data['EXIT'].iloc[1:].values
#data['DEXIT'][1:] = diff

In [12]:
data['DATETIME'] = pd.to_datetime(data.DATE + data.TIME, format='%m/%d/%Y%H:%M:%S')
data['HOUR'] = data['DATETIME'].apply(lambda x: x.hour)

In [13]:
data['WEEKDAY']=data.DATETIME.apply(lambda x: 'Weekday' if 0<=x.weekday()<5 else 'Weekend')

In [14]:
daysofweek = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

whatdayofweek = lambda x: daysofweek[x.weekday()]


data['DAYOFWEEK'] = data.DATETIME.apply(whatdayofweek)

In [15]:
data_cleaned = data[(data['dENTRY'] >= 0) & (data['dENTRY'] <= 5000) & (data['dEXIT'] >= 0) & (data['dEXIT'] <= 5000)]

In [16]:
data_0to4 = data_cleaned[(data_cleaned.HOUR ==0)|(data_cleaned.HOUR==1)]

In [17]:
data_0to4

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,DATETIME,HOUR,WEEKDAY,DAYOFWEEK
504,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/26/2015,01:00:00,REGULAR,2019275,3566726,12,6,18,2015-12-26 01:00:00,1,Weekend,Saturday
510,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/27/2015,01:00:00,REGULAR,2020556,3568504,14,8,22,2015-12-27 01:00:00,1,Weekend,Sunday
516,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/28/2015,01:00:00,REGULAR,2021633,3569933,7,12,19,2015-12-28 01:00:00,1,Weekday,Monday
522,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/29/2015,01:00:00,REGULAR,2023488,3572923,24,19,43,2015-12-29 01:00:00,1,Weekday,Tuesday
528,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/30/2015,01:00:00,REGULAR,2025243,3575846,28,20,48,2015-12-30 01:00:00,1,Weekday,Wednesday
534,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/31/2015,01:00:00,REGULAR,2027163,3578910,21,69,90,2015-12-31 01:00:00,1,Weekday,Thursday
540,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/01/2016,01:00:00,REGULAR,2028761,3581396,2,7,9,2016-01-01 01:00:00,1,Weekday,Friday
546,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/26/2015,01:00:00,REGULAR,3289224,2153861,18,5,23,2015-12-26 01:00:00,1,Weekend,Saturday
552,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/27/2015,01:00:00,REGULAR,3290371,2154540,16,1,17,2015-12-27 01:00:00,1,Weekend,Sunday
558,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/28/2015,01:00:00,REGULAR,3291290,2155137,14,1,15,2015-12-28 01:00:00,1,Weekday,Monday
564,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/29/2015,01:00:00,REGULAR,3293056,2156199,5,2,7,2015-12-29 01:00:00,1,Weekday,Tuesday
570,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/30/2015,01:00:00,REGULAR,3294733,2157123,7,3,10,2015-12-30 01:00:00,1,Weekday,Wednesday
576,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/31/2015,01:00:00,REGULAR,3296603,2158199,14,23,37,2015-12-31 01:00:00,1,Weekday,Thursday
582,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/01/2016,01:00:00,REGULAR,3298052,2159019,1,1,2,2016-01-01 01:00:00,1,Weekday,Friday
588,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/26/2015,01:00:00,REGULAR,7188753,3193911,3,0,3,2015-12-26 01:00:00,1,Weekend,Saturday
594,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/27/2015,01:00:00,REGULAR,7189628,3194268,4,1,5,2015-12-27 01:00:00,1,Weekend,Sunday
600,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/28/2015,01:00:00,REGULAR,7190339,3194573,6,1,7,2015-12-28 01:00:00,1,Weekday,Monday
606,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/29/2015,01:00:00,REGULAR,7191768,3195153,4,3,7,2015-12-29 01:00:00,1,Weekday,Tuesday
612,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/30/2015,01:00:00,REGULAR,7193140,3195697,6,0,6,2015-12-30 01:00:00,1,Weekday,Wednesday
618,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/31/2015,01:00:00,REGULAR,7194664,3196291,5,7,12,2015-12-31 01:00:00,1,Weekday,Thursday
624,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/01/2016,01:00:00,REGULAR,7195724,3196804,3,1,4,2016-01-01 01:00:00,1,Weekday,Friday
630,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/26/2015,01:00:00,REGULAR,1876958,705919,2,3,5,2015-12-26 01:00:00,1,Weekend,Saturday
636,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/27/2015,01:00:00,REGULAR,1877702,706131,9,2,11,2015-12-27 01:00:00,1,Weekend,Sunday
642,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/28/2015,01:00:00,REGULAR,1878342,706347,4,1,5,2015-12-28 01:00:00,1,Weekday,Monday
648,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/29/2015,01:00:00,REGULAR,1879440,706751,5,0,5,2015-12-29 01:00:00,1,Weekday,Tuesday
654,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/30/2015,01:00:00,REGULAR,1880575,707138,1,1,2,2015-12-30 01:00:00,1,Weekday,Wednesday
660,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/31/2015,01:00:00,REGULAR,1881910,707554,10,4,14,2015-12-31 01:00:00,1,Weekday,Thursday
666,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/01/2016,01:00:00,REGULAR,1882776,707945,0,0,0,2016-01-01 01:00:00,1,Weekday,Friday
672,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,12/26/2015,01:00:00,REGULAR,6602408,2929275,4,3,7,2015-12-26 01:00:00,1,Weekend,Saturday
678,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,12/27/2015,01:00:00,REGULAR,6603216,2929498,8,3,11,2015-12-27 01:00:00,1,Weekend,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191607,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,12/31/2015,00:00:00,REGULAR,1416116,14567,9,2,11,2015-12-31 00:00:00,0,Weekday,Thursday
191613,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,01/01/2016,00:00:00,REGULAR,1417901,14583,54,2,56,2016-01-01 00:00:00,0,Weekday,Friday
191619,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,12/26/2015,00:00:00,REGULAR,272317,11129,0,2,2,2015-12-26 00:00:00,0,Weekend,Saturday
191625,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,12/27/2015,00:00:00,REGULAR,272576,11137,0,0,0,2015-12-27 00:00:00,0,Weekend,Sunday
191631,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,12/28/2015,00:00:00,REGULAR,272793,11149,0,1,1,2015-12-28 00:00:00,0,Weekday,Monday
191637,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,12/29/2015,00:00:00,REGULAR,273141,11161,1,0,1,2015-12-29 00:00:00,0,Weekday,Tuesday
191643,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,12/30/2015,00:00:00,REGULAR,273357,11165,0,0,0,2015-12-30 00:00:00,0,Weekday,Wednesday
191649,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,12/31/2015,00:00:00,REGULAR,273836,11176,1,1,2,2015-12-31 00:00:00,0,Weekday,Thursday
191655,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/01/2016,00:00:00,REGULAR,274068,11185,3,4,7,2016-01-01 00:00:00,0,Weekday,Friday
191661,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,12/26/2015,00:00:00,REGULAR,2583057,375729,0,0,0,2015-12-26 00:00:00,0,Weekend,Saturday
191667,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,12/27/2015,00:00:00,REGULAR,2583323,375738,0,0,0,2015-12-27 00:00:00,0,Weekend,Sunday
191673,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,12/28/2015,00:00:00,REGULAR,2583590,375758,0,0,0,2015-12-28 00:00:00,0,Weekday,Monday
191679,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,12/29/2015,00:00:00,REGULAR,2583934,375765,1,3,4,2015-12-29 00:00:00,0,Weekday,Tuesday
191685,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,12/30/2015,00:00:00,REGULAR,2584197,375780,0,2,2,2015-12-30 00:00:00,0,Weekday,Wednesday
191691,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,12/31/2015,00:00:00,REGULAR,2584758,375801,1,0,1,2015-12-31 00:00:00,0,Weekday,Thursday
191697,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2016,00:00:00,REGULAR,2585053,375810,4,0,4,2016-01-01 00:00:00,0,Weekday,Friday
191703,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,12/26/2015,00:00:00,REGULAR,2049,62,0,0,0,2015-12-26 00:00:00,0,Weekend,Saturday
191709,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,12/27/2015,00:00:00,REGULAR,2049,62,0,0,0,2015-12-27 00:00:00,0,Weekend,Sunday
191715,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,12/28/2015,00:00:00,REGULAR,2050,62,0,0,0,2015-12-28 00:00:00,0,Weekday,Monday
191721,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,12/29/2015,00:00:00,REGULAR,2050,62,0,0,0,2015-12-29 00:00:00,0,Weekday,Tuesday
191727,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,12/30/2015,00:00:00,REGULAR,2050,62,0,0,0,2015-12-30 00:00:00,0,Weekday,Wednesday
191733,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,12/31/2015,00:00:00,REGULAR,2051,62,0,0,0,2015-12-31 00:00:00,0,Weekday,Thursday
191739,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/01/2016,00:00:00,REGULAR,2051,62,0,0,0,2016-01-01 00:00:00,0,Weekday,Friday
191745,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,12/26/2015,00:00:00,REGULAR,5554,230,0,0,0,2015-12-26 00:00:00,0,Weekend,Saturday
191751,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,12/27/2015,00:00:00,REGULAR,5554,230,0,0,0,2015-12-27 00:00:00,0,Weekend,Sunday
191757,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,12/28/2015,00:00:00,REGULAR,5554,230,0,0,0,2015-12-28 00:00:00,0,Weekday,Monday
191763,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,12/29/2015,00:00:00,REGULAR,5554,230,0,0,0,2015-12-29 00:00:00,0,Weekday,Tuesday
191769,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,12/30/2015,00:00:00,REGULAR,5554,230,0,0,0,2015-12-30 00:00:00,0,Weekday,Wednesday
191775,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,12/31/2015,00:00:00,REGULAR,5554,230,0,0,0,2015-12-31 00:00:00,0,Weekday,Thursday
191781,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/01/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-01 00:00:00,0,Weekday,Friday

In [18]:
data_grouped = data_0to4.groupby(['DATE','STATION']).sum()

In [19]:
data_grouped

                                 ENTRY        EXIT  dENTRY  dEXIT  dTOTAL  \
DATE       STATION
01/01/2016 103 ST            124275451    97068537    1382   2627    4009
           111 ST             56026967    20703956       7      7      14
           116 ST            434045322   443270013    2226   1544    3770
           116 ST-COLUMBIA  1209304180   255757907     427    397     824
           125 ST            149283761   108805385    2122   1930    4052
           135 ST            202828327    30307064     238    347     585
           137 ST CITY COL    51595602    40876251     574    970    1544
           14 ST             263727289    52602844    2026   1126    3152
           14 ST-UNION SQ   1295825246   498726380    8723   4876   13599
           14TH STREET         5328286     1390620    1587    197    1784
           155 ST             30732079    23505411     347    659    1006
           157 ST             31479360    21130033     598    886    1484
           163 ST-AMSTERDM    16699135    11278577     143    289     432
           170 ST           1284544003  2348550148     222    242     464
           174 ST             21571530    14401105     288    429     717
           18 AV              20547147    21078948      79    327     406
           181 ST             51373405    42726742     325   1043    1368
           20 AV              14549689    12590139      27    181     208
           21 ST               5581354     6316633     165    191     356
           219 ST              9570512     5885820     135    104     239
           225 ST             14065377     7765433     154    135     289
           23 ST            2188269767  1831047870    2541   2026    4567
           233 ST             95213634     4508303     150     88     238
           238 ST             18951764      873664     210     10     220
           25 AV               3647116     1233446      82    122     204
           28 ST            1511587521  2315673565    2605   1746    4351
           3 AV 138 ST        17463359    14917640     271    457     728
           33 ST             227628017   136211144    1830   1380    3210
           34 ST-PENN STA   1882266234  1219826448    3421   2279    5700
           36 ST             863856666  1233230333     475   1153    1628
...                                ...         ...     ...    ...     ...
12/31/2015 RIT-MANHATTAN       4246923       68972      63      1      64
           RIT-ROOSEVELT       7181901      443024      25      3      28
           ROCKAWAY AV       716550294    42260220     102    183     285
           ROCKAWAY BLVD     271252502    12923252     110    100     210
           ROCKAWAY PARK B   105075618    10824168      14     49      63
           SENECA AVE          5064757     5660500      31    134     165
           SHEEPSHEAD BAY     39503737    35687499     131    356     487
           SHEPHERD AV        16685992    14330380      52     88     140
           SIMPSON ST         36994903    10242128     125     45     170
           SOUTH FERRY        34934820    30590148     181    556     737
           SUTPHIN BLVD       17864532     9611088      32    127     159
           SUTPHIN-ARCHER       390518      370327     267    441     708
           SUTTER AV          11107537    14919689      76    247     323
           THIRTY ST            788721     3428432      66      9      75
           THIRTY THIRD ST     5012759     3532470     193    174     367
           TOMPKINSVILLE       8612291     2414987      10      0      10
           TREMONT AV        128816996    10654451     153    401     554
           TWENTY THIRD ST      566901     1196172      34     16      50
           UTICA AV          102383089    49731798     276    653     929
           VAN SICLEN AV      12159407    11914781      63    188     251
           VAN SICLEN AVE     13181214    13691285      50    160     210
           W 4 ST-WASH SQ    802331670   894987502    2703    812    3515
           WAKEFIELD/241      16001928    16554856     133    318     451
           WALL ST           532858827   277634205      77     80     157
           WEST FARMS SQ     438009515    72769492     165    305     470
           WHITEHALL S-FRY   131534549    11861096     133    243     376
           WINTHROP ST        31323378     5530444      77     49     126
           WOODHAVEN BLVD     54675899    36218673     205    419     624
           YORK ST            31243732    28674361      89    104     193
           ZEREGA AV          53468921      461325      27     97     124

                            HOUR
DATE       STATION
01/01/2016 103 ST              0
           111 ST              0
           116 ST              0
           116 ST-COLUMBIA     0
           125 ST              0
           135 ST              0
           137 ST CITY COL     0
           14 ST               0
           14 ST-UNION SQ      0
           14TH STREET         3
           155 ST              0
           157 ST              0
           163 ST-AMSTERDM     0
           170 ST              0
           174 ST              0
           18 AV               0
           181 ST              0
           20 AV               0
           21 ST               0
           219 ST              0
           225 ST              0
           23 ST               0
           233 ST              0
           238 ST              0
           25 AV               0
           28 ST               0
           3 AV 138 ST         0
           33 ST               0
           34 ST-PENN STA     21
           36 ST               0
...                          ...
12/31/2015 RIT-MANHATTAN       0
           RIT-ROOSEVELT       0
           ROCKAWAY AV         0
           ROCKAWAY BLVD       0
           ROCKAWAY PARK B     0
           SENECA AVE          0
           SHEEPSHEAD BAY      0
           SHEPHERD AV         0
           SIMPSON ST          0
           SOUTH FERRY         0
           SUTPHIN BLVD        0
           SUTPHIN-ARCHER      0
           SUTTER AV           0
           THIRTY ST           7
           THIRTY THIRD ST     5
           TOMPKINSVILLE       7
           TREMONT AV          0
           TWENTY THIRD ST     0
           UTICA AV            0
           VAN SICLEN AV       0
           VAN SICLEN AVE      0
           W 4 ST-WASH SQ      0
           WAKEFIELD/241       0
           WALL ST            28
           WEST FARMS SQ       0
           WHITEHALL S-FRY     0
           WINTHROP ST         0
           WOODHAVEN BLVD      0
           YORK ST             0
           ZEREGA AV           0

[1390 rows x 6 columns]

In [22]:
data_reset = (data_grouped
    .reset_index()
    .sort_values(['dTOTAL'], ascending=(False))
)
data_reset

,DATE,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR
8,01/01/2016,14 ST-UNION SQ,1295825246,498726380,8723,4876,13599,0
30,01/01/2016,42 ST-PORT AUTH,323071716,86045730,8131,2395,10526,19
190,01/01/2016,W 4 ST-WASH SQ,802362012,895020261,6303,3384,9687,0
51,01/01/2016,96 ST,769817980,1415871614,2627,4528,7155,0
45,01/01/2016,8 AV,197136435,90764301,4927,2061,6988,0
91,01/01/2016,DELANCEY/ESSEX,1710769774,1110982848,4302,2299,6601,0
41,01/01/2016,7 AV,1907910719,838925819,4771,1808,6579,0
42,01/01/2016,72 ST,1607584159,983008486,4535,1967,6502,0
28,01/01/2016,34 ST-PENN STA,1882266234,1219826448,3421,2279,5700,21
406,12/27/2015,14 ST-UNION SQ,1298639282,502382002,3837,1139,4976,0
1200,12/31/2015,14 ST-UNION SQ,1295748794,498653448,3634,1149,4783,0
21,01/01/2016,23 ST,2188269767,1831047870,2541,2026,4567,0
77,01/01/2016,CANAL ST,2982847741,1621189329,2592,1861,4453,0
112,01/01/2016,GRD CNTRL-42 ST,2645123108,624410165,1369,3070,4439,0
25,01/01/2016,28 ST,1511587521,2315673565,2605,1746,4351,0
1002,12/30/2015,14 ST-UNION SQ,1295653043,498567996,3245,986,4231,0
4,01/01/2016,125 ST,149283761,108805385,2122,1930,4052,0
0,01/01/2016,103 ST,124275451,97068537,1382,2627,4009,0
428,12/27/2015,42 ST-PORT AUTH,322877013,85899986,3057,729,3786,19
2,01/01/2016,116 ST,434045322,443270013,2226,1544,3770,0
587,12/27/2015,W 4 ST-WASH SQ,802203424,894862566,2818,872,3690,0
1381,12/31/2015,W 4 ST-WASH SQ,802331670,894987502,2703,812,3515,0
139,01/01/2016,METROPOLITAN AV,29289286,21783910,2356,1004,3360,0
35,01/01/2016,57 ST,190408877,50369205,2839,440,3279,0
48,01/01/2016,86 ST,100503631,111910230,1307,1940,3247,0
56,01/01/2016,ASTOR PL,28634541,22924796,2194,1021,3215,0
27,01/01/2016,33 ST,227628017,136211144,1830,1380,3210,0
803,12/29/2015,14 ST-UNION SQ,1295567266,498490245,2443,728,3171,0
43,01/01/2016,77 ST,230246716,88471646,1431,1737,3168,0
7,01/01/2016,14 ST,263727289,52602844,2026,1126,3152,0
...,...,...,...,...,...,...,...,...
941,12/29/2015,NEPTUNE AV,6424324,2565602,10,7,17,0
1058,12/30/2015,BEACH 105 ST,118563268,1583858,3,14,17,0
1140,12/30/2015,NEPTUNE AV,6425775,2566033,4,12,16,0
965,12/29/2015,RIT-ROOSEVELT,7173824,442891,12,4,16,0
544,12/27/2015,NEPTUNE AV,6421950,2564896,7,9,16,0
678,12/28/2015,CHRISTOPHER ST,464173,397316,0,14,14,0
1,01/01/2016,111 ST,56026967,20703956,7,7,14,0
514,12/27/2015,HARRISON,139880,369955,1,13,14,1
468,12/27/2015,BROAD CHANNEL,1754842,603352,9,5,14,0
581,12/27/2015,TOMPKINSVILLE,8610094,2414987,13,0,13,7
660,12/28/2015,BEACH 105 ST,118562910,1583421,1,12,13,0
859,12/29/2015,BEACH 105 ST,118563085,1583640,0,13,13,0
865,12/29/2015,BROAD CHANNEL,1755269,603496,7,6,13,0
462,12/27/2015,BEACH 105 ST,118562859,1583355,1,12,13,0
1343,12/31/2015,NEWARK C,2228258,171638,13,0,13,6
263,12/26/2015,BEACH 105 ST,118562791,1583283,2,10,12,0
1375,12/31/2015,TOMPKINSVILLE,8612291,2414987,10,0,10,7
780,12/28/2015,TOMPKINSVILLE,8610382,2414987,10,0,10,7
946,12/29/2015,NEWARK C,212808,119025,4,5,9,1
979,12/29/2015,TOMPKINSVILLE,8611022,2414987,9,0,9,7
1262,12/31/2015,BROAD CHANNEL,1755899,603706,5,3,8,0
269,12/26/2015,BROAD CHANNEL,1754732,603297,7,1,8,0
1177,12/30/2015,TOMPKINSVILLE,8611660,2414987,7,0,7,7
666,12/28/2015,BROAD CHANNEL,1754949,603409,4,1,5,0
383,12/26/2015,TOMPKINSVILLE,8609660,2414987,4,0,4,7
1179,12/30/2015,TWENTY THIRD ST,3955,123279,0,3,3,1
151,01/01/2016,NEWARK C,857295,196567,2,1,3,7
549,12/27/2015,NEWARK C,2316259,154778,0,0,0,2
350,12/26/2015,NEWARK C,503857,32683,0,0,0,0
1145,12/30/2015,NEWARK C,742281,41595,0,0,0,0

In [21]:
for r in range(data_reset.shape[0]):
    if data_reset.ix[r,'WEEKDAY'] =='Weekday':
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(5)
    else:
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(2)

KeyError: 'WEEKDAY'

In [ ]:
data_reset

In [ ]:
testweekend = data_reset[(data_reset.WEEKDAY == 'Weekday')]

In [ ]:
testweekend

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#data_reset[data_reset.STATION=='WORLD TRADE CTR'].dTOTAL.plot(kind='bar');
data_reset[data_reset.STATION=='WORLD TRADE CTR'].hist(by = data_reset.DATE, bins = 25, figsize = (100,50));