In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
"""
list_data =[]
list_weeks = ['160102', '160109', '160116','160130','160206','160213',
              '160220','160227','160305','160312','160319','160326','160402']
for u in list_weeks:
    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'
    print(url)
    list_data.append(pd.read_csv(url))

data = pd.concat(list_data)
del list_data"""

"\nlist_data =[]\nlist_weeks = ['160102', '160109', '160116','160130','160206','160213',\n              '160220','160227','160305','160312','160319','160326','160402']\nfor u in list_weeks:\n    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'\n    print(url)\n    list_data.append(pd.read_csv(url))\n\ndata = pd.concat(list_data)\ndel list_data"

In [3]:
data = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_160109.txt")

In [4]:
data.columns = [column.strip() for column in data.columns]
data.columns

Index([u'C/A', u'UNIT', u'SCP', u'STATION', u'LINENAME', u'DIVISION', u'DATE',
       u'TIME', u'DESC', u'ENTRIES', u'EXITS'],
      dtype='object')

In [5]:
data.rename(columns={"EXITS": "EXIT", "ENTRIES": "ENTRY"}, inplace=True)

In [6]:
data['dENTRY'] = 0
data['dEXIT'] = 0

In [7]:
data['dENTRY'] = data.ENTRY.shift(-1) - data.ENTRY
data['dEXIT'] = data.EXIT.shift(-1) - data.EXIT
data['dTOTAL'] = data.dENTRY + data.dEXIT

In [8]:
#diff = data['ENTRY'].iloc[1:].values - data['ENTRY'].iloc[:-1].values
#data['DENTRY'][1:] = diff
#diff = data['EXIT'].iloc[:-1].values - data['EXIT'].iloc[1:].values
#data['DEXIT'][1:] = diff

In [9]:
data['DATETIME'] = pd.to_datetime(data.DATE + data.TIME, format='%m/%d/%Y%H:%M:%S')
data['HOUR'] = data['DATETIME'].apply(lambda x: x.hour)

In [10]:
data['WEEKDAY']=data.DATETIME.apply(lambda x: 'Weekday' if 0<=x.weekday()<5 else 'Weekend')

In [11]:
daysofweek = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

whatdayofweek = lambda x: daysofweek[x.weekday()]


data['DAYOFWEEK'] = data.DATETIME.apply(whatdayofweek)

In [12]:
data_cleaned = data[(data['dENTRY'] >= 0) & (data['dENTRY'] <= 5000) & (data['dEXIT'] >= 0) & (data['dEXIT'] <= 5000)]

In [13]:
data_0to4 = data_cleaned[(data_cleaned.HOUR ==0)|(data_cleaned.HOUR==1)]

In [14]:
data_0to4

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,DATETIME,HOUR,WEEKDAY,DAYOFWEEK
503,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/02/2016,01:00:00,REGULAR,2029643,3582673,11,19,30,2016-01-02 01:00:00,1,Weekend,Saturday
509,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/03/2016,01:00:00,REGULAR,2030945,3584358,18,14,32,2016-01-03 01:00:00,1,Weekend,Sunday
515,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/04/2016,01:00:00,REGULAR,2031863,3585640,7,10,17,2016-01-04 01:00:00,1,Weekday,Monday
521,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/05/2016,01:00:00,REGULAR,2033653,3588436,18,9,27,2016-01-05 01:00:00,1,Weekday,Tuesday
527,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/06/2016,01:00:00,REGULAR,2035256,3591288,11,12,23,2016-01-06 01:00:00,1,Weekday,Wednesday
533,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/07/2016,01:00:00,REGULAR,2037063,3594070,17,12,29,2016-01-07 01:00:00,1,Weekday,Thursday
539,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/08/2016,01:00:00,REGULAR,2038939,3596919,19,13,32,2016-01-08 01:00:00,1,Weekday,Friday
545,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/02/2016,01:00:00,REGULAR,3298900,2159570,10,6,16,2016-01-02 01:00:00,1,Weekend,Saturday
551,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/03/2016,01:00:00,REGULAR,3300052,2160275,14,2,16,2016-01-03 01:00:00,1,Weekend,Sunday
557,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/04/2016,01:00:00,REGULAR,3300889,2160760,4,5,9,2016-01-04 01:00:00,1,Weekday,Monday
563,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/05/2016,01:00:00,REGULAR,3302629,2161615,10,6,16,2016-01-05 01:00:00,1,Weekday,Tuesday
569,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/06/2016,01:00:00,REGULAR,3304264,2162462,6,7,13,2016-01-06 01:00:00,1,Weekday,Wednesday
575,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/07/2016,01:00:00,REGULAR,3305959,2163280,7,3,10,2016-01-07 01:00:00,1,Weekday,Thursday
581,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/08/2016,01:00:00,REGULAR,3307707,2164158,15,1,16,2016-01-08 01:00:00,1,Weekday,Friday
587,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/02/2016,01:00:00,REGULAR,7196391,3197093,9,3,12,2016-01-02 01:00:00,1,Weekend,Saturday
593,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/03/2016,01:00:00,REGULAR,7197285,3197485,9,0,9,2016-01-03 01:00:00,1,Weekend,Sunday
599,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/04/2016,01:00:00,REGULAR,7197837,3197727,2,0,2,2016-01-04 01:00:00,1,Weekday,Monday
605,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/05/2016,01:00:00,REGULAR,7199234,3198199,5,1,6,2016-01-05 01:00:00,1,Weekday,Tuesday
611,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/06/2016,01:00:00,REGULAR,7200661,3198729,4,1,5,2016-01-06 01:00:00,1,Weekday,Wednesday
617,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/07/2016,01:00:00,REGULAR,7201985,3199253,5,2,7,2016-01-07 01:00:00,1,Weekday,Thursday
623,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/08/2016,01:00:00,REGULAR,7203301,3199739,9,7,16,2016-01-08 01:00:00,1,Weekday,Friday
629,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/02/2016,01:00:00,REGULAR,1883334,708143,6,1,7,2016-01-02 01:00:00,1,Weekend,Saturday
635,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/03/2016,01:00:00,REGULAR,1884068,708366,5,1,6,2016-01-03 01:00:00,1,Weekend,Sunday
641,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/04/2016,01:00:00,REGULAR,1884596,708511,7,4,11,2016-01-04 01:00:00,1,Weekday,Monday
647,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/05/2016,01:00:00,REGULAR,1885765,708882,6,4,10,2016-01-05 01:00:00,1,Weekday,Tuesday
653,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/06/2016,01:00:00,REGULAR,1887383,709317,4,2,6,2016-01-06 01:00:00,1,Weekday,Wednesday
659,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/07/2016,01:00:00,REGULAR,1888423,709706,4,0,4,2016-01-07 01:00:00,1,Weekday,Thursday
665,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/08/2016,01:00:00,REGULAR,1889563,710083,7,0,7,2016-01-08 01:00:00,1,Weekday,Friday
671,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,01/02/2016,01:00:00,REGULAR,6608897,2931579,4,0,4,2016-01-02 01:00:00,1,Weekend,Saturday
677,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,01/03/2016,01:00:00,REGULAR,6609627,2931817,6,0,6,2016-01-03 01:00:00,1,Weekend,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195181,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,01/07/2016,00:00:00,REGULAR,1426556,14725,8,2,10,2016-01-07 00:00:00,0,Weekday,Thursday
195187,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,01/08/2016,00:00:00,REGULAR,1428037,14742,5,1,6,2016-01-08 00:00:00,0,Weekday,Friday
195193,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/02/2016,00:00:00,REGULAR,274332,11203,0,3,3,2016-01-02 00:00:00,0,Weekend,Saturday
195199,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/03/2016,00:00:00,REGULAR,274686,11210,6,1,7,2016-01-03 00:00:00,0,Weekend,Sunday
195205,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/04/2016,00:00:00,REGULAR,275009,11216,0,1,1,2016-01-04 00:00:00,0,Weekday,Monday
195211,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/05/2016,00:00:00,REGULAR,275274,11228,0,0,0,2016-01-05 00:00:00,0,Weekday,Tuesday
195217,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/06/2016,00:00:00,REGULAR,275455,11236,0,0,0,2016-01-06 00:00:00,0,Weekday,Wednesday
195223,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/07/2016,00:00:00,REGULAR,275625,11242,0,1,1,2016-01-07 00:00:00,0,Weekday,Thursday
195229,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/08/2016,00:00:00,REGULAR,275809,11251,0,0,0,2016-01-08 00:00:00,0,Weekday,Friday
195235,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2016,00:00:00,REGULAR,2585381,375827,0,0,0,2016-01-02 00:00:00,0,Weekend,Saturday
195241,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2016,00:00:00,REGULAR,2585798,375834,7,0,7,2016-01-03 00:00:00,0,Weekend,Sunday
195247,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2016,00:00:00,REGULAR,2586133,375844,2,0,2,2016-01-04 00:00:00,0,Weekday,Monday
195253,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2016,00:00:00,REGULAR,2586416,375847,0,1,1,2016-01-05 00:00:00,0,Weekday,Tuesday
195259,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/06/2016,00:00:00,REGULAR,2586670,375856,0,4,4,2016-01-06 00:00:00,0,Weekday,Wednesday
195265,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/07/2016,00:00:00,REGULAR,2586896,375867,0,0,0,2016-01-07 00:00:00,0,Weekday,Thursday
195271,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/08/2016,00:00:00,REGULAR,2587113,375876,1,0,1,2016-01-08 00:00:00,0,Weekday,Friday
195277,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/02/2016,00:00:00,REGULAR,2051,62,0,0,0,2016-01-02 00:00:00,0,Weekend,Saturday
195283,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/03/2016,00:00:00,REGULAR,2051,62,0,0,0,2016-01-03 00:00:00,0,Weekend,Sunday
195289,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/04/2016,00:00:00,REGULAR,2052,62,0,0,0,2016-01-04 00:00:00,0,Weekday,Monday
195295,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/05/2016,00:00:00,REGULAR,2052,62,0,0,0,2016-01-05 00:00:00,0,Weekday,Tuesday
195301,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/06/2016,00:00:00,REGULAR,2052,62,0,0,0,2016-01-06 00:00:00,0,Weekday,Wednesday
195307,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/07/2016,00:00:00,REGULAR,2053,62,0,0,0,2016-01-07 00:00:00,0,Weekday,Thursday
195313,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/08/2016,00:00:00,REGULAR,2055,62,0,0,0,2016-01-08 00:00:00,0,Weekday,Friday
195319,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/02/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-02 00:00:00,0,Weekend,Saturday
195325,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/03/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-03 00:00:00,0,Weekend,Sunday
195331,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/04/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-04 00:00:00,0,Weekday,Monday
195337,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/05/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-05 00:00:00,0,Weekday,Tuesday
195343,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/06/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-06 00:00:00,0,Weekday,Wednesday
195349,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/07/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-07 00:00:00,0,Weekday,Thursday
195355,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/08/2016,00:00:00,REGULAR,5554,230,0,0,0,2016-01-08 00:00:00,0,Weekday,Friday

In [15]:
data_grouped = data_0to4.groupby(['DATE','STATION']).sum()

In [16]:
data_grouped

                                 ENTRY        EXIT  dENTRY  dEXIT  dTOTAL  \
DATE       STATION
01/02/2016 103 ST            124292857    97082540     409    880    1289
           111 ST             56027116    20704083       1      3       4
           116 ST            434063625   443280041     599    593    1192
           116 ST-COLUMBIA  1209308119   255759947      82     88     170
           125 ST            149301349   108819408     808    920    1728
           135 ST            202830516    30308699      54    141     195
           137 ST CITY COL    51602239    40881272     190    491     681
           14 ST             263736650    52611697     664    345    1009
           14 ST-UNION SQ   1295877780   498774065    3270   1110    4380
           14TH STREET         1879593     2090588      40     26      66
           155 ST             30735962    23508432     101    243     344
           157 ST             31485555    21134850     183    538     721
           163 ST-AMSTERDM    16700891    11279726      36    147     183
           170 ST           1284547644  2348552000     105    162     267
           174 ST             21574725    14404241     112    271     383
           18 AV              20549689    21081814      18    128     146
           181 ST             51378786    42732008      85    385     470
           20 AV              14551209    12591268      10     74      84
           21 ST               5582074     6317446      77     51     128
           219 ST              9572016     5886603      68     66     134
           225 ST             14067326     7766473      64     83     147
           23 ST            2188282885  1831059646     555    264     819
           233 ST             95215789     4509102      78     61     139
           238 ST             18953610      873765      81      3      84
           25 AV               3649154     1234214      36     42      78
           28 ST            1511600995  2315685958     755    376    1131
           3 AV 138 ST        17466805    14920424     114    307     421
           33 ST             227640316   136222213     759    237     996
           34 ST-PENN STA   1882290441  1219846382     582    427    1009
           36 ST             863862460  1233235525     228    408     636
...                                ...         ...     ...    ...     ...
01/08/2016 RIT-MANHATTAN       4275055       69311      37     10      47
           RIT-ROOSEVELT       7210044      443519      12      4      16
           ROCKAWAY AV       716586985    42281815      83    169     252
           ROCKAWAY BLVD     271293093    12935458      97     80     177
           ROCKAWAY PARK B   105079639    10829113      13     47      60
           SENECA AVE          5081368     5676434      23    122     145
           SHEEPSHEAD BAY     39587291    35763602     130    306     436
           SHEPHERD AV        16707560    14342351      54    110     164
           SIMPSON ST         37057685    10252537     114     34     148
           SOUTH FERRY        35013810    30693907     155    360     515
           SUTPHIN BLVD       17893057     9628528      32    127     159
           SUTPHIN-ARCHER       432638      412241     205    382     587
           SUTTER AV          11137875    14941474      97    201     298
           THIRTY ST           3950907     3486458      28     18      46
           THIRTY THIRD ST     6077723     4147085     215     82     297
           TOMPKINSVILLE       8616814     2414988      15      0      15
           TREMONT AV        128880065    10692818     152    607     759
           TWENTY THIRD ST     3915829     1270098      53     67     120
           UTICA AV          102486640    49809993     217    568     785
           VAN SICLEN AV      12178176    11934123      45    121     166
           VAN SICLEN AVE     13202118    13710387      45    154     199
           W 4 ST-WASH SQ    802588665   895235063    1931    563    2494
           WAKEFIELD/241      16035499    16589893     120    278     398
           WALL ST           532982315   277726806      84     57     141
           WEST FARMS SQ     438059499    72805614     164    225     389
           WHITEHALL S-FRY   131631271    11952061     126    132     258
           WINTHROP ST        31366451     5540838      79     56     135
           WOODHAVEN BLVD     54823552    36307539     156    471     627
           YORK ST            31300397    28715945      75     94     169
           ZEREGA AV          53484080      475466      21     83     104

                            HOUR
DATE       STATION
01/02/2016 103 ST              0
           111 ST              0
           116 ST              0
           116 ST-COLUMBIA     0
           125 ST              0
           135 ST              0
           137 ST CITY COL     0
           14 ST               0
           14 ST-UNION SQ      0
           14TH STREET         3
           155 ST              0
           157 ST              0
           163 ST-AMSTERDM     0
           170 ST              0
           174 ST              0
           18 AV               0
           181 ST              0
           20 AV               0
           21 ST               0
           219 ST              0
           225 ST              0
           23 ST               0
           233 ST              0
           238 ST              0
           25 AV               0
           28 ST               0
           3 AV 138 ST         0
           33 ST               0
           34 ST-PENN STA     21
           36 ST               0
...                          ...
01/08/2016 RIT-MANHATTAN       0
           RIT-ROOSEVELT       0
           ROCKAWAY AV         0
           ROCKAWAY BLVD       0
           ROCKAWAY PARK B     0
           SENECA AVE          0
           SHEEPSHEAD BAY      0
           SHEPHERD AV         0
           SIMPSON ST          0
           SOUTH FERRY         0
           SUTPHIN BLVD        0
           SUTPHIN-ARCHER      0
           SUTTER AV           0
           THIRTY ST           4
           THIRTY THIRD ST     2
           TOMPKINSVILLE       7
           TREMONT AV          0
           TWENTY THIRD ST     5
           UTICA AV            0
           VAN SICLEN AV       0
           VAN SICLEN AVE      0
           W 4 ST-WASH SQ      0
           WAKEFIELD/241       0
           WALL ST            28
           WEST FARMS SQ       0
           WHITEHALL S-FRY     0
           WINTHROP ST         0
           WOODHAVEN BLVD      0
           YORK ST             0
           ZEREGA AV           0

[1387 rows x 6 columns]

In [20]:
data_reset = (data_grouped
    .reset_index()
    .sort_values(['dTOTAL'], ascending=(False))
)
data_reset

,DATE,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR
207,01/03/2016,14 ST-UNION SQ,1295944355,498836823,4799,1416,6215,0
388,01/03/2016,W 4 ST-WASH SQ,802415006,895073803,3437,1012,4449,0
8,01/02/2016,14 ST-UNION SQ,1295877780,498774065,3270,1110,4380,0
1197,01/08/2016,14 ST-UNION SQ,1296397089,499217685,3171,984,4155,0
229,01/03/2016,42 ST-PORT AUTH,323144274,86094674,2727,785,3512,19
190,01/02/2016,W 4 ST-WASH SQ,802387491,895044524,2576,744,3320,0
30,01/02/2016,42 ST-PORT AUTH,323108446,86068600,2394,689,3083,19
244,01/03/2016,8 AV,197187830,90804574,2214,839,3053,0
290,01/03/2016,DELANCEY/ESSEX,1710802970,1111010355,2106,872,2978,0
1000,01/07/2016,14 ST-UNION SQ,1296293013,499129897,2332,590,2922,0
250,01/03/2016,96 ST,769877278,1415921628,1020,1850,2870,0
803,01/06/2016,14 ST-UNION SQ,1296189016,499042401,1976,577,2553,0
1378,01/08/2016,W 4 ST-WASH SQ,802588665,895235063,1931,563,2494,0
626,01/05/2016,42 ST-PORT AUTH,323202360,86138464,1350,949,2299,19
604,01/05/2016,14 ST-UNION SQ,1296093008,498962844,1708,556,2264,0
405,01/04/2016,14 ST-UNION SQ,1295998660,498883455,1682,509,2191,0
203,01/03/2016,125 ST,149323429,108840339,948,1142,2090,0
51,01/02/2016,96 ST,769846610,1415895655,810,1229,2039,0
45,01/02/2016,8 AV,197162677,90784106,1392,619,2011,0
91,01/02/2016,DELANCEY/ESSEX,1710786004,1110995329,1206,777,1983,0
1180,01/07/2016,W 4 ST-WASH SQ,802548782,895198189,1500,413,1913,0
983,01/06/2016,W 4 ST-WASH SQ,802509930,895162445,1342,448,1790,0
1239,01/08/2016,96 ST,770161617,1416112798,779,976,1755,0
4,01/02/2016,125 ST,149301349,108819408,808,920,1728,0
1233,01/08/2016,8 AV,197343342,90922950,1217,506,1723,0
1042,01/07/2016,96 ST,770094140,1416069805,835,885,1720,0
587,01/04/2016,W 4 ST-WASH SQ,802437943,895095445,1346,361,1707,0
1218,01/08/2016,42 ST-PORT AUTH,322695560,102180445,1104,599,1703,19
241,01/03/2016,72 ST,1607631021,983050629,1001,700,1701,0
1279,01/08/2016,DELANCEY/ESSEX,1710914923,1111097855,1167,500,1667,0
...,...,...,...,...,...,...,...,...
1061,01/07/2016,BROAD CHANNEL,1757367,604250,7,4,11,0
742,01/05/2016,NEPTUNE AV,6432039,2567973,9,2,11,0
263,01/03/2016,BEACH 105 ST,118563765,1584430,1,10,11,0
64,01/02/2016,BEACH 105 ST,118563688,1584371,3,8,11,0
993,01/07/2016,111 ST,56028852,20704954,6,4,10,0
1142,01/07/2016,NEWARK C,2051695,162586,6,4,10,8
963,01/06/2016,RIT-ROOSEVELT,7203339,443436,4,6,10,0
766,01/05/2016,RIT-ROOSEVELT,7200293,443395,6,4,10,0
581,01/04/2016,TOMPKINSVILLE,8613823,2414987,10,0,10,7
865,01/06/2016,BROAD CHANNEL,1757013,604161,7,2,9,0
184,01/02/2016,TOMPKINSVILLE,8613124,2414987,9,0,9,7
859,01/06/2016,BEACH 105 ST,118564391,1585103,1,7,8,0
1174,01/07/2016,TOMPKINSVILLE,8616025,2414988,7,0,7,7
660,01/05/2016,BEACH 105 ST,118564107,1584814,1,6,7,0
747,01/05/2016,NEWARK C,110195,108230,4,2,6,1
780,01/05/2016,TOMPKINSVILLE,8614533,2414987,6,0,6,7
977,01/06/2016,TOMPKINSVILLE,8615251,2414987,5,0,5,7
979,01/06/2016,TWENTY THIRD ST,422187,146844,1,4,5,1
467,01/04/2016,BROAD CHANNEL,1756377,603955,2,3,5,0
1,01/02/2016,111 ST,56027116,20704083,1,3,4,0
945,01/06/2016,NEWARK C,745800,41736,0,2,2,0
398,01/04/2016,111 ST,56027132,20704100,1,1,2,0
245,01/03/2016,80 ST,130651796,6693581,0,2,2,0
200,01/03/2016,111 ST,56027128,20704097,1,0,1,0
186,01/02/2016,TWENTY THIRD ST,4109,127966,0,1,1,0
443,01/04/2016,80 ST,130651797,6693585,0,0,0,0
446,01/04/2016,88 ST,8712305,8671724,0,0,0,0
248,01/03/2016,88 ST,8712304,8671724,0,0,0,0
350,01/03/2016,NEWARK C,2325662,155002,0,0,0,2
151,01/02/2016,NEWARK C,505591,32711,0,0,0,0

In [18]:
for r in range(data_reset.shape[0]):
    if data_reset.ix[r,'WEEKDAY'] =='Weekday':
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(5)
    else:
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(2)

KeyError: 'WEEKDAY'

In [ ]:
data_reset

In [ ]:
testweekend = data_reset[(data_reset.WEEKDAY == 'Weekday')]

In [ ]:
testweekend

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#data_reset[data_reset.STATION=='WORLD TRADE CTR'].dTOTAL.plot(kind='bar');
data_reset[data_reset.STATION=='WORLD TRADE CTR'].hist(by = data_reset.DATE, bins = 25, figsize = (100,50));