In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
"""
list_data =[]
list_weeks = ['160102', '160109', '160116','160130','160206','160213',
              '160220','160227','160305','160312','160319','160326','160402']
for u in list_weeks:
    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'
    print(url)
    list_data.append(pd.read_csv(url))

data = pd.concat(list_data)
del list_data"""

"\nlist_data =[]\nlist_weeks = ['160102', '160109', '160116','160130','160206','160213',\n              '160220','160227','160305','160312','160319','160326','160402']\nfor u in list_weeks:\n    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'\n    print(url)\n    list_data.append(pd.read_csv(url))\n\ndata = pd.concat(list_data)\ndel list_data"

In [3]:
data = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_160130.txt")

In [4]:
data.columns = [column.strip() for column in data.columns]
data.columns

Index([u'C/A', u'UNIT', u'SCP', u'STATION', u'LINENAME', u'DIVISION', u'DATE',
       u'TIME', u'DESC', u'ENTRIES', u'EXITS'],
      dtype='object')

In [5]:
data.rename(columns={"EXITS": "EXIT", "ENTRIES": "ENTRY"}, inplace=True)

In [6]:
data['dENTRY'] = 0
data['dEXIT'] = 0

In [7]:
data['dENTRY'] = data.ENTRY.shift(-1) - data.ENTRY
data['dEXIT'] = data.EXIT.shift(-1) - data.EXIT
data['dTOTAL'] = data.dENTRY + data.dEXIT

In [8]:
#diff = data['ENTRY'].iloc[1:].values - data['ENTRY'].iloc[:-1].values
#data['DENTRY'][1:] = diff
#diff = data['EXIT'].iloc[:-1].values - data['EXIT'].iloc[1:].values
#data['DEXIT'][1:] = diff

In [9]:
data['DATETIME'] = pd.to_datetime(data.DATE + data.TIME, format='%m/%d/%Y%H:%M:%S')
data['HOUR'] = data['DATETIME'].apply(lambda x: x.hour)

In [10]:
data['WEEKDAY']=data.DATETIME.apply(lambda x: 'Weekday' if 0<=x.weekday()<5 else 'Weekend')

In [11]:
daysofweek = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

whatdayofweek = lambda x: daysofweek[x.weekday()]


data['DAYOFWEEK'] = data.DATETIME.apply(whatdayofweek)

In [12]:
data_cleaned = data[(data['dENTRY'] >= 0) & (data['dENTRY'] <= 5000) & (data['dEXIT'] >= 0) & (data['dEXIT'] <= 5000)]

In [13]:
data_0to4 = data_cleaned[(data_cleaned.HOUR ==0)|(data_cleaned.HOUR==1)]

In [14]:
data_0to4

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,DATETIME,HOUR,WEEKDAY,DAYOFWEEK
503,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/23/2016,01:00:00,REGULAR,2061371,3633165,9,13,22,2016-01-23 01:00:00,1,Weekend,Saturday
509,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/24/2016,01:00:00,REGULAR,2061733,3633797,3,6,9,2016-01-24 01:00:00,1,Weekend,Sunday
515,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/25/2016,01:00:00,REGULAR,2062482,3634882,9,9,18,2016-01-25 01:00:00,1,Weekday,Monday
521,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/26/2016,01:00:00,REGULAR,2064148,3637581,6,14,20,2016-01-26 01:00:00,1,Weekday,Tuesday
527,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/27/2016,01:00:00,REGULAR,2065990,3640650,3,19,22,2016-01-27 01:00:00,1,Weekday,Wednesday
533,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/28/2016,01:00:00,REGULAR,2067827,3643760,0,7,7,2016-01-28 01:00:00,1,Weekday,Thursday
539,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/29/2016,01:00:00,REGULAR,2069613,3646803,0,6,6,2016-01-29 01:00:00,1,Weekday,Friday
545,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/23/2016,01:00:00,REGULAR,3329009,2174786,6,4,10,2016-01-23 01:00:00,1,Weekend,Saturday
551,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/24/2016,01:00:00,REGULAR,3329347,2175013,0,4,4,2016-01-24 01:00:00,1,Weekend,Sunday
557,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/25/2016,01:00:00,REGULAR,3330052,2175411,8,0,8,2016-01-25 01:00:00,1,Weekday,Monday
563,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/26/2016,01:00:00,REGULAR,3331624,2176156,8,2,10,2016-01-26 01:00:00,1,Weekday,Tuesday
569,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/27/2016,01:00:00,REGULAR,3333480,2177030,8,3,11,2016-01-27 01:00:00,1,Weekday,Wednesday
575,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/28/2016,01:00:00,REGULAR,3335276,2177947,0,0,0,2016-01-28 01:00:00,1,Weekday,Thursday
581,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/29/2016,01:00:00,REGULAR,3337058,2178829,0,3,3,2016-01-29 01:00:00,1,Weekday,Friday
587,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/23/2016,01:00:00,REGULAR,7219200,3205841,3,1,4,2016-01-23 01:00:00,1,Weekend,Saturday
593,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/24/2016,01:00:00,REGULAR,7219474,3205930,5,0,5,2016-01-24 01:00:00,1,Weekend,Sunday
599,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/25/2016,01:00:00,REGULAR,7220023,3206104,3,2,5,2016-01-25 01:00:00,1,Weekday,Monday
605,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/26/2016,01:00:00,REGULAR,7221314,3206512,3,1,4,2016-01-26 01:00:00,1,Weekday,Tuesday
611,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/27/2016,01:00:00,REGULAR,7222675,3206997,2,1,3,2016-01-27 01:00:00,1,Weekday,Wednesday
617,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/28/2016,01:00:00,REGULAR,7224040,3207512,0,1,1,2016-01-28 01:00:00,1,Weekday,Thursday
623,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/29/2016,01:00:00,REGULAR,7225384,3207990,0,0,0,2016-01-29 01:00:00,1,Weekday,Friday
629,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/23/2016,01:00:00,REGULAR,1902234,714757,2,0,2,2016-01-23 01:00:00,1,Weekend,Saturday
635,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/24/2016,01:00:00,REGULAR,1902481,714822,2,1,3,2016-01-24 01:00:00,1,Weekend,Sunday
641,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/25/2016,01:00:00,REGULAR,1902980,714921,4,3,7,2016-01-25 01:00:00,1,Weekday,Monday
647,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/26/2016,01:00:00,REGULAR,1903960,715248,3,0,3,2016-01-26 01:00:00,1,Weekday,Tuesday
653,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/27/2016,01:00:00,REGULAR,1905030,715624,2,1,3,2016-01-27 01:00:00,1,Weekday,Wednesday
659,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/28/2016,01:00:00,REGULAR,1906144,715982,0,0,0,2016-01-28 01:00:00,1,Weekday,Thursday
665,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/29/2016,01:00:00,REGULAR,1907199,716364,0,2,2,2016-01-29 01:00:00,1,Weekday,Friday
671,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,01/23/2016,01:00:00,REGULAR,6625920,2938441,2,1,3,2016-01-23 01:00:00,1,Weekend,Saturday
677,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,01/24/2016,01:00:00,REGULAR,6626134,2938521,0,1,1,2016-01-24 01:00:00,1,Weekend,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193564,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,01/28/2016,00:00:00,REGULAR,1453578,15117,9,1,10,2016-01-28 00:00:00,0,Weekday,Thursday
193570,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,01/29/2016,00:00:00,REGULAR,1455152,15126,9,3,12,2016-01-29 00:00:00,0,Weekday,Friday
193576,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/23/2016,00:00:00,REGULAR,278290,11371,1,2,3,2016-01-23 00:00:00,0,Weekend,Saturday
193582,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/24/2016,00:00:00,REGULAR,278298,11391,0,0,0,2016-01-24 00:00:00,0,Weekend,Sunday
193588,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/25/2016,00:00:00,REGULAR,278398,11394,0,2,2,2016-01-25 00:00:00,0,Weekday,Monday
193594,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/26/2016,00:00:00,REGULAR,278507,11399,2,0,2,2016-01-26 00:00:00,0,Weekday,Tuesday
193601,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/27/2016,00:00:00,REGULAR,278634,11401,1,0,1,2016-01-27 00:00:00,0,Weekday,Wednesday
193607,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/28/2016,00:00:00,REGULAR,278771,11405,0,1,1,2016-01-28 00:00:00,0,Weekday,Thursday
193613,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/29/2016,00:00:00,REGULAR,278910,11407,0,0,0,2016-01-29 00:00:00,0,Weekday,Friday
193619,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/23/2016,00:00:00,REGULAR,2590053,376052,1,0,1,2016-01-23 00:00:00,0,Weekend,Saturday
193625,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/24/2016,00:00:00,REGULAR,2590056,376069,0,0,0,2016-01-24 00:00:00,0,Weekend,Sunday
193631,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/25/2016,00:00:00,REGULAR,2590151,376073,0,0,0,2016-01-25 00:00:00,0,Weekday,Monday
193637,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/26/2016,00:00:00,REGULAR,2590288,376077,0,2,2,2016-01-26 00:00:00,0,Weekday,Tuesday
193644,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/27/2016,00:00:00,REGULAR,2590429,376089,1,2,3,2016-01-27 00:00:00,0,Weekday,Wednesday
193650,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/28/2016,00:00:00,REGULAR,2590621,376097,1,0,1,2016-01-28 00:00:00,0,Weekday,Thursday
193656,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/29/2016,00:00:00,REGULAR,2590790,376103,1,0,1,2016-01-29 00:00:00,0,Weekday,Friday
193662,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/23/2016,00:00:00,REGULAR,2073,62,0,0,0,2016-01-23 00:00:00,0,Weekend,Saturday
193668,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/24/2016,00:00:00,REGULAR,2073,62,0,0,0,2016-01-24 00:00:00,0,Weekend,Sunday
193674,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/25/2016,00:00:00,REGULAR,2073,62,0,0,0,2016-01-25 00:00:00,0,Weekday,Monday
193680,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/26/2016,00:00:00,REGULAR,2073,62,0,0,0,2016-01-26 00:00:00,0,Weekday,Tuesday
193687,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/27/2016,00:00:00,REGULAR,2073,62,0,0,0,2016-01-27 00:00:00,0,Weekday,Wednesday
193693,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/28/2016,00:00:00,REGULAR,2075,62,0,0,0,2016-01-28 00:00:00,0,Weekday,Thursday
193699,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/29/2016,00:00:00,REGULAR,2075,62,0,0,0,2016-01-29 00:00:00,0,Weekday,Friday
193705,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/23/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-01-23 00:00:00,0,Weekend,Saturday
193711,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/24/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-01-24 00:00:00,0,Weekend,Sunday
193717,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/25/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-01-25 00:00:00,0,Weekday,Monday
193723,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/26/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-01-26 00:00:00,0,Weekday,Tuesday
193730,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/27/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-01-27 00:00:00,0,Weekday,Wednesday
193736,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/28/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-01-28 00:00:00,0,Weekday,Thursday
193742,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/29/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-01-29 00:00:00,0,Weekday,Friday

In [15]:
data_grouped = data_0to4.groupby(['DATE','STATION']).sum()

In [16]:
data_grouped

                                 ENTRY        EXIT  dENTRY  dEXIT  dTOTAL  \
DATE       STATION
01/23/2016 103 ST            150481729   593152389     536   1061    1597
           111 ST             56034725    20707009       5      7      12
           116 ST            434699946   443606837     672    897    1569
           116 ST-COLUMBIA  1209538396   255877048     308    198     506
           125 ST            149985358   109337393     870    949    1819
           135 ST            202922219    30378536      68    183     251
           137 ST CITY COL    51836195    41048376     178    661     839
           14 ST             264095354    52919122     984    322    1306
           14 ST-UNION SQ   1292952833   498925989    4335   1394    5729
           14TH STREET         1935210     1494398      34     70     104
           155 ST             30857781    23586293     108    336     444
           157 ST             31691860    21276091     189    645     834
           163 ST-AMSTERDM    16765017    11304547      61    147     208
           170 ST           1284678548  2348616193      73    178     251
           174 ST             21690102    14506081     105    295     400
           18 AV              20620142    21161968      11    144     155
           181 ST             51584761    42898547      99    443     542
           20 AV              14606785    12620760       9     25      34
           21 ST               5614564     6353566     115     94     209
           219 ST              9635357     5915276      56     77     133
           225 ST             10706632     6333551      59    118     177
           23 ST            2188969310  1831620784    1013    346    1359
           233 ST             95315976     4540882      75     65     140
           238 ST             19026360      875499      67      5      72
           25 AV               3745297     1259154      58     90     148
           28 ST            1512259201  2082324181    1194    469    1663
           3 AV 138 ST        17609475    15022903     175    387     562
           33 ST             345633521   136650243     798    338    1136
           34 ST-PENN STA   1883260585  1220534187     586    389     975
           36 ST              58871994   159679597     279    563     842
...                                ...         ...     ...    ...     ...
01/29/2016 RIT-MANHATTAN       2471837       28649      47      1      48
           RIT-ROOSEVELT       7270661      444674      19      3      22
           ROCKAWAY AV       716688051    42340205      80    215     295
           ROCKAWAY BLVD     271419090    12975346      96    102     198
           ROCKAWAY PARK B   105089820    10843016      15     32      47
           SENECA AVE          5130401     5723786      28    112     140
           SHEEPSHEAD BAY     39826804    35976826     148    342     490
           SHEPHERD AV        16768163    14374801      51    137     188
           SIMPSON ST         37233686    10281237     113     42     155
           SOUTH FERRY        35198058    30914860     116    346     462
           SUTPHIN BLVD       17974984     9677981      39    126     165
           SUTPHIN-ARCHER       540931      534336     164    281     445
           SUTTER AV          10704715    14845979      73    176     249
           THIRTY ST           4731774     6408871     126     61     187
           THIRTY THIRD ST    12288643     8021956     374    215     589
           TOMPKINSVILLE       8629719     2414988      15      0      15
           TREMONT AV        129058039    10799773     164    410     574
           TWENTY THIRD ST     4486825     1569801      81     63     144
           UTICA AV          102764984    50013219     251    568     819
           VAN SICLEN AV      12231878    11987582      41    113     154
           VAN SICLEN AVE     13259908    13762925      45    158     203
           W 4 ST-WASH SQ    803320252   895935150    2097    612    2709
           WAKEFIELD/241      16127849    16684742      98    243     341
           WALL ST           533345659   278004304      93    113     206
           WEST FARMS SQ     438199011    72900832     161    226     387
           WHITEHALL S-FRY   265581870    62305751     157    153     310
           WINTHROP ST        31493430     5570560      63     30      93
           WOODHAVEN BLVD     55215877    36536100     170    361     531
           YORK ST            31465708    28837154     119     84     203
           ZEREGA AV          53528485      516929      29     83     112

                            HOUR
DATE       STATION
01/23/2016 103 ST              0
           111 ST              0
           116 ST              0
           116 ST-COLUMBIA     0
           125 ST              0
           135 ST              0
           137 ST CITY COL     0
           14 ST               0
           14 ST-UNION SQ      0
           14TH STREET         2
           155 ST              0
           157 ST              0
           163 ST-AMSTERDM     0
           170 ST              0
           174 ST              0
           18 AV               0
           181 ST              0
           20 AV               0
           21 ST               0
           219 ST              0
           225 ST              0
           23 ST               0
           233 ST              0
           238 ST              0
           25 AV               0
           28 ST               0
           3 AV 138 ST         0
           33 ST               0
           34 ST-PENN STA     21
           36 ST               0
...                          ...
01/29/2016 RIT-MANHATTAN       0
           RIT-ROOSEVELT       0
           ROCKAWAY AV         0
           ROCKAWAY BLVD       0
           ROCKAWAY PARK B     0
           SENECA AVE          0
           SHEEPSHEAD BAY      0
           SHEPHERD AV         0
           SIMPSON ST          0
           SOUTH FERRY         0
           SUTPHIN BLVD        0
           SUTPHIN-ARCHER      0
           SUTTER AV           0
           THIRTY ST           5
           THIRTY THIRD ST     2
           TOMPKINSVILLE       7
           TREMONT AV          0
           TWENTY THIRD ST     4
           UTICA AV            0
           VAN SICLEN AV       0
           VAN SICLEN AVE      0
           W 4 ST-WASH SQ      0
           WAKEFIELD/241       0
           WALL ST            28
           WEST FARMS SQ       0
           WHITEHALL S-FRY     0
           WINTHROP ST         0
           WOODHAVEN BLVD      0
           YORK ST             0
           ZEREGA AV           0

[1386 rows x 6 columns]

In [19]:
data_reset = (data_grouped
    .reset_index()
    .sort_values(['dTOTAL'], ascending=(False))
)
data_reset

,DATE,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR
8,01/23/2016,14 ST-UNION SQ,1292952833,498925989,4335,1394,5729,0
188,01/23/2016,W 4 ST-WASH SQ,803120959,895749505,3373,875,4248,0
1195,01/29/2016,14 ST-UNION SQ,1293432512,499338030,3095,1086,4181,0
997,01/28/2016,14 ST-UNION SQ,1293324591,499244539,2436,715,3151,0
45,01/23/2016,8 AV,197807335,91265275,2158,825,2983,0
801,01/27/2016,14 ST-UNION SQ,1293216091,499151646,2303,630,2933,0
90,01/23/2016,DELANCEY/ESSEX,1709167341,1109987652,2014,795,2809,0
51,01/23/2016,96 ST,771015378,1416680170,1088,1644,2732,0
1377,01/29/2016,W 4 ST-WASH SQ,803320252,895935150,2097,612,2709,0
602,01/26/2016,14 ST-UNION SQ,1293109769,499060007,1878,574,2452,0
30,01/23/2016,42 ST-PORT AUTH,320634453,99711099,1864,526,2390,18
980,01/27/2016,W 4 ST-WASH SQ,803230319,895850674,1602,565,2167,0
1278,01/29/2016,DELANCEY/ESSEX,1711380984,1111481048,979,1160,2139,0
1178,01/28/2016,W 4 ST-WASH SQ,803274446,895891677,1621,511,2132,0
42,01/23/2016,72 ST,1608316363,983649007,1596,532,2128,0
1232,01/29/2016,8 AV,197976754,91381500,1489,505,1994,0
1080,01/28/2016,DELANCEY/ESSEX,1711355356,1111460667,737,1222,1959,0
883,01/27/2016,DELANCEY/ESSEX,1711330587,1111441482,726,1203,1929,0
1238,01/29/2016,96 ST,771334738,1416893203,843,1026,1869,0
849,01/27/2016,ASTOR PL,28981421,23271732,1342,503,1845,0
784,01/26/2016,W 4 ST-WASH SQ,803187754,895811353,1350,486,1836,0
4,01/23/2016,125 ST,149985358,109337393,870,949,1819,0
403,01/25/2016,14 ST-UNION SQ,1293011411,498976309,1228,513,1741,0
205,01/24/2016,14 ST-UNION SQ,1292974614,498944277,1136,599,1735,0
1040,01/28/2016,96 ST,771263404,1416847801,738,990,1728,0
111,01/23/2016,GRD CNTRL-42 ST,3966808752,1427947635,1190,534,1724,0
844,01/27/2016,96 ST,771191947,1416801606,767,925,1692,0
25,01/23/2016,28 ST,1512259201,2082324181,1194,469,1663,0
41,01/23/2016,7 AV,1908602467,839449085,973,631,1604,0
1217,01/29/2016,42 ST-PORT AUTH,323305484,102667387,1092,507,1599,19
...,...,...,...,...,...,...,...,...
246,01/24/2016,88 ST,8773143,8692349,0,1,1,0
365,01/24/2016,RIT-MANHATTAN,2457641,28524,0,1,1,0
1338,01/29/2016,NEWARK C,2745628,310810,0,1,1,4
362,01/24/2016,PROSPECT AV,24703635,5978600,0,1,1,0
237,01/24/2016,69 ST,34790377,27041620,0,1,1,0
358,01/24/2016,PARKSIDE AV,33741236,30555069,0,1,1,0
547,01/25/2016,NEWARK HM HE,21121,1696449,0,0,0,2
321,01/24/2016,JACKSON AV,129833427,1538408,0,0,0,0
546,01/25/2016,NEWARK C,1948000,267356,0,0,0,11
548,01/25/2016,NEWARK HW BMEBE,146316,775770,0,0,0,1
575,01/25/2016,SUTPHIN-ARCHER,525219,516631,0,0,0,0
511,01/25/2016,HARRISON,682394,1420043,0,0,0,1
300,01/24/2016,FOREST AVE,11493340,10783104,0,0,0,0
211,01/24/2016,174 ST,711778530,316598231,0,0,0,0
243,01/24/2016,80 ST,130677099,6698477,0,0,0,0
376,01/24/2016,SUTPHIN-ARCHER,525218,516631,0,0,0,0
214,01/24/2016,20 AV,14607030,12620874,0,0,0,0
260,01/24/2016,BAYCHESTER AV,13216221,1202901,0,0,0,0
774,01/26/2016,SUTPHIN-ARCHER,525219,516631,0,0,0,0
373,01/24/2016,SIMPSON ST,37189842,10273815,0,0,0,0
370,01/24/2016,SENECA AVE,5117437,5711507,0,0,0,0
250,01/24/2016,ALABAMA AV,8306459,8951263,0,0,0,0
745,01/26/2016,NEWARK C,429880,133619,0,0,0,1
746,01/26/2016,NEWARK HM HE,198339,1712999,0,0,0,2
348,01/24/2016,NEWARK C,2135958,165397,0,0,0,2
349,01/24/2016,NEWARK HM HE,441775,9032323,0,0,0,8
350,01/24/2016,NEWARK HW BMEBE,1542510,1429495,0,0,0,5
150,01/23/2016,NEWARK C,543283,34061,0,0,0,1
366,01/24/2016,RIT-ROOSEVELT,7256156,444516,0,0,0,0
212,01/24/2016,18 AV,20620494,21162366,0,0,0,0

In [18]:
for r in range(data_reset.shape[0]):
    if data_reset.ix[r,'WEEKDAY'] =='Weekday':
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(5)
    else:
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(2)

KeyError: 'WEEKDAY'

In [ ]:
data_reset

In [ ]:
testweekend = data_reset[(data_reset.WEEKDAY == 'Weekday')]

In [ ]:
testweekend

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#data_reset[data_reset.STATION=='WORLD TRADE CTR'].dTOTAL.plot(kind='bar');
data_reset[data_reset.STATION=='WORLD TRADE CTR'].hist(by = data_reset.DATE, bins = 25, figsize = (100,50));