In [150]:
import pandas as pd
import matplotlib.pyplot as plt

In [151]:

list_data =[]
list_weeks = ['160102', '160109', '160116','160130','160206','160213',
              '160220','160227','160305','160312','160319','160326','160402']
for u in list_weeks:
    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'
    print(url)
    list_data.append(pd.read_csv(url))

data = pd.concat(list_data)
del list_data

http://web.mta.info/developers/data/nyct/turnstile/turnstile_160102.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160109.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160116.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160130.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160206.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160213.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160220.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160227.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160305.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160312.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160319.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160326.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160402.txt

In [152]:
#data = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_160402.txt")

In [153]:
data.columns = [column.strip() for column in data.columns]
data.columns

Index([u'C/A', u'UNIT', u'SCP', u'STATION', u'LINENAME', u'DIVISION', u'DATE',
       u'TIME', u'DESC', u'ENTRIES', u'EXITS'],
      dtype='object')

In [154]:
data.rename(columns={"EXITS": "EXIT", "ENTRIES": "ENTRY"}, inplace=True)

In [155]:
data['dENTRY'] = 0
data['dEXIT'] = 0

In [156]:
data['dENTRY'] = data.ENTRY.shift(-1) - data.ENTRY
data['dEXIT'] = data.EXIT.shift(-1) - data.EXIT
data['dTOTAL'] = data.dENTRY + data.dEXIT

In [157]:
#diff = data['ENTRY'].iloc[1:].values - data['ENTRY'].iloc[:-1].values
#data['DENTRY'][1:] = diff
#diff = data['EXIT'].iloc[:-1].values - data['EXIT'].iloc[1:].values
#data['DEXIT'][1:] = diff

In [158]:
data['DATETIME'] = pd.to_datetime(data.DATE + data.TIME, format='%m/%d/%Y%H:%M:%S')
data['HOUR'] = data['DATETIME'].apply(lambda x: x.hour)

In [159]:
#data['WEEKDAY']=data.DATETIME.apply(lambda x: 'Weekday' if 0<=x.weekday()<5 else 'Weekend')

In [160]:
# daysofweek = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

# whatdayofweek = lambda x: daysofweek[x.weekday()]


# data['DAYOFWEEK'] = data.DATETIME.apply(whatdayofweek)

In [161]:
data_cleaned = data[(data['dENTRY'] >= 0) & (data['dENTRY'] <= 5000) & (data['dEXIT'] >= 0) & (data['dEXIT'] <= 5000)]

In [162]:
data_0to4 = data_cleaned[(data_cleaned.HOUR ==0)|(data_cleaned.HOUR==1)]

In [163]:
data_0to4

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,DATETIME,HOUR
504,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/26/2015,01:00:00,REGULAR,2019275,3566726,12,6,18,2015-12-26 01:00:00,1
510,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/27/2015,01:00:00,REGULAR,2020556,3568504,14,8,22,2015-12-27 01:00:00,1
516,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/28/2015,01:00:00,REGULAR,2021633,3569933,7,12,19,2015-12-28 01:00:00,1
522,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/29/2015,01:00:00,REGULAR,2023488,3572923,24,19,43,2015-12-29 01:00:00,1
528,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/30/2015,01:00:00,REGULAR,2025243,3575846,28,20,48,2015-12-30 01:00:00,1
534,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,12/31/2015,01:00:00,REGULAR,2027163,3578910,21,69,90,2015-12-31 01:00:00,1
540,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/01/2016,01:00:00,REGULAR,2028761,3581396,2,7,9,2016-01-01 01:00:00,1
546,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/26/2015,01:00:00,REGULAR,3289224,2153861,18,5,23,2015-12-26 01:00:00,1
552,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/27/2015,01:00:00,REGULAR,3290371,2154540,16,1,17,2015-12-27 01:00:00,1
558,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/28/2015,01:00:00,REGULAR,3291290,2155137,14,1,15,2015-12-28 01:00:00,1
564,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/29/2015,01:00:00,REGULAR,3293056,2156199,5,2,7,2015-12-29 01:00:00,1
570,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/30/2015,01:00:00,REGULAR,3294733,2157123,7,3,10,2015-12-30 01:00:00,1
576,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,12/31/2015,01:00:00,REGULAR,3296603,2158199,14,23,37,2015-12-31 01:00:00,1
582,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/01/2016,01:00:00,REGULAR,3298052,2159019,1,1,2,2016-01-01 01:00:00,1
588,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/26/2015,01:00:00,REGULAR,7188753,3193911,3,0,3,2015-12-26 01:00:00,1
594,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/27/2015,01:00:00,REGULAR,7189628,3194268,4,1,5,2015-12-27 01:00:00,1
600,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/28/2015,01:00:00,REGULAR,7190339,3194573,6,1,7,2015-12-28 01:00:00,1
606,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/29/2015,01:00:00,REGULAR,7191768,3195153,4,3,7,2015-12-29 01:00:00,1
612,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/30/2015,01:00:00,REGULAR,7193140,3195697,6,0,6,2015-12-30 01:00:00,1
618,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,12/31/2015,01:00:00,REGULAR,7194664,3196291,5,7,12,2015-12-31 01:00:00,1
624,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/01/2016,01:00:00,REGULAR,7195724,3196804,3,1,4,2016-01-01 01:00:00,1
630,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/26/2015,01:00:00,REGULAR,1876958,705919,2,3,5,2015-12-26 01:00:00,1
636,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/27/2015,01:00:00,REGULAR,1877702,706131,9,2,11,2015-12-27 01:00:00,1
642,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/28/2015,01:00:00,REGULAR,1878342,706347,4,1,5,2015-12-28 01:00:00,1
648,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/29/2015,01:00:00,REGULAR,1879440,706751,5,0,5,2015-12-29 01:00:00,1
654,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/30/2015,01:00:00,REGULAR,1880575,707138,1,1,2,2015-12-30 01:00:00,1
660,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,12/31/2015,01:00:00,REGULAR,1881910,707554,10,4,14,2015-12-31 01:00:00,1
666,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/01/2016,01:00:00,REGULAR,1882776,707945,0,0,0,2016-01-01 01:00:00,1
672,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,12/26/2015,01:00:00,REGULAR,6602408,2929275,4,3,7,2015-12-26 01:00:00,1
678,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,12/27/2015,01:00:00,REGULAR,6603216,2929498,8,3,11,2015-12-27 01:00:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193977,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,03/31/2016,01:00:00,REGULAR,1554761,16118,1,0,1,2016-03-31 01:00:00,1
193983,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,04/01/2016,01:00:00,REGULAR,1556710,16129,3,0,3,2016-04-01 01:00:00,1
193989,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/26/2016,01:00:00,REGULAR,291256,11918,1,2,3,2016-03-26 01:00:00,1
193995,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/27/2016,01:00:00,REGULAR,291589,11930,4,0,4,2016-03-27 01:00:00,1
194000,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/28/2016,01:00:00,REGULAR,291911,11949,1,0,1,2016-03-28 01:00:00,1
194006,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/29/2016,01:00:00,REGULAR,292125,11958,0,5,5,2016-03-29 01:00:00,1
194012,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/30/2016,01:00:00,REGULAR,292366,11973,0,0,0,2016-03-30 01:00:00,1
194018,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/31/2016,01:00:00,REGULAR,292663,11986,0,0,0,2016-03-31 01:00:00,1
194024,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,04/01/2016,01:00:00,REGULAR,292921,11992,0,0,0,2016-04-01 01:00:00,1
194030,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/26/2016,01:00:00,REGULAR,2605630,376631,0,0,0,2016-03-26 01:00:00,1
194036,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/27/2016,01:00:00,REGULAR,2606029,376638,1,2,3,2016-03-27 01:00:00,1
194041,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/28/2016,01:00:00,REGULAR,2606387,376655,1,0,1,2016-03-28 01:00:00,1
194047,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/29/2016,01:00:00,REGULAR,2606631,376660,0,1,1,2016-03-29 01:00:00,1
194053,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/30/2016,01:00:00,REGULAR,2606869,376668,0,0,0,2016-03-30 01:00:00,1
194059,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/31/2016,01:00:00,REGULAR,2607155,376680,0,1,1,2016-03-31 01:00:00,1
194065,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,04/01/2016,01:00:00,REGULAR,2607450,376689,0,3,3,2016-04-01 01:00:00,1
194071,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/26/2016,01:00:00,REGULAR,2124,62,0,0,0,2016-03-26 01:00:00,1
194077,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/27/2016,01:00:00,REGULAR,2125,62,0,0,0,2016-03-27 01:00:00,1
194083,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/28/2016,01:00:00,REGULAR,2127,62,0,0,0,2016-03-28 01:00:00,1
194089,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/29/2016,01:00:00,REGULAR,2128,62,0,0,0,2016-03-29 01:00:00,1
194095,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/30/2016,01:00:00,REGULAR,2129,62,0,0,0,2016-03-30 01:00:00,1
194101,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/31/2016,01:00:00,REGULAR,2132,62,0,0,0,2016-03-31 01:00:00,1
194107,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,04/01/2016,01:00:00,REGULAR,2132,62,0,0,0,2016-04-01 01:00:00,1
194113,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/26/2016,01:00:00,REGULAR,5554,236,0,0,0,2016-03-26 01:00:00,1
194119,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/27/2016,01:00:00,REGULAR,5554,239,0,0,0,2016-03-27 01:00:00,1
194124,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/28/2016,01:00:00,REGULAR,5554,241,0,0,0,2016-03-28 01:00:00,1
194130,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/29/2016,01:00:00,REGULAR,5554,241,0,0,0,2016-03-29 01:00:00,1
194136,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/30/2016,01:00:00,REGULAR,5554,241,0,0,0,2016-03-30 01:00:00,1
194142,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/31/2016,01:00:00,REGULAR,5554,241,0,0,0,2016-03-31 01:00:00,1
194148,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/01/2016,01:00:00,REGULAR,5554,241,0,0,0,2016-04-01 01:00:00,1

In [164]:
data_grouped = data_0to4.groupby(['DATE','STATION']).sum()

In [165]:
data_grouped

                                 ENTRY        EXIT  dENTRY  dEXIT  dTOTAL  \
DATE       STATION
01/01/2016 103 ST            124275451    97068537    1382   2627    4009
           111 ST             56026967    20703956       7      7      14
           116 ST            434045322   443270013    2226   1544    3770
           116 ST-COLUMBIA  1209304180   255757907     427    397     824
           125 ST            149283761   108805385    2122   1930    4052
           135 ST            202828327    30307064     238    347     585
           137 ST CITY COL    51595602    40876251     574    970    1544
           14 ST             263727289    52602844    2026   1126    3152
           14 ST-UNION SQ   1295825246   498726380    8723   4876   13599
           14TH STREET         5328286     1390620    1587    197    1784
           155 ST             30732079    23505411     347    659    1006
           157 ST             31479360    21130033     598    886    1484
           163 ST-AMSTERDM    16699135    11278577     143    289     432
           170 ST           1284544003  2348550148     222    242     464
           174 ST             21571530    14401105     288    429     717
           18 AV              20547147    21078948      79    327     406
           181 ST             51373405    42726742     325   1043    1368
           20 AV              14549689    12590139      27    181     208
           21 ST               5581354     6316633     165    191     356
           219 ST              9570512     5885820     135    104     239
           225 ST             14065377     7765433     154    135     289
           23 ST            2188269767  1831047870    2541   2026    4567
           233 ST             95213634     4508303     150     88     238
           238 ST             18951764      873664     210     10     220
           25 AV               3647116     1233446      82    122     204
           28 ST            1511587521  2315673565    2605   1746    4351
           3 AV 138 ST        17463359    14917640     271    457     728
           33 ST             227628017   136211144    1830   1380    3210
           34 ST-PENN STA   1882266234  1219826448    3421   2279    5700
           36 ST             863856666  1233230333     475   1153    1628
...                                ...         ...     ...    ...     ...
12/31/2015 RIT-MANHATTAN       4246923       68972      63      1      64
           RIT-ROOSEVELT       7181901      443024      25      3      28
           ROCKAWAY AV       716550294    42260220     102    183     285
           ROCKAWAY BLVD     271252502    12923252     110    100     210
           ROCKAWAY PARK B   105075618    10824168      14     49      63
           SENECA AVE          5064757     5660500      31    134     165
           SHEEPSHEAD BAY     39503737    35687499     131    356     487
           SHEPHERD AV        16685992    14330380      52     88     140
           SIMPSON ST         36994903    10242128     125     45     170
           SOUTH FERRY        34934820    30590148     181    556     737
           SUTPHIN BLVD       17864532     9611088      32    127     159
           SUTPHIN-ARCHER       390518      370327     267    441     708
           SUTTER AV          11107537    14919689      76    247     323
           THIRTY ST            788721     3428432      66      9      75
           THIRTY THIRD ST     5012759     3532470     193    174     367
           TOMPKINSVILLE       8612291     2414987      10      0      10
           TREMONT AV        128816996    10654451     153    401     554
           TWENTY THIRD ST      566901     1196172      34     16      50
           UTICA AV          102383089    49731798     276    653     929
           VAN SICLEN AV      12159407    11914781      63    188     251
           VAN SICLEN AVE     13181214    13691285      50    160     210
           W 4 ST-WASH SQ    802331670   894987502    2703    812    3515
           WAKEFIELD/241      16001928    16554856     133    318     451
           WALL ST           532858827   277634205      77     80     157
           WEST FARMS SQ     438009515    72769492     165    305     470
           WHITEHALL S-FRY   131534549    11861096     133    243     376
           WINTHROP ST        31323378     5530444      77     49     126
           WOODHAVEN BLVD     54675899    36218673     205    419     624
           YORK ST            31243732    28674361      89    104     193
           ZEREGA AV          53468921      461325      27     97     124

                            HOUR
DATE       STATION
01/01/2016 103 ST              0
           111 ST              0
           116 ST              0
           116 ST-COLUMBIA     0
           125 ST              0
           135 ST              0
           137 ST CITY COL     0
           14 ST               0
           14 ST-UNION SQ      0
           14TH STREET         3
           155 ST              0
           157 ST              0
           163 ST-AMSTERDM     0
           170 ST              0
           174 ST              0
           18 AV               0
           181 ST              0
           20 AV               0
           21 ST               0
           219 ST              0
           225 ST              0
           23 ST               0
           233 ST              0
           238 ST              0
           25 AV               0
           28 ST               0
           3 AV 138 ST         0
           33 ST               0
           34 ST-PENN STA     21
           36 ST               0
...                          ...
12/31/2015 RIT-MANHATTAN       0
           RIT-ROOSEVELT       0
           ROCKAWAY AV         0
           ROCKAWAY BLVD       0
           ROCKAWAY PARK B     0
           SENECA AVE          0
           SHEEPSHEAD BAY      0
           SHEPHERD AV         0
           SIMPSON ST          0
           SOUTH FERRY         0
           SUTPHIN BLVD        0
           SUTPHIN-ARCHER      0
           SUTTER AV           0
           THIRTY ST           7
           THIRTY THIRD ST     5
           TOMPKINSVILLE       7
           TREMONT AV          0
           TWENTY THIRD ST     0
           UTICA AV            0
           VAN SICLEN AV       0
           VAN SICLEN AVE      0
           W 4 ST-WASH SQ      0
           WAKEFIELD/241       0
           WALL ST            28
           WEST FARMS SQ       0
           WHITEHALL S-FRY     0
           WINTHROP ST         0
           WOODHAVEN BLVD      0
           YORK ST             0
           ZEREGA AV           0

[21178 rows x 6 columns]

In [166]:
data_reset = (data_grouped
    .reset_index()
    .sort_values(['dTOTAL'], ascending=(False))
)
data_reset

,DATE,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR
8,01/01/2016,14 ST-UNION SQ,1295825246,498726380,8723,4876,13599,0
30,01/01/2016,42 ST-PORT AUTH,323071716,86045730,8131,2395,10526,19
190,01/01/2016,W 4 ST-WASH SQ,802362012,895020261,6303,3384,9687,0
17755,03/26/2016,TIMES SQ-42 ST,3825096876,3080925551,7205,1990,9195,0
18122,03/27/2016,TIMES SQ-42 ST,3825167957,3080996667,6887,1849,8736,0
15189,03/19/2016,TIMES SQ-42 ST,3824481753,3080347125,6359,2197,8556,0
15557,03/20/2016,TIMES SQ-42 ST,3824548288,3080419668,6097,1786,7883,0
8664,02/21/2016,14 ST-UNION SQ,1295528824,501172425,5517,2151,7668,0
14703,03/18/2016,GRD CNTRL-42 ST,5004151320,2098509366,2674,4923,7597,32
14965,03/19/2016,ATL AV-BARCLAY,325746008,255318311,6066,1159,7225,0
12816,03/13/2016,14 ST-UNION SQ,1414079194,499532993,5351,1849,7200,0
51,01/01/2016,96 ST,769817980,1415871614,2627,4528,7155,0
12618,03/12/2016,14 ST-UNION SQ,1414000549,499462588,5365,1742,7107,0
11432,03/06/2016,14 ST-UNION SQ,1413381828,498940432,4990,2087,7077,0
1791,01/10/2016,14 ST-UNION SQ,1296576062,499378628,5411,1657,7068,0
10049,02/28/2016,14 ST-UNION SQ,1296189109,501749192,5195,1825,7020,0
45,01/01/2016,8 AV,197136435,90764301,4927,2061,6988,0
8466,02/20/2016,14 ST-UNION SQ,1295451436,501103243,5239,1661,6900,0
4554,01/31/2016,14 ST-UNION SQ,1293618130,499503816,5019,1871,6890,0
4356,01/30/2016,14 ST-UNION SQ,1293542597,499435093,5051,1765,6816,0
1594,01/09/2016,14 ST-UNION SQ,1296505129,499311855,5444,1366,6810,0
5912,02/07/2016,14 ST-UNION SQ,1294280919,500076323,4818,1873,6691,0
91,01/01/2016,DELANCEY/ESSEX,1710769774,1110982848,4302,2299,6601,0
41,01/01/2016,7 AV,1907910719,838925819,4771,1808,6579,0
11234,03/05/2016,14 ST-UNION SQ,1413305482,498871179,4903,1647,6550,0
42,01/01/2016,72 ST,1607584159,983008486,4535,1967,6502,0
5714,02/06/2016,14 ST-UNION SQ,1294207716,500010299,4864,1587,6451,0
9852,02/27/2016,14 ST-UNION SQ,1296113534,501679945,4954,1487,6441,0
7087,02/13/2016,14 ST-UNION SQ,1294860103,500575041,4898,1500,6398,0
17387,03/25/2016,TIMES SQ-42 ST,3825001849,3080835150,4857,1377,6234,0
...,...,...,...,...,...,...,...,...
8860,02/22/2016,137 ST CITY COL,656790409,910912814,0,0,0,0
11654,03/07/2016,5 AV/53 ST,84549367,91036645,0,0,0,21
3205,01/24/2016,80 ST,130677099,6698477,0,0,0,0
8855,02/22/2016,111 ST,2116014,2292703,0,0,0,0
350,01/02/2016,NEWARK C,505591,32711,0,0,0,0
7231,02/13/2016,NEWARK C,611397,31715,0,0,0,3
13240,03/14/2016,HIGH ST,32077354,37091837,0,0,0,0
11456,03/06/2016,5 AV/53 ST,84549364,91036628,0,0,0,21
3222,01/24/2016,BAYCHESTER AV,13216221,1202901,0,0,0,0
15505,03/20/2016,NEWARK C,2684978,305871,0,0,0,3
10507,03/01/2016,BROADWAY,14890373,11079117,0,0,0,0
12170,03/09/2016,NEWARK HW BMEBE,504970,17373,0,0,0,0
10270,02/29/2016,5 AV/53 ST,84420315,90896571,0,0,0,21
12287,03/10/2016,BROADWAY,14927221,11107492,0,0,0,0
9876,02/27/2016,5 AV/53 ST,84420311,90896498,0,0,0,21
7658,02/15/2016,TOMPKINSVILLE,8639235,2414988,0,0,0,7
1735,01/09/2016,NEWARK C,509472,32809,0,0,0,0
5738,02/06/2016,5 AV/53 ST,84009907,90443509,0,0,0,21
3332,01/24/2016,SENECA AVE,5117437,5711507,0,0,0,0
17335,03/25/2016,NEWARK C,10887,878,0,0,0,0
18378,03/28/2016,HARLEM 148 ST,9084825,6448119,0,0,0,0
14034,03/16/2016,NEWARK C,1355576,187232,0,0,0,2
3335,01/24/2016,SIMPSON ST,37189842,10273815,0,0,0,0
447,01/03/2016,88 ST,8712304,8671724,0,0,0,0
3338,01/24/2016,SUTPHIN-ARCHER,525218,516631,0,0,0,0
8903,02/22/2016,88 ST,8851641,8718809,0,0,0,0
8900,02/22/2016,80 ST,130709517,6701987,0,0,0,0
10220,02/28/2016,SUTTER AV,10821564,14923620,0,0,0,0
6575,02/10/2016,CITY / BUS,998,6186,0,0,0,0
6062,02/07/2016,PATH WTC,145083,44177,0,0,0,1

In [167]:
data_reset.columns

Index([u'DATE', u'STATION', u'ENTRY', u'EXIT', u'dENTRY', u'dEXIT', u'dTOTAL',
       u'HOUR'],
      dtype='object')

In [168]:
data_reset['DATE'] = pd.to_datetime(data_reset.DATE, format='%m/%d/%Y')
data_reset['WEEKDAY']=data_reset.DATE.apply(lambda x: 'Weekday' if 0<=x.weekday()<5 else 'Weekend')

In [169]:
new_data_grouped = data_reset.groupby(['WEEKDAY','STATION']).sum()

In [170]:
new_data_grouped

                               ENTRY          EXIT  dENTRY  dEXIT  dTOTAL  \
WEEKDAY STATION
Weekday 1 AV             21134059178   21932208010    9721   5313   15034
        103 ST            9218635553   30466847914   16131  25107   41238
        103 ST-CORONA      936911609     897358198    3170  14214   17384
        104 ST           18747542983   10987928062     662   1004    1666
        110 ST             392135677     401063881    2570   5718    8288
        111 ST            3276355623    1503921823    2425   8290   10715
        116 ST           29561965193   30529961997   29567  30992   60559
        116 ST-COLUMBIA  78642778901   16643200360    9465   4500   13965
        121 ST             119661954      98985228     847    579    1426
        125 ST           18051447693   13410634075   50343  58623  108966
        135 ST           13641501445    2210675258    6530   8479   15009
        137 ST CITY COL   3992441577    3551045103    9874  26199   36073
        138/GRAND CONC   14944849173   14432420449    1077   1552    2629
        14 ST            21848883891    5538325320   47342  17821   65163
        14 ST-UNION SQ   87168398335   32491281666  139343  51257  190600
        145 ST           22141041002   31227688601    7245  21885   29130
        149/GRAND CONC    7934865378    3081287798    4341   5317    9658
        14TH STREET        196801046      77535475    5865   3541    9406
        15 ST-PROSPECT    1792014679     126638045     382    606     988
        155 ST            2012887076    1534396509    6880  13137   20017
        157 ST            2071620098    1387282981    9783  23030   32813
        161/YANKEE STAD   9318456438    3511722833    4731   5367   10098
        163 ST-AMSTERDM  30381821932   10700595747    3190   6606    9796
        167 ST           22178625477   10807102444    4202  10205   14407
        168 ST            2054389136     895501227    4722   5700   10422
        169 ST             370317972     394113426    1320   3865    5185
        170 ST           80757940822  148159141705    8046  15424   23470
        174 ST            1417934478     949715334    6693  14135   20828
        174-175 STS        224096292     150870465    1181    944    2125
        175 ST            2198880607     288262925    1360   4149    5509
...                              ...           ...     ...    ...     ...
Weekend SUTPHIN-ARCHER     604709798     307065750    3639   6095    9734
        SUTTER AV          283406076     388003712    2056   4875    6931
        SUTTER AV-RUTLD    112817309      65729858     476   1327    1803
        THIRTY ST           49810845      55857111    4379   1132    5511
        THIRTY THIRD ST    150176926      97943593    7296   2306    9602
        TIMES SQ-42 ST   15299294874   12322689011   26548   7822   34370
        TOMPKINSVILLE      189944205      53129738     251      0     251
        TREMONT AV        3358771351     283203114    3794  11527   15321
        TWENTY THIRD ST     28933404      10224952    1190    632    1822
        UNION ST            80563402      84943176    1002    831    1833
        UTICA AV          2651490454    1305216366    7264  16724   23988
        V.CORTLANDT PK      89954706      30914341     275    777    1052
        VAN SICLEN AV      390520175     348523833    1161   3598    4759
        VAN SICLEN AVE     345802477     358775238    1321   4842    6163
        VERNON-JACKSON     131235448      88484400     689   1034    1723
        W 4 ST-WASH SQ   20895976200   23300734723   85393  27217  112610
        W 8 ST-AQUARIUM     43702088      47895861      61    127     188
        WAKEFIELD/241      421024985     435502309    3052   7752   10804
        WALL ST          12172426121    6500704665    3026   2727    5753
        WEST FARMS SQ    11395708048    1897014379    3946   6803   10749
        WESTCHESTER SQ      93934413      87210666     354    989    1343
        WHITEHALL S-FRY   6107679325    1323749007    4491   8293   12784
        WHITLOCK AV        893446540      84276600     139    493     632
        WILSON AV           58871667      52787867     441   1504    1945
        WINTHROP ST        821192741     145337591    1821   1165    2986
        WOODHAVEN BLVD    1648009552    1010468923    4980   8645   13625
        WOODLAWN           110112551      45153163     802    580    1382
        WORLD TRADE CTR    141889443      75908015     705    853    1558
        YORK ST            821295539     751964167    3143   4217    7360
        ZEREGA AV         1392543192      14169667     583   2408    2991

                         HOUR
WEEKDAY STATION
Weekday 1 AV                0
        103 ST            207
        103 ST-CORONA       0
        104 ST              0
        110 ST              0
        111 ST             94
        116 ST            315
        116 ST-COLUMBIA    90
        121 ST              0
        125 ST            260
        135 ST            165
        137 ST CITY COL   135
        138/GRAND CONC      0
        14 ST             150
        14 ST-UNION SQ    570
        145 ST              0
        149/GRAND CONC      0
        14TH STREET       173
        15 ST-PROSPECT      0
        155 ST            119
        157 ST            118
        161/YANKEE STAD     0
        163 ST-AMSTERDM    78
        167 ST              0
        168 ST              0
        169 ST              0
        170 ST            150
        174 ST             75
        174-175 STS         0
        175 ST              0
...                       ...
Weekend SUTPHIN-ARCHER      0
        SUTTER AV           8
        SUTTER AV-RUTLD     0
        THIRTY ST          80
        THIRTY THIRD ST   106
        TIMES SQ-42 ST      0
        TOMPKINSVILLE     154
        TREMONT AV         36
        TWENTY THIRD ST    29
        UNION ST            0
        UTICA AV           52
        V.CORTLANDT PK      0
        VAN SICLEN AV      12
        VAN SICLEN AVE     12
        VERNON-JACKSON      0
        W 4 ST-WASH SQ     76
        W 8 ST-AQUARIUM     0
        WAKEFIELD/241      20
        WALL ST           616
        WEST FARMS SQ      36
        WESTCHESTER SQ      0
        WHITEHALL S-FRY    60
        WHITLOCK AV         0
        WILSON AV           0
        WINTHROP ST        16
        WOODHAVEN BLVD     44
        WOODLAWN            0
        WORLD TRADE CTR     0
        YORK ST            12
        ZEREGA AV          24

[746 rows x 6 columns]

In [182]:
new_data_reset = (new_data_grouped
    .reset_index()
    .sort_values(['dTOTAL'], ascending=(False))
)
new_data_reset

,WEEKDAY,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR
14,Weekday,14 ST-UNION SQ,87168398335,32491281666,139343,51257,190600,570
387,Weekend,14 ST-UNION SQ,34631837602,13003137167,114553,39337,153890,152
358,Weekday,W 4 ST-WASH SQ,51527184030,57431162342,97174,33343,130517,278
731,Weekend,W 4 ST-WASH SQ,20895976200,23300734723,85393,27217,112610,76
113,Weekday,96 ST,50538865727,92441471536,47260,62372,109632,435
9,Weekday,125 ST,18051447693,13410634075,50343,58623,108966,260
68,Weekday,42 ST-PORT AUTH,68037837777,42759193691,65606,35826,101432,944
229,Weekday,GRD CNTRL-42 ST,233775067966,78703954085,65606,33356,98962,480
103,Weekday,8 AV,12909263120,5968068395,63583,28136,91719,270
196,Weekday,DELANCEY/ESSEX,111241788642,72250461670,46920,40325,87245,285
61,Weekday,34 ST-PENN STA,132336799618,73761645029,47886,34195,82081,1050
476,Weekend,8 AV,5160833716,2385160627,52594,20885,73479,72
486,Weekend,96 ST,20166200679,36933540016,27780,45338,73118,116
441,Weekend,42 ST-PORT AUTH,20972069230,12220449249,53656,19355,73011,416
569,Weekend,DELANCEY/ESSEX,44493591774,28897880491,48259,22963,71222,76
13,Weekday,14 ST,21848883891,5538325320,47342,17821,65163,150
46,Weekday,23 ST,172953845194,147622173564,46525,18499,65024,465
348,Weekday,TIMES SQ-42 ST,57254168374,46209002968,49483,14430,63913,0
6,Weekday,116 ST,29561965193,30529961997,29567,30992,60559,315
109,Weekday,86 ST,26148906467,15254191219,30917,28704,59621,240
95,Weekday,7 AV,124106891620,54600528153,36020,22351,58371,345
307,Weekday,PARKCHESTER,1482830191,1668857278,15317,42490,57807,180
52,Weekday,28 ST,98590470105,137078563665,39232,17222,56454,420
382,Weekend,125 ST,5848379177,4466608407,26805,29469,56274,80
259,Weekday,KINGSBRIDGE RD,3509373702,2481130508,18764,37159,55923,255
169,Weekday,CANAL ST,208358116118,114412324755,37108,18741,55849,585
257,Weekday,KEW GARDENS,4407864327,3792490991,29487,22913,52400,999
97,Weekday,72 ST,105422991231,64522584350,32354,20005,52359,285
419,Weekend,23 ST,63169008395,53203983574,30782,13154,43936,124
88,Weekday,61 ST WOODSIDE,3779607129,3485741424,10774,33133,43907,180
...,...,...,...,...,...,...,...,...
629,Weekend,JUNIUS ST,51773676,33071068,249,316,565,0
437,Weekend,39 AV,21173050,20800317,215,345,560,0
409,Weekend,190 ST,74259694,41559811,165,385,550,0
607,Weekend,HARLEM 148 ST,36291157,25749405,98,452,550,0
645,Weekend,MARBLE HILL-225,30596781,4685639,326,220,546,0
381,Weekend,121 ST,31912500,26397591,272,219,491,0
512,Weekend,BEACH 36 ST,15935450,15703492,93,397,490,0
99,Weekday,75 AV,1654220375,18802775,300,168,468,0
610,Weekend,HIGH ST,128579501,148672132,151,314,465,0
523,Weekend,BEVERLY RD,92621943,37251129,296,146,442,0
359,Weekday,W 8 ST-AQUARIUM,163873656,179607412,146,276,422,0
510,Weekend,BEACH 105 ST,3082874084,41449684,64,354,418,20
349,Weekday,TOMPKINSVILLE,397187432,111089449,410,0,410,322
391,Weekend,15 ST-PROSPECT,477878832,33773005,179,219,398,0
677,Weekend,OCEAN PKWY,526359643,42992945,156,226,382,0
502,Weekend,AVENUE P,64432398,50673205,121,261,382,0
416,Weekend,215 ST,35881998,681456150,200,149,349,0
500,Weekend,AVENUE M,467249430,30702260,166,177,343,0
554,Weekend,CITY HALL,1072665612,197257372,237,102,339,0
513,Weekend,BEACH 44 ST,9906228,12826002,40,279,319,0
660,Weekend,NECK RD,443533687,4917824,142,167,309,0
531,Weekend,BROAD CHANNEL,45930552,15782730,172,131,303,12
472,Weekend,75 AV,441130077,5014103,176,86,262,0
722,Weekend,TOMPKINSVILLE,189944205,53129738,251,0,251,154
496,Weekend,ATLANTIC AV,6950920,2911133,134,92,226,0
567,Weekend,CYPRESS HILLS,22889844,13435089,67,153,220,0
455,Weekend,55 ST,42124939,32534028,85,127,212,0
504,Weekend,AVENUE X,47138232,43922361,118,91,209,0
732,Weekend,W 8 ST-AQUARIUM,43702088,47895861,61,127,188,0
668,Weekend,NEWARK C,22057940,1735340,4,4,8,37

In [183]:
# daysofweek = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

# whatdayofweek = lambda x: daysofweek[x.weekday()]


# data_reset['DAYOFWEEK'] = data_reset.DATETIME.apply(whatdayofweek)

In [184]:
for r in range(new_data_reset.shape[0]):
    if new_data_reset.ix[r,'WEEKDAY'] =='Weekday':
        new_data_reset.ix[r,'dTOTALACTUAL'] = new_data_reset.ix[r, 'dTOTAL']/(5*13)
    else:
        new_data_reset.ix[r,'dTOTALACTUAL'] = new_data_reset.ix[r, 'dTOTAL']/(2*13)

In [186]:
new_data_reset = (new_data_reset
    .sort_values(['dTOTALACTUAL'], ascending=(False))
)
new_data_reset

,WEEKDAY,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR,dTOTALACTUAL
387,Weekend,14 ST-UNION SQ,34631837602,13003137167,114553,39337,153890,152,5918.846154
731,Weekend,W 4 ST-WASH SQ,20895976200,23300734723,85393,27217,112610,76,4331.153846
14,Weekday,14 ST-UNION SQ,87168398335,32491281666,139343,51257,190600,570,2932.307692
476,Weekend,8 AV,5160833716,2385160627,52594,20885,73479,72,2826.115385
486,Weekend,96 ST,20166200679,36933540016,27780,45338,73118,116,2812.230769
441,Weekend,42 ST-PORT AUTH,20972069230,12220449249,53656,19355,73011,416,2808.115385
569,Weekend,DELANCEY/ESSEX,44493591774,28897880491,48259,22963,71222,76,2739.307692
382,Weekend,125 ST,5848379177,4466608407,26805,29469,56274,80,2164.384615
358,Weekday,W 4 ST-WASH SQ,51527184030,57431162342,97174,33343,130517,278,2007.953846
419,Weekend,23 ST,63169008395,53203983574,30782,13154,43936,124,1689.846154
113,Weekday,96 ST,50538865727,92441471536,47260,62372,109632,435,1686.646154
9,Weekday,125 ST,18051447693,13410634075,50343,58623,108966,260,1676.400000
602,Weekend,GRD CNTRL-42 ST,92679368157,30951044291,27360,15972,43332,128,1666.615385
386,Weekend,14 ST,8173429988,1933875198,29519,12779,42298,40,1626.846154
434,Weekend,34 ST-PENN STA,51437926223,30239392045,24231,17172,41403,459,1592.423077
68,Weekday,42 ST-PORT AUTH,68037837777,42759193691,65606,35826,101432,944,1560.492308
542,Weekend,CANAL ST,79388086031,43947755363,26523,13741,40264,156,1548.615385
229,Weekday,GRD CNTRL-42 ST,233775067966,78703954085,65606,33356,98962,480,1522.492308
425,Weekend,28 ST,39395063365,55156702844,27007,12575,39582,112,1522.384615
647,Weekend,METROPOLITAN AV,1423696476,630711581,25138,11970,37108,28,1427.230769
482,Weekend,86 ST,7850121805,5043261137,18208,18840,37048,64,1424.923077
103,Weekday,8 AV,12909263120,5968068395,63583,28136,91719,270,1411.061538
470,Weekend,72 ST,42055463250,25734436279,21020,15654,36674,76,1410.538462
492,Weekend,ASTOR PL,760157798,612088805,27660,7860,35520,48,1366.153846
379,Weekend,116 ST,12585180964,13181886421,16527,18982,35509,84,1365.730769
196,Weekday,DELANCEY/ESSEX,111241788642,72250461670,46920,40325,87245,285,1342.230769
721,Weekend,TIMES SQ-42 ST,15299294874,12322689011,26548,7822,34370,0,1321.923077
468,Weekend,7 AV,49640177157,21838235802,19459,13529,32988,92,1268.769231
61,Weekday,34 ST-PENN STA,132336799618,73761645029,47886,34195,82081,1050,1262.784615
505,Weekend,B'WAY-LAFAYETTE,2820550804,2317259039,19582,9246,28828,80,1108.769231
...,...,...,...,...,...,...,...,...,...
502,Weekend,AVENUE P,64432398,50673205,121,261,382,0,14.692308
677,Weekend,OCEAN PKWY,526359643,42992945,156,226,382,0,14.692308
158,Weekday,BROAD CHANNEL,114876176,39473366,680,263,943,45,14.507692
129,Weekday,AVENUE P,241609825,190020396,378,555,933,0,14.353846
295,Weekday,NEWARK C,92128792,11339152,712,176,888,328,13.661538
416,Weekend,215 ST,35881998,681456150,200,149,349,0,13.423077
181,Weekday,CITY HALL,4022461748,739697864,640,232,872,0,13.415385
500,Weekend,AVENUE M,467249430,30702260,166,177,343,0,13.192308
127,Weekday,AVENUE M,1752160236,115124457,473,381,854,0,13.138462
287,Weekday,NECK RD,1663233900,18436937,427,424,851,0,13.092308
554,Weekend,CITY HALL,1072665612,197257372,237,102,339,0,13.038462
140,Weekday,BEACH 44 ST,37145684,48095035,182,660,842,0,12.953846
82,Weekday,55 ST,157962559,122000074,359,459,818,0,12.584615
513,Weekend,BEACH 44 ST,9906228,12826002,40,279,319,0,12.269231
660,Weekend,NECK RD,443533687,4917824,142,167,309,0,11.884615
531,Weekend,BROAD CHANNEL,45930552,15782730,172,131,303,12,11.653846
194,Weekday,CYPRESS HILLS,85831180,50378195,228,486,714,0,10.984615
131,Weekday,AVENUE X,176756549,164707305,449,249,698,0,10.738462
472,Weekend,75 AV,441130077,5014103,176,86,262,0,10.076923
722,Weekend,TOMPKINSVILLE,189944205,53129738,251,0,251,154,9.653846
123,Weekday,ATLANTIC AV,26058652,10914859,355,243,598,0,9.200000
496,Weekend,ATLANTIC AV,6950920,2911133,134,92,226,0,8.692308
567,Weekend,CYPRESS HILLS,22889844,13435089,67,153,220,0,8.461538
455,Weekend,55 ST,42124939,32534028,85,127,212,0,8.153846
504,Weekend,AVENUE X,47138232,43922361,118,91,209,0,8.038462
732,Weekend,W 8 ST-AQUARIUM,43702088,47895861,61,127,188,0,7.230769
99,Weekday,75 AV,1654220375,18802775,300,168,468,0,7.200000
359,Weekday,W 8 ST-AQUARIUM,163873656,179607412,146,276,422,0,6.492308
349,Weekday,TOMPKINSVILLE,397187432,111089449,410,0,410,322,6.307692
668,Weekend,NEWARK C,22057940,1735340,4,4,8,37,0.307692

In [175]:
#testweekend = data_reset[(data_reset.WEEKDAY == 'Weekday')]

In [176]:
#testweekend

In [177]:
# import numpy as np
# import matplotlib.pyplot as plt
# %matplotlib inline

In [178]:
#data_reset[data_reset.STATION=='WORLD TRADE CTR'].dTOTAL.plot(kind='bar');
# data_reset[data_reset.STATION=='WORLD TRADE CTR'].hist(by = data_reset.DATE, bins = 25, figsize = (100,50));