In [187]:
import pandas as pd
import matplotlib.pyplot as plt

In [188]:

list_data =[]
list_weeks = ['160102', '160109', '160116','160130','160206','160213',
              '160220','160227','160305','160312','160319','160326','160402']
for u in list_weeks:
    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'
    print(url)
    list_data.append(pd.read_csv(url))

data = pd.concat(list_data)
del list_data

http://web.mta.info/developers/data/nyct/turnstile/turnstile_160102.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160109.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160116.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160130.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160206.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160213.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160220.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160227.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160305.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160312.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160319.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160326.txt
http://web.mta.info/developers/data/nyct/turnstile/turnstile_160402.txt

In [189]:
#data = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_160402.txt")

In [190]:
data.columns = [column.strip() for column in data.columns]
data.columns

Index([u'C/A', u'UNIT', u'SCP', u'STATION', u'LINENAME', u'DIVISION', u'DATE',
       u'TIME', u'DESC', u'ENTRIES', u'EXITS'],
      dtype='object')

In [191]:
data.rename(columns={"EXITS": "EXIT", "ENTRIES": "ENTRY"}, inplace=True)

In [192]:
data['dENTRY'] = 0
data['dEXIT'] = 0

In [193]:
data['dENTRY'] = data.ENTRY.shift(-1) - data.ENTRY
data['dEXIT'] = data.EXIT.shift(-1) - data.EXIT
data['dTOTAL'] = data.dENTRY + data.dEXIT

In [194]:
#diff = data['ENTRY'].iloc[1:].values - data['ENTRY'].iloc[:-1].values
#data['DENTRY'][1:] = diff
#diff = data['EXIT'].iloc[:-1].values - data['EXIT'].iloc[1:].values
#data['DEXIT'][1:] = diff

In [195]:
data['DATETIME'] = pd.to_datetime(data.DATE + data.TIME, format='%m/%d/%Y%H:%M:%S')
data['HOUR'] = data['DATETIME'].apply(lambda x: x.hour)

In [196]:
#data['WEEKDAY']=data.DATETIME.apply(lambda x: 'Weekday' if 0<=x.weekday()<5 else 'Weekend')

In [197]:
# daysofweek = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

# whatdayofweek = lambda x: daysofweek[x.weekday()]


# data['DAYOFWEEK'] = data.DATETIME.apply(whatdayofweek)

In [198]:
data_cleaned = data[(data['dENTRY'] >= 0) & (data['dENTRY'] <= 10000) & (data['dEXIT'] >= 0) & (data['dEXIT'] <= 10000)]

In [199]:
data_0to4 = data_cleaned[(data_cleaned.HOUR ==22)|(data_cleaned.HOUR ==23)|(data_cleaned.HOUR ==0)|(data_cleaned.HOUR==1)]

In [200]:
data_0to4

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,DATETIME,HOUR
5,A002,R051,02-00-00,59 ST,NQR456,BMT,12/26/2015,23:00:00,REGULAR,5470411,1846906,48,19,67,2015-12-26 23:00:00,23
11,A002,R051,02-00-00,59 ST,NQR456,BMT,12/27/2015,23:00:00,REGULAR,5471087,1847060,28,4,32,2015-12-27 23:00:00,23
17,A002,R051,02-00-00,59 ST,NQR456,BMT,12/28/2015,23:00:00,REGULAR,5472688,1847517,38,8,46,2015-12-28 23:00:00,23
23,A002,R051,02-00-00,59 ST,NQR456,BMT,12/29/2015,23:00:00,REGULAR,5474280,1847999,62,5,67,2015-12-29 23:00:00,23
29,A002,R051,02-00-00,59 ST,NQR456,BMT,12/30/2015,23:00:00,REGULAR,5476038,1848523,47,12,59,2015-12-30 23:00:00,23
35,A002,R051,02-00-00,59 ST,NQR456,BMT,12/31/2015,23:00:00,REGULAR,5477402,1848918,85,18,103,2015-12-31 23:00:00,23
47,A002,R051,02-00-01,59 ST,NQR456,BMT,12/26/2015,23:00:00,REGULAR,5037029,1100031,39,8,47,2015-12-26 23:00:00,23
53,A002,R051,02-00-01,59 ST,NQR456,BMT,12/27/2015,23:00:00,REGULAR,5037666,1100179,24,1,25,2015-12-27 23:00:00,23
59,A002,R051,02-00-01,59 ST,NQR456,BMT,12/28/2015,23:00:00,REGULAR,5039121,1100449,30,6,36,2015-12-28 23:00:00,23
65,A002,R051,02-00-01,59 ST,NQR456,BMT,12/29/2015,23:00:00,REGULAR,5040597,1100756,51,10,61,2015-12-29 23:00:00,23
71,A002,R051,02-00-01,59 ST,NQR456,BMT,12/30/2015,23:00:00,REGULAR,5042118,1101112,47,12,59,2015-12-30 23:00:00,23
77,A002,R051,02-00-01,59 ST,NQR456,BMT,12/31/2015,23:00:00,REGULAR,5043252,1101371,72,12,84,2015-12-31 23:00:00,23
89,A002,R051,02-03-00,59 ST,NQR456,BMT,12/26/2015,23:00:00,REGULAR,621346,2343230,36,49,85,2015-12-26 23:00:00,23
95,A002,R051,02-03-00,59 ST,NQR456,BMT,12/27/2015,23:00:00,REGULAR,621642,2344408,19,27,46,2015-12-27 23:00:00,23
101,A002,R051,02-03-00,59 ST,NQR456,BMT,12/28/2015,23:00:00,REGULAR,622285,2346652,12,41,53,2015-12-28 23:00:00,23
107,A002,R051,02-03-00,59 ST,NQR456,BMT,12/29/2015,23:00:00,REGULAR,622887,2348823,25,30,55,2015-12-29 23:00:00,23
113,A002,R051,02-03-00,59 ST,NQR456,BMT,12/30/2015,23:00:00,REGULAR,623611,2351239,12,42,54,2015-12-30 23:00:00,23
119,A002,R051,02-03-00,59 ST,NQR456,BMT,12/31/2015,23:00:00,REGULAR,624115,2352979,30,101,131,2015-12-31 23:00:00,23
131,A002,R051,02-03-01,59 ST,NQR456,BMT,12/26/2015,23:00:00,REGULAR,5000358,7894709,95,61,156,2015-12-26 23:00:00,23
137,A002,R051,02-03-01,59 ST,NQR456,BMT,12/27/2015,23:00:00,REGULAR,5001247,7895958,40,47,87,2015-12-27 23:00:00,23
143,A002,R051,02-03-01,59 ST,NQR456,BMT,12/28/2015,23:00:00,REGULAR,5002628,7898238,72,48,120,2015-12-28 23:00:00,23
149,A002,R051,02-03-01,59 ST,NQR456,BMT,12/29/2015,23:00:00,REGULAR,5003983,7900534,68,57,125,2015-12-29 23:00:00,23
155,A002,R051,02-03-01,59 ST,NQR456,BMT,12/30/2015,23:00:00,REGULAR,5005476,7902957,95,75,170,2015-12-30 23:00:00,23
161,A002,R051,02-03-01,59 ST,NQR456,BMT,12/31/2015,23:00:00,REGULAR,5006752,7904885,80,160,240,2015-12-31 23:00:00,23
173,A002,R051,02-03-02,59 ST,NQR456,BMT,12/26/2015,23:00:00,REGULAR,4728365,6521210,61,38,99,2015-12-26 23:00:00,23
179,A002,R051,02-03-02,59 ST,NQR456,BMT,12/27/2015,23:00:00,REGULAR,4729123,6522141,46,40,86,2015-12-27 23:00:00,23
185,A002,R051,02-03-02,59 ST,NQR456,BMT,12/28/2015,23:00:00,REGULAR,4730569,6523924,51,39,90,2015-12-28 23:00:00,23
191,A002,R051,02-03-02,59 ST,NQR456,BMT,12/29/2015,23:00:00,REGULAR,4731929,6525826,72,39,111,2015-12-29 23:00:00,23
197,A002,R051,02-03-02,59 ST,NQR456,BMT,12/30/2015,23:00:00,REGULAR,4733442,6527861,74,53,127,2015-12-30 23:00:00,23
203,A002,R051,02-03-02,59 ST,NQR456,BMT,12/31/2015,23:00:00,REGULAR,4734625,6529335,99,115,214,2015-12-31 23:00:00,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193977,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,03/31/2016,01:00:00,REGULAR,1554761,16118,1,0,1,2016-03-31 01:00:00,1
193983,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,04/01/2016,01:00:00,REGULAR,1556710,16129,3,0,3,2016-04-01 01:00:00,1
193989,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/26/2016,01:00:00,REGULAR,291256,11918,1,2,3,2016-03-26 01:00:00,1
193995,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/27/2016,01:00:00,REGULAR,291589,11930,4,0,4,2016-03-27 01:00:00,1
194000,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/28/2016,01:00:00,REGULAR,291911,11949,1,0,1,2016-03-28 01:00:00,1
194006,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/29/2016,01:00:00,REGULAR,292125,11958,0,5,5,2016-03-29 01:00:00,1
194012,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/30/2016,01:00:00,REGULAR,292366,11973,0,0,0,2016-03-30 01:00:00,1
194018,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,03/31/2016,01:00:00,REGULAR,292663,11986,0,0,0,2016-03-31 01:00:00,1
194024,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,04/01/2016,01:00:00,REGULAR,292921,11992,0,0,0,2016-04-01 01:00:00,1
194030,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/26/2016,01:00:00,REGULAR,2605630,376631,0,0,0,2016-03-26 01:00:00,1
194036,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/27/2016,01:00:00,REGULAR,2606029,376638,1,2,3,2016-03-27 01:00:00,1
194041,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/28/2016,01:00:00,REGULAR,2606387,376655,1,0,1,2016-03-28 01:00:00,1
194047,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/29/2016,01:00:00,REGULAR,2606631,376660,0,1,1,2016-03-29 01:00:00,1
194053,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/30/2016,01:00:00,REGULAR,2606869,376668,0,0,0,2016-03-30 01:00:00,1
194059,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,03/31/2016,01:00:00,REGULAR,2607155,376680,0,1,1,2016-03-31 01:00:00,1
194065,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,04/01/2016,01:00:00,REGULAR,2607450,376689,0,3,3,2016-04-01 01:00:00,1
194071,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/26/2016,01:00:00,REGULAR,2124,62,0,0,0,2016-03-26 01:00:00,1
194077,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/27/2016,01:00:00,REGULAR,2125,62,0,0,0,2016-03-27 01:00:00,1
194083,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/28/2016,01:00:00,REGULAR,2127,62,0,0,0,2016-03-28 01:00:00,1
194089,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/29/2016,01:00:00,REGULAR,2128,62,0,0,0,2016-03-29 01:00:00,1
194095,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/30/2016,01:00:00,REGULAR,2129,62,0,0,0,2016-03-30 01:00:00,1
194101,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,03/31/2016,01:00:00,REGULAR,2132,62,0,0,0,2016-03-31 01:00:00,1
194107,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,04/01/2016,01:00:00,REGULAR,2132,62,0,0,0,2016-04-01 01:00:00,1
194113,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/26/2016,01:00:00,REGULAR,5554,236,0,0,0,2016-03-26 01:00:00,1
194119,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/27/2016,01:00:00,REGULAR,5554,239,0,0,0,2016-03-27 01:00:00,1
194124,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/28/2016,01:00:00,REGULAR,5554,241,0,0,0,2016-03-28 01:00:00,1
194130,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/29/2016,01:00:00,REGULAR,5554,241,0,0,0,2016-03-29 01:00:00,1
194136,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/30/2016,01:00:00,REGULAR,5554,241,0,0,0,2016-03-30 01:00:00,1
194142,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/31/2016,01:00:00,REGULAR,5554,241,0,0,0,2016-03-31 01:00:00,1
194148,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/01/2016,01:00:00,REGULAR,5554,241,0,0,0,2016-04-01 01:00:00,1

In [201]:
data_grouped = data_0to4.groupby(['DATE','STATION']).sum()

In [202]:
data_grouped

                                 ENTRY        EXIT  dENTRY  dEXIT  dTOTAL  \
DATE       STATION
01/01/2016 103 ST            124275451    97068537    1382   2627    4009
           111 ST             56026967    20703956       7      7      14
           116 ST            434045322   443270013    2226   1544    3770
           116 ST-COLUMBIA  1209304180   255757907     427    397     824
           125 ST            149283761   108805385    2122   1930    4052
           135 ST            202828327    30307064     238    347     585
           137 ST CITY COL    51595602    40876251     574    970    1544
           14 ST             263727289    52602844    2026   1126    3152
           14 ST-UNION SQ   1295825246   498726380    8723   4876   13599
           14TH STREET         5328286     1390620    1587    197    1784
           155 ST             30732079    23505411     347    659    1006
           157 ST             31479360    21130033     598    886    1484
           163 ST-AMSTERDM    16699135    11278577     143    289     432
           170 ST           1284544003  2348550148     222    242     464
           174 ST             21571530    14401105     288    429     717
           18 AV              20547147    21078948      79    327     406
           181 ST             51373405    42726742     325   1043    1368
           20 AV              14549689    12590139      27    181     208
           21 ST               5581354     6316633     165    191     356
           219 ST              9570512     5885820     135    104     239
           225 ST             14065377     7765433     154    135     289
           23 ST            2188269767  1831047870    2541   2026    4567
           233 ST             95213634     4508303     150     88     238
           238 ST             18951764      873664     210     10     220
           25 AV               3647116     1233446      82    122     204
           28 ST            1511587521  2315673565    2605   1746    4351
           3 AV 138 ST        17463359    14917640     271    457     728
           33 ST             227628017   136211144    1830   1380    3210
           34 ST-HUDSON YD       51425       27797    6852  11226   18078
           34 ST-PENN STA   1882266234  1219826448    3421   2279    5700
...                                ...         ...     ...    ...     ...
12/31/2015 SUTPHIN-ARCHER    149026372    74978218    1295   2021    3316
           SUTTER AV          11107537    14919689      76    247     323
           SUTTER AV-RUTLD    27640471    16104283     305    470     775
           THIRTY ST           1568494     6104691     572    310     882
           THIRTY THIRD ST    12538977     8230609    3378   1196    4574
           TIMES SQ-42 ST   3818234281  3074661495    6915   7595   14510
           TOMPKINSVILLE       8612291     2414987      10      0      10
           TREMONT AV        128816996    10654451     153    401     554
           TWENTY THIRD ST      987171     1335283     105    116     221
           UNION ST           19672545    20854004    1091    635    1726
           UTICA AV          102383089    49731798     276    653     929
           V.CORTLANDT PK     21988126     7518196     173    405     578
           VAN SICLEN AV      12159407    11914781      63    188     251
           VAN SICLEN AVE     13181214    13691285      50    160     210
           VERNON-JACKSON     31744597    21338371    1233   1115    2348
           W 4 ST-WASH SQ    802331670   894987502    2703    812    3515
           W 8 ST-AQUARIUM    10785218    11879650     169    159     328
           WAKEFIELD/241      16001928    16554856     133    318     451
           WALL ST           652728067   384938399     915   1223    2138
           WEST FARMS SQ     438009515    72769492     165    305     470
           WESTCHESTER SQ     23036523    21388526     235    354     589
           WHITEHALL S-FRY   131534549    11861096     133    243     376
           WHITLOCK AV       223241094    20948063      79    123     202
           WILSON AV          14392623    12899853     586    731    1317
           WINTHROP ST        31323378     5530444      77     49     126
           WOODHAVEN BLVD    105658651    50155830     369    529     898
           WOODLAWN           27005982    11160921     286    187     473
           WORLD TRADE CTR    38708128    20343151     477    839    1316
           YORK ST            31243732    28674361      89    104     193
           ZEREGA AV          53468921      461325      27     97     124

                            HOUR
DATE       STATION
01/01/2016 103 ST              0
           111 ST              0
           116 ST              0
           116 ST-COLUMBIA     0
           125 ST              0
           135 ST              0
           137 ST CITY COL     0
           14 ST               0
           14 ST-UNION SQ      0
           14TH STREET         3
           155 ST              0
           157 ST              0
           163 ST-AMSTERDM     0
           170 ST              0
           174 ST              0
           18 AV               0
           181 ST              0
           20 AV               0
           21 ST               0
           219 ST              0
           225 ST              0
           23 ST               0
           233 ST              0
           238 ST              0
           25 AV               0
           28 ST               0
           3 AV 138 ST         0
           33 ST               0
           34 ST-HUDSON YD    69
           34 ST-PENN STA     21
...                          ...
12/31/2015 SUTPHIN-ARCHER    299
           SUTTER AV           0
           SUTTER AV-RUTLD    69
           THIRTY ST         184
           THIRTY THIRD ST   206
           TIMES SQ-42 ST   1127
           TOMPKINSVILLE       7
           TREMONT AV          0
           TWENTY THIRD ST    45
           UNION ST          138
           UTICA AV            0
           V.CORTLANDT PK     92
           VAN SICLEN AV       0
           VAN SICLEN AVE      0
           VERNON-JACKSON    299
           W 4 ST-WASH SQ      0
           W 8 ST-AQUARIUM   184
           WAKEFIELD/241       0
           WALL ST           534
           WEST FARMS SQ       0
           WESTCHESTER SQ     69
           WHITEHALL S-FRY     0
           WHITLOCK AV       138
           WILSON AV          69
           WINTHROP ST         0
           WOODHAVEN BLVD    184
           WOODLAWN          115
           WORLD TRADE CTR   253
           YORK ST             0
           ZEREGA AV           0

[31930 rows x 6 columns]

In [203]:
data_reset = (data_grouped
    .reset_index()
    .sort_values(['dTOTAL'], ascending=(False))
)
data_reset

,DATE,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR
17034,02/26/2016,34 ST-HUDSON YD,78002,48916,9255,11581,20836,69
9732,02/05/2016,34 ST-HUDSON YD,67369,34100,7909,12371,20280,69
12167,02/12/2016,34 ST-HUDSON YD,70821,36652,8518,11705,20223,69
4883,01/15/2016,34 ST-HUDSON YD,57563,30319,7211,11687,18898,69
31620,12/31/2015,34 ST-PENN STA,4221382551,2089059521,9759,8544,18303,1838
2458,01/08/2016,34 ST-HUDSON YD,54422,29081,6968,11221,18189,69
28,01/01/2016,34 ST-HUDSON YD,51425,27797,6852,11226,18078,69
31618,12/31/2015,34 ST-HERALD SQ,553364219,292713350,10289,7060,17349,1219
14692,02/19/2016,HOYT ST,98707,91380,9643,7701,17344,23
14706,02/19/2016,LACKAWANNA,1912746,2872181,9489,7809,17298,32
12260,02/12/2016,HOYT ST,96648,89594,9664,7054,16718,23
17128,02/26/2016,HOYT ST,100763,93628,9184,7423,16607,23
19559,03/04/2016,HOYT ST,103082,95933,8756,7585,16341,23
21996,03/11/2016,HOYT ST,105464,98221,8260,7873,16133,23
31645,12/31/2015,59 ST COLUMBUS,3855446143,3476934206,11438,3824,15262,897
14598,02/19/2016,34 ST-HUDSON YD,74570,44822,8554,6633,15187,69
31905,12/31/2015,TIMES SQ-42 ST,3818234281,3074661495,6915,7595,14510,1127
30048,12/26/2015,TIMES SQ-42 ST,3817818557,3074256465,11059,3243,14302,1127
22424,03/12/2016,TIMES SQ-42 ST,3823924584,3079849684,10307,3949,14256,1127
27166,03/26/2016,42 ST-PORT AUTH,3789606232,2611098106,10016,3699,13715,418
8,01/01/2016,14 ST-UNION SQ,1295825246,498726380,8723,4876,13599,0
31637,12/31/2015,50 ST,143129243,127732043,9951,3218,13169,828
31534,12/30/2015,TIMES SQ-42 ST,3818188037,3074592142,10232,2746,12978,1127
548,01/02/2016,TIMES SQ-42 ST,3818361159,3074790813,9792,2931,12723,1127
19987,03/05/2016,TIMES SQ-42 ST,3823311778,3079280935,9119,3194,12313,1127
4860,01/15/2016,135 ST,202886923,30353918,9319,2955,12274,23
15117,02/20/2016,TIMES SQ-42 ST,3822166218,3078232740,8908,3280,12188,1127
24573,03/19/2016,42 ST-PORT AUTH,3789031238,2610656572,8883,3295,12178,418
17553,02/27/2016,TIMES SQ-42 ST,3822735991,3078749655,8796,3014,11810,1127
2978,01/09/2016,TIMES SQ-42 ST,3818927651,3075297423,8914,2708,11622,1127
...,...,...,...,...,...,...,...,...
7977,01/31/2016,AVENUE M,116557169,7581484,0,0,0,230
867,01/03/2016,NEWARK C,2831253,187713,0,0,0,46
4609,01/14/2016,ATLANTIC AV,1680018,704173,0,0,0,69
7604,01/30/2016,AVENUE J,27518786,17427230,0,0,0,299
24800,03/19/2016,NEWARK C,390371,22006,0,0,0,23
5921,01/25/2016,ATLANTIC AV,1680018,704173,0,0,0,69
20460,03/07/2016,5 AV/53 ST,84549367,91036645,0,0,0,21
18025,02/29/2016,5 AV/53 ST,84420315,90896571,0,0,0,21
27021,03/25/2016,NEWARK C,10887,878,0,0,0,0
17814,02/28/2016,HIGH ST,31992961,36998828,0,0,0,138
15496,02/21/2016,V.CORTLANDT PK,22285463,7645469,0,0,0,92
15123,02/20/2016,V.CORTLANDT PK,22285463,7645469,0,0,0,92
3795,01/12/2016,238 ST,18987059,874599,0,0,0,0
10403,02/07/2016,AVENUE J,27550407,17442269,0,0,0,299
30366,12/27/2015,NEWARK C,2820116,187463,0,0,0,46
7031,01/28/2016,ATLANTIC AV,1680018,704173,0,0,0,69
19934,03/05/2016,NEWARK C,2264005,283068,0,0,0,322
17846,02/28/2016,LIVONIA AV,11514039,9083047,0,0,0,0
20087,03/06/2016,5 AV/53 ST,84549364,91036628,0,0,0,21
22883,03/14/2016,HIGH ST,32077354,37091837,0,0,0,0
17872,02/28/2016,NEWARK C,375274,21736,0,0,0,23
10352,02/07/2016,5 AV/53 ST,84009907,90443511,0,0,0,21
4411,01/13/2016,NEWARK C,1223937,79149,0,0,0,0
15526,02/22/2016,137 ST CITY COL,656790409,910912814,0,0,0,0
17873,02/28/2016,NEWARK HM HE,31693,541532,0,0,0,0
8145,01/31/2016,NEWKIRK PLAZA,48047798,45696094,0,0,0,0
429,01/02/2016,GRANT AV,30234235,24947852,0,0,0,92
17921,02/28/2016,SUTTER AV,10821564,14923620,0,0,0,0
12864,02/14/2016,BOWERY,12323868,12854813,0,0,0,69
10426,02/07/2016,BEVERLEY ROAD,12979187,13804814,0,0,0,69

In [204]:
data_reset.columns

Index([u'DATE', u'STATION', u'ENTRY', u'EXIT', u'dENTRY', u'dEXIT', u'dTOTAL',
       u'HOUR'],
      dtype='object')

In [205]:
data_reset['DATE'] = pd.to_datetime(data_reset.DATE, format='%m/%d/%Y')
data_reset['WEEKDAY']=data_reset.DATE.apply(lambda x: 'Weekday' if 0<=x.weekday()<5 else 'Weekend')

In [206]:
new_data_grouped = data_reset.groupby(['WEEKDAY','STATION']).sum()

In [207]:
new_data_grouped

                               ENTRY          EXIT  dENTRY   dEXIT  dTOTAL  \
WEEKDAY STATION
Weekday 1 AV             77467342880   80629523354   65726   42736  108462
        103 ST            9218635553   30466847914   16131   25107   41238
        103 ST-CORONA     3403244123    3265936011   12903   77338   90241
        104 ST           56403408146   33111626337    2394    5397    7791
        110 ST            1414330493    1451739758   12941   30114   43055
        111 ST            5479918505    3020269809    8698   46994   55692
        116 ST           29561965193   30529961997   29567   30992   60559
        116 ST-COLUMBIA  78642778901   16643200360    9465    4500   13965
        121 ST             434597222     360755417    3424    3249    6673
        125 ST           37768180411   29981799537   95002  120527  215529
        135 ST           14974897082    2763557469   32390   23037   55427
        137 ST CITY COL   3992441577    3551045103    9874   26199   36073
        138/GRAND CONC   54792215056   52914148821    4391    7047   11438
        14 ST            34903248265   11186839949  120341   45378  165719
        14 ST-UNION SQ   87168398335   32491281666  139343   51257  190600
        145 ST           80675365906  114021124232   37616  114677  152293
        149/GRAND CONC   28940346713   11276803722   21100   22554   43654
        14TH STREET        322053284     137935742   15032    7938   22970
        15 ST-PROSPECT    6560189935     460443061    2368    3748    6116
        155 ST            2012887076    1534396509    6880   13137   20017
        157 ST            2071620098    1387282981    9783   23030   32813
        161/YANKEE STAD  34125038322   12852165668   19155   28815   47970
        163 ST-AMSTERDM  30381821932   10700595747    3190    6606    9796
        167 ST           24621214889   12336027800   19074   51709   70783
        168 ST            7489990359    3252036515   28254   33381   61635
        169 ST            1346433014    1436464600    4879   20276   25155
        170 ST           81452703342  148658675499   15145   35393   50538
        174 ST            1417934478     949715334    6693   14135   20828
        174-175 STS        812521030     550087851    5314    5874   11188
        175 ST            8253507197    1060250533   10978   20382   31360
...                              ...           ...     ...     ...     ...
Weekend SUTPHIN-ARCHER    3740669992    1885502801   19365   23754   43119
        SUTTER AV          283406076     388003712    2056    4875    6931
        SUTTER AV-RUTLD    697949103     406639836    3494    7909   11403
        THIRTY ST          109310927     127061214   10817    2800   13617
        THIRTY THIRD ST    322335112     200833947   21069    7620   28689
        TIMES SQ-42 ST   95536700502   76939988037  158417   51733  210150
        TOMPKINSVILLE      233262027      65204709     445       0     445
        TREMONT AV        3358771351     283203114    3794   11527   15321
        TWENTY THIRD ST     84103111      26295400    5291    2187    7478
        UNION ST           497625704     525913770    6527    5437   11964
        UTICA AV          2651490454    1305216366    7264   16724   23988
        V.CORTLANDT PK     555813790     190558620    2334    4845    7179
        VAN SICLEN AV      408398230     357498006    1161    3598    4759
        VAN SICLEN AVE     345802477     358775238    1321    4842    6163
        VERNON-JACKSON     806759424     543191426    9708   10360   20068
        W 4 ST-WASH SQ   20895976200   23300734723   85393   27217  112610
        W 8 ST-AQUARIUM    271347886     298141087     348     650     998
        WAKEFIELD/241      421024985     435502309    3052    7752   10804
        WALL ST          17237117668   10014752856   10039   11242   21281
        WEST FARMS SQ    11395708048    1897014379    3946    6803   10749
        WESTCHESTER SQ     581419092     539838675    2584    6662    9246
        WHITEHALL S-FRY   6107679325    1323749007    4491    8293   12784
        WHITLOCK AV       5582511172     525197117    1058    3123    4181
        WILSON AV          363855944     326192443    2799    9012   11811
        WINTHROP ST        821192741     145337591    1821    1165    2986
        WOODHAVEN BLVD    2721496254    1304435619    7260   10687   17947
        WOODLAWN           681552272     280598684    5430    3092    8522
        WORLD TRADE CTR    947563766     499633614    5032    4556    9588
        YORK ST            821295539     751964167    3143    4217    7360
        ZEREGA AV         1392543192      14169667     583    2408    2991

                          HOUR
WEEKDAY STATION
Weekday 1 AV              8924
        103 ST             207
        103 ST-CORONA     8280
        104 ST            6026
        110 ST            5520
        111 ST            8374
        116 ST             315
        116 ST-COLUMBIA     90
        121 ST            4600
        125 ST           19580
        135 ST           10124
        137 ST CITY COL    135
        138/GRAND CONC    2760
        14 ST            29590
        14 ST-UNION SQ     570
        145 ST           16583
        149/GRAND CONC    6210
        14TH STREET       6067
        15 ST-PROSPECT    9200
        155 ST             119
        157 ST             118
        161/YANKEE STAD  33097
        163 ST-AMSTERDM     78
        167 ST           11040
        168 ST           18400
        169 ST           13800
        170 ST            3830
        174 ST              75
        174-175 STS       8280
        175 ST           14674
...                        ...
Weekend SUTPHIN-ARCHER    6499
        SUTTER AV            8
        SUTTER AV-RUTLD   1449
        THIRTY ST         4411
        THIRTY THIRD ST   4948
        TIMES SQ-42 ST   23667
        TOMPKINSVILLE      924
        TREMONT AV          36
        TWENTY THIRD ST   2412
        UNION ST          2875
        UTICA AV            52
        V.CORTLANDT PK    1932
        VAN SICLEN AV       81
        VAN SICLEN AVE      12
        VERNON-JACKSON    6279
        W 4 ST-WASH SQ      76
        W 8 ST-AQUARIUM   3864
        WAKEFIELD/241       20
        WALL ST          14322
        WEST FARMS SQ       36
        WESTCHESTER SQ    1449
        WHITEHALL S-FRY     60
        WHITLOCK AV       2898
        WILSON AV         1449
        WINTHROP ST         16
        WOODHAVEN BLVD    3908
        WOODLAWN          2415
        WORLD TRADE CTR   5313
        YORK ST             12
        ZEREGA AV           24

[746 rows x 6 columns]

In [208]:
new_data_reset = (new_data_grouped
    .reset_index()
    .sort_values(['dTOTAL'], ascending=(False))
)
new_data_reset

,WEEKDAY,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR
61,Weekday,34 ST-PENN STA,253073195252,123110236278,210641,134216,344857,79021
348,Weekday,TIMES SQ-42 ST,210091009097,169292782467,259691,81506,341197,45080
68,Weekday,42 ST-PORT AUTH,212870054777,146208281279,181641,104779,286420,31766
59,Weekday,34 ST-HERALD SQ,75244663509,59444423574,174488,71434,245922,48737
229,Weekday,GRD CNTRL-42 ST,263381436773,93042187947,148449,70728,219177,24630
9,Weekday,125 ST,37768180411,29981799537,95002,120527,215529,19580
721,Weekend,TIMES SQ-42 ST,95536700502,76939988037,158417,51733,210150,23667
46,Weekday,23 ST,246202814444,213675988350,148913,48770,197683,35494
253,Weekday,JKSN HT-ROOSVLT,6913057946,5151958704,55593,140972,196565,20102
109,Weekday,86 ST,78167107171,36281064086,107192,89309,196501,32440
14,Weekday,14 ST-UNION SQ,87168398335,32491281666,139343,51257,190600,570
86,Weekday,59 ST COLUMBUS,194140454597,172027333536,149424,38183,187607,37421
60,Weekday,34 ST-HUDSON YD,55585156,67958765,87167,90276,177443,17158
78,Weekday,50 ST,7956735885,7094812794,129257,45659,174916,32959
85,Weekday,59 ST,14309059546,11662203841,120230,54466,174696,46000
434,Weekend,34 ST-PENN STA,112517775155,54511109225,106118,66932,173050,40719
13,Weekday,14 ST,34903248265,11186839949,120341,45378,165719,29590
441,Weekend,42 ST-PORT AUTH,97330302381,67040346275,109177,51917,161094,16053
213,Weekday,FLUSHING-MAIN,10132031560,10149988210,46339,114387,160726,24748
387,Weekend,14 ST-UNION SQ,34631837602,13003137167,114553,39337,153890,152
15,Weekday,145 ST,80675365906,114021124232,37616,114677,152293,16583
432,Weekend,34 ST-HERALD SQ,33621301052,26459219846,91358,44239,135597,25599
222,Weekday,FULTON ST,214784086615,239592546764,79812,55476,135288,52265
358,Weekday,W 4 ST-WASH SQ,51527184030,57431162342,97174,33343,130517,278
145,Weekday,BEDFORD AV,10460012064,4751531558,65129,59515,124644,11017
113,Weekday,96 ST,51417818053,93230270229,52944,68538,121482,7795
482,Weekend,86 ST,35157850896,16080891917,62714,56211,118925,16969
179,Weekday,CHURCH AV,19199030634,8127182806,28416,89074,117490,25826
382,Weekend,125 ST,16198927878,13165835379,53033,64001,117034,10223
72,Weekday,47-50 STS ROCK,16573660511,10259127642,96268,18800,115068,33051
...,...,...,...,...,...,...,...,...
513,Weekend,BEACH 44 ST,61332626,79540306,336,1397,1733,2415
653,Weekend,MORRIS PARK,170438171,98132798,183,1524,1707,12
500,Weekend,AVENUE M,2915245327,190006251,892,789,1681,4830
422,Weekend,238 ST,496508913,22812548,1433,178,1611,12
570,Weekend,DITMAS AV,186918640,164427048,432,1178,1610,32
648,Weekend,METS-WILLETS PT,1245121658,291979925,615,995,1610,143
472,Weekend,75 AV,2753775221,30979421,1192,383,1575,3864
567,Weekend,CYPRESS HILLS,141733695,83164175,488,984,1472,1449
288,Weekday,NEPTUNE AV,422132691,168151268,896,549,1445,45
701,Weekend,ROCKAWAY PARK B,2732539437,282165172,334,1111,1445,20
504,Weekend,AVENUE X,292372413,274082483,847,584,1431,1449
509,Weekend,BAYCHESTER AV,345319187,31480246,772,537,1309,12
572,Weekend,E 143/ST MARY'S,120131355,134214645,390,876,1266,24
325,Weekday,RIT-ROOSEVELT,476948164,28958427,977,271,1248,90
698,Weekend,RIT-ROOSEVELT,190459551,11578248,1070,124,1194,24
137,Weekday,BEACH 105 ST,7707224567,103671642,272,889,1161,75
498,Weekend,AVENUE I,193003264,221225869,362,798,1160,12
506,Weekend,BAY 50 ST,249132832,214389178,596,538,1134,12
295,Weekday,NEWARK C,161474975,18614856,743,285,1028,9971
478,Weekend,80 ST,3394083557,172549916,529,493,1022,28
732,Weekend,W 8 ST-AQUARIUM,271347886,298141087,348,650,998,3864
158,Weekday,BROAD CHANNEL,114876176,39473366,680,263,943,45
349,Weekday,TOMPKINSVILLE,501165445,140069381,943,0,943,2236
517,Weekend,BEACH 98 ST,113145139,123413472,178,760,938,20
496,Weekend,ATLANTIC AV,42473546,17800050,439,335,774,1449
661,Weekend,NEPTUNE AV,168731200,67222910,242,356,598,12
722,Weekend,TOMPKINSVILLE,233262027,65204709,445,0,445,924
510,Weekend,BEACH 105 ST,3082874084,41449684,64,354,418,20
531,Weekend,BROAD CHANNEL,45930552,15782730,172,131,303,12
668,Weekend,NEWARK C,44105532,4589782,6,112,118,3289

In [209]:
# daysofweek = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

# whatdayofweek = lambda x: daysofweek[x.weekday()]


# data_reset['DAYOFWEEK'] = data_reset.DATETIME.apply(whatdayofweek)

In [210]:
for r in range(new_data_reset.shape[0]):
    if new_data_reset.ix[r,'WEEKDAY'] =='Weekday':
        new_data_reset.ix[r,'dTOTALACTUAL'] = new_data_reset.ix[r, 'dTOTAL']/(5*13)
    else:
        new_data_reset.ix[r,'dTOTALACTUAL'] = new_data_reset.ix[r, 'dTOTAL']/(2*13)

In [211]:
new_data_reset = (new_data_reset
    .sort_values(['dTOTALACTUAL'], ascending=(False))
)
new_data_reset

,WEEKDAY,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR,dTOTALACTUAL
721,Weekend,TIMES SQ-42 ST,95536700502,76939988037,158417,51733,210150,23667,8082.692308
434,Weekend,34 ST-PENN STA,112517775155,54511109225,106118,66932,173050,40719,6655.769231
441,Weekend,42 ST-PORT AUTH,97330302381,67040346275,109177,51917,161094,16053,6195.923077
387,Weekend,14 ST-UNION SQ,34631837602,13003137167,114553,39337,153890,152,5918.846154
61,Weekday,34 ST-PENN STA,253073195252,123110236278,210641,134216,344857,79021,5305.492308
348,Weekday,TIMES SQ-42 ST,210091009097,169292782467,259691,81506,341197,45080,5249.184615
432,Weekend,34 ST-HERALD SQ,33621301052,26459219846,91358,44239,135597,25599,5215.269231
482,Weekend,86 ST,35157850896,16080891917,62714,56211,118925,16969,4574.038462
382,Weekend,125 ST,16198927878,13165835379,53033,64001,117034,10223,4501.307692
68,Weekday,42 ST-PORT AUTH,212870054777,146208281279,181641,104779,286420,31766,4406.461538
731,Weekend,W 4 ST-WASH SQ,20895976200,23300734723,85393,27217,112610,76,4331.153846
419,Weekend,23 ST,105951704961,92440370660,76671,30917,107588,18478,4138.000000
386,Weekend,14 ST,15026152428,4898697701,70913,32018,102931,15496,3958.884615
602,Weekend,GRD CNTRL-42 ST,112940840068,38380898330,61849,36633,98482,13008,3787.769231
59,Weekday,34 ST-HERALD SQ,75244663509,59444423574,174488,71434,245922,48737,3783.415385
626,Weekend,JKSN HT-ROOSVLT,3030454734,2259763238,29620,67511,97131,10258,3735.807692
518,Weekend,BEDFORD AV,5035568483,2115135145,52522,41109,93631,5796,3601.192308
451,Weekend,50 ST,3620117117,3227844853,63618,29092,92710,17342,3565.769231
229,Weekday,GRD CNTRL-42 ST,263381436773,93042187947,148449,70728,219177,24630,3371.953846
9,Weekday,125 ST,37768180411,29981799537,95002,120527,215529,19580,3315.830769
458,Weekend,59 ST,6639518773,5416105075,55012,31155,86167,24787,3314.115385
459,Weekend,59 ST COLUMBUS,88920869780,78918534490,64238,20884,85122,19573,3273.923077
388,Weekend,145 ST,36801476035,51958409864,22982,60453,83435,9039,3209.038462
46,Weekday,23 ST,246202814444,213675988350,148913,48770,197683,35494,3041.276923
486,Weekend,96 ST,20620601902,37338390318,30228,48692,78920,3934,3035.384615
253,Weekday,JKSN HT-ROOSVLT,6913057946,5151958704,55593,140972,196565,20102,3024.076923
109,Weekday,86 ST,78167107171,36281064086,107192,89309,196501,32440,3023.092308
373,Weekend,1 AV,35211081735,36675806603,45421,33080,78501,4715,3019.269231
586,Weekend,FLUSHING-MAIN,4602411396,4609467058,27873,49265,77138,12972,2966.846154
14,Weekday,14 ST-UNION SQ,87168398335,32491281666,139343,51257,190600,570,2932.307692
...,...,...,...,...,...,...,...,...,...
199,Weekday,E 143/ST MARY'S,300504382,335726292,1318,2006,3324,90,51.138462
509,Weekend,BAYCHESTER AV,345319187,31480246,772,537,1309,12,50.346154
194,Weekday,CYPRESS HILLS,312260122,183230747,947,2318,3265,2760,50.230769
572,Weekend,E 143/ST MARY'S,120131355,134214645,390,876,1266,24,48.692308
324,Weekday,RIT-MANHATTAN,192515345,2526834,2823,214,3037,60,46.723077
698,Weekend,RIT-ROOSEVELT,190459551,11578248,1070,124,1194,24,45.923077
131,Weekday,AVENUE X,643955865,603126262,1852,1130,2982,2760,45.876923
498,Weekend,AVENUE I,193003264,221225869,362,798,1160,12,44.615385
506,Weekend,BAY 50 ST,249132832,214389178,596,538,1134,12,43.615385
105,Weekday,80 ST,8245059615,427603477,1916,892,2808,104,43.200000
99,Weekday,75 AV,6059415204,68276394,1764,838,2602,7360,40.030769
359,Weekday,W 8 ST-AQUARIUM,597573394,656323375,950,1638,2588,7360,39.815385
478,Weekend,80 ST,3394083557,172549916,529,493,1022,28,39.307692
732,Weekend,W 8 ST-AQUARIUM,271347886,298141087,348,650,998,3864,38.384615
125,Weekday,AVENUE I,482777476,553340483,920,1570,2490,45,38.307692
517,Weekend,BEACH 98 ST,113145139,123413472,178,760,938,20,36.076923
144,Weekday,BEACH 98 ST,282945265,308616452,722,1573,2295,75,35.307692
496,Weekend,ATLANTIC AV,42473546,17800050,439,335,774,1449,29.769231
123,Weekday,ATLANTIC AV,93733859,39280304,963,775,1738,2760,26.738462
661,Weekend,NEPTUNE AV,168731200,67222910,242,356,598,12,23.000000
288,Weekday,NEPTUNE AV,422132691,168151268,896,549,1445,45,22.230769
325,Weekday,RIT-ROOSEVELT,476948164,28958427,977,271,1248,90,19.200000
137,Weekday,BEACH 105 ST,7707224567,103671642,272,889,1161,75,17.861538
722,Weekend,TOMPKINSVILLE,233262027,65204709,445,0,445,924,17.115385
510,Weekend,BEACH 105 ST,3082874084,41449684,64,354,418,20,16.076923
295,Weekday,NEWARK C,161474975,18614856,743,285,1028,9971,15.815385
158,Weekday,BROAD CHANNEL,114876176,39473366,680,263,943,45,14.507692
349,Weekday,TOMPKINSVILLE,501165445,140069381,943,0,943,2236,14.507692
531,Weekend,BROAD CHANNEL,45930552,15782730,172,131,303,12,11.653846
668,Weekend,NEWARK C,44105532,4589782,6,112,118,3289,4.538462

In [212]:
#testweekend = data_reset[(data_reset.WEEKDAY == 'Weekday')]

In [213]:
#testweekend

In [214]:
# import numpy as np
# import matplotlib.pyplot as plt
# %matplotlib inline

In [215]:
#data_reset[data_reset.STATION=='WORLD TRADE CTR'].dTOTAL.plot(kind='bar');
# data_reset[data_reset.STATION=='WORLD TRADE CTR'].hist(by = data_reset.DATE, bins = 25, figsize = (100,50));