In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
"""
list_data =[]
list_weeks = ['160102', '160109', '160116','160130','160206','160213',
              '160220','160227','160305','160312','160319','160326','160402']
for u in list_weeks:
    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'
    print(url)
    list_data.append(pd.read_csv(url))

data = pd.concat(list_data)
del list_data"""

"\nlist_data =[]\nlist_weeks = ['160102', '160109', '160116','160130','160206','160213',\n              '160220','160227','160305','160312','160319','160326','160402']\nfor u in list_weeks:\n    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'\n    print(url)\n    list_data.append(pd.read_csv(url))\n\ndata = pd.concat(list_data)\ndel list_data"

In [3]:
data = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_160213.txt")

In [4]:
data.columns = [column.strip() for column in data.columns]
data.columns

Index([u'C/A', u'UNIT', u'SCP', u'STATION', u'LINENAME', u'DIVISION', u'DATE',
       u'TIME', u'DESC', u'ENTRIES', u'EXITS'],
      dtype='object')

In [5]:
data.rename(columns={"EXITS": "EXIT", "ENTRIES": "ENTRY"}, inplace=True)

In [6]:
data['dENTRY'] = 0
data['dEXIT'] = 0

In [7]:
data['dENTRY'] = data.ENTRY.shift(-1) - data.ENTRY
data['dEXIT'] = data.EXIT.shift(-1) - data.EXIT
data['dTOTAL'] = data.dENTRY + data.dEXIT

In [8]:
#diff = data['ENTRY'].iloc[1:].values - data['ENTRY'].iloc[:-1].values
#data['DENTRY'][1:] = diff
#diff = data['EXIT'].iloc[:-1].values - data['EXIT'].iloc[1:].values
#data['DEXIT'][1:] = diff

In [9]:
data['DATETIME'] = pd.to_datetime(data.DATE + data.TIME, format='%m/%d/%Y%H:%M:%S')
data['HOUR'] = data['DATETIME'].apply(lambda x: x.hour)

In [10]:
data['WEEKDAY']=data.DATETIME.apply(lambda x: 'Weekday' if 0<=x.weekday()<5 else 'Weekend')

In [11]:
daysofweek = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

whatdayofweek = lambda x: daysofweek[x.weekday()]


data['DAYOFWEEK'] = data.DATETIME.apply(whatdayofweek)

In [12]:
data_cleaned = data[(data['dENTRY'] >= 0) & (data['dENTRY'] <= 5000) & (data['dEXIT'] >= 0) & (data['dEXIT'] <= 5000)]

In [13]:
data_0to4 = data_cleaned[(data_cleaned.HOUR ==0)|(data_cleaned.HOUR==1)]

In [14]:
data_0to4

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,DATETIME,HOUR,WEEKDAY,DAYOFWEEK
504,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/06/2016,01:00:00,REGULAR,2082365,3666629,17,14,31,2016-02-06 01:00:00,1,Weekend,Saturday
510,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/07/2016,01:00:00,REGULAR,2083389,3668220,15,6,21,2016-02-07 01:00:00,1,Weekend,Sunday
516,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/08/2016,01:00:00,REGULAR,2084123,3669302,9,9,18,2016-02-08 01:00:00,1,Weekday,Monday
522,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/09/2016,01:00:00,REGULAR,2085908,3672126,7,18,25,2016-02-09 01:00:00,1,Weekday,Tuesday
528,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/10/2016,01:00:00,REGULAR,2087685,3675229,9,5,14,2016-02-10 01:00:00,1,Weekday,Wednesday
534,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/11/2016,01:00:00,REGULAR,2089506,3678389,9,12,21,2016-02-11 01:00:00,1,Weekday,Thursday
540,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/12/2016,01:00:00,REGULAR,2091321,3681575,14,10,24,2016-02-12 01:00:00,1,Weekday,Friday
546,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/06/2016,01:00:00,REGULAR,3349049,2184658,22,5,27,2016-02-06 01:00:00,1,Weekend,Saturday
552,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/07/2016,01:00:00,REGULAR,3349966,2185144,11,4,15,2016-02-07 01:00:00,1,Weekend,Sunday
558,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/08/2016,01:00:00,REGULAR,3350636,2185493,3,0,3,2016-02-08 01:00:00,1,Weekday,Monday
564,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/09/2016,01:00:00,REGULAR,3352269,2186316,4,0,4,2016-02-09 01:00:00,1,Weekday,Tuesday
570,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/10/2016,01:00:00,REGULAR,3354019,2187209,4,3,7,2016-02-10 01:00:00,1,Weekday,Wednesday
576,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/11/2016,01:00:00,REGULAR,3355856,2188064,7,3,10,2016-02-11 01:00:00,1,Weekday,Thursday
582,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/12/2016,01:00:00,REGULAR,3357636,2188977,7,3,10,2016-02-12 01:00:00,1,Weekday,Friday
588,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/06/2016,01:00:00,REGULAR,7234438,3211378,7,5,12,2016-02-06 01:00:00,1,Weekend,Saturday
594,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/07/2016,01:00:00,REGULAR,7235091,3211635,3,1,4,2016-02-07 01:00:00,1,Weekend,Sunday
600,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/08/2016,01:00:00,REGULAR,7235526,3211808,5,2,7,2016-02-08 01:00:00,1,Weekday,Monday
606,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/09/2016,01:00:00,REGULAR,7236734,3212296,3,0,3,2016-02-09 01:00:00,1,Weekday,Tuesday
612,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/10/2016,01:00:00,REGULAR,7238134,3212794,3,1,4,2016-02-10 01:00:00,1,Weekday,Wednesday
618,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/11/2016,01:00:00,REGULAR,7239526,3213242,2,0,2,2016-02-11 01:00:00,1,Weekday,Thursday
624,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/12/2016,01:00:00,REGULAR,7240920,3213803,2,2,4,2016-02-12 01:00:00,1,Weekday,Friday
630,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/06/2016,01:00:00,REGULAR,1914240,718805,7,0,7,2016-02-06 01:00:00,1,Weekend,Saturday
636,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/07/2016,01:00:00,REGULAR,1914763,718974,10,1,11,2016-02-07 01:00:00,1,Weekend,Sunday
642,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/08/2016,01:00:00,REGULAR,1915119,719074,1,0,1,2016-02-08 01:00:00,1,Weekday,Monday
648,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/09/2016,01:00:00,REGULAR,1916027,719447,5,1,6,2016-02-09 01:00:00,1,Weekday,Tuesday
654,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/10/2016,01:00:00,REGULAR,1917058,719812,3,0,3,2016-02-10 01:00:00,1,Weekday,Wednesday
660,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/11/2016,01:00:00,REGULAR,1918147,720205,3,1,4,2016-02-11 01:00:00,1,Weekday,Thursday
666,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/12/2016,01:00:00,REGULAR,1919206,720592,3,0,3,2016-02-12 01:00:00,1,Weekday,Friday
672,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,02/06/2016,01:00:00,REGULAR,6637247,2942790,6,0,6,2016-02-06 01:00:00,1,Weekend,Saturday
678,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,02/07/2016,01:00:00,REGULAR,6637760,2942947,6,0,6,2016-02-07 01:00:00,1,Weekend,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193797,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,02/11/2016,00:00:00,REGULAR,1475071,15332,3,4,7,2016-02-11 00:00:00,0,Weekday,Thursday
193803,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,02/12/2016,00:00:00,REGULAR,1476536,15343,7,4,11,2016-02-12 00:00:00,0,Weekday,Friday
193810,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/06/2016,00:00:00,REGULAR,280394,11479,0,0,0,2016-02-06 00:00:00,0,Weekend,Saturday
193816,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/07/2016,00:00:00,REGULAR,280681,11483,5,4,9,2016-02-07 00:00:00,0,Weekend,Sunday
193822,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/08/2016,00:00:00,REGULAR,280880,11504,0,0,0,2016-02-08 00:00:00,0,Weekday,Monday
193828,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/09/2016,00:00:00,REGULAR,281050,11508,1,3,4,2016-02-09 00:00:00,0,Weekday,Tuesday
193834,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/10/2016,00:00:00,REGULAR,281191,11515,6,0,6,2016-02-10 00:00:00,0,Weekday,Wednesday
193840,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/11/2016,00:00:00,REGULAR,281404,11517,2,1,3,2016-02-11 00:00:00,0,Weekday,Thursday
193846,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/12/2016,00:00:00,REGULAR,281604,11526,0,0,0,2016-02-12 00:00:00,0,Weekday,Friday
193853,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/06/2016,00:00:00,REGULAR,2592649,376184,0,0,0,2016-02-06 00:00:00,0,Weekend,Saturday
193859,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/07/2016,00:00:00,REGULAR,2592941,376198,5,0,5,2016-02-07 00:00:00,0,Weekend,Sunday
193865,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/08/2016,00:00:00,REGULAR,2593189,376212,2,0,2,2016-02-08 00:00:00,0,Weekday,Monday
193871,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/09/2016,00:00:00,REGULAR,2593401,376221,0,3,3,2016-02-09 00:00:00,0,Weekday,Tuesday
193877,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/10/2016,00:00:00,REGULAR,2593575,376229,1,0,1,2016-02-10 00:00:00,0,Weekday,Wednesday
193883,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/11/2016,00:00:00,REGULAR,2593820,376241,0,0,0,2016-02-11 00:00:00,0,Weekday,Thursday
193889,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/12/2016,00:00:00,REGULAR,2594028,376251,0,0,0,2016-02-12 00:00:00,0,Weekday,Friday
193896,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/06/2016,00:00:00,REGULAR,2081,62,0,0,0,2016-02-06 00:00:00,0,Weekend,Saturday
193902,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/07/2016,00:00:00,REGULAR,2083,62,0,0,0,2016-02-07 00:00:00,0,Weekend,Sunday
193908,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/08/2016,00:00:00,REGULAR,2083,62,0,0,0,2016-02-08 00:00:00,0,Weekday,Monday
193914,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/09/2016,00:00:00,REGULAR,2083,62,0,0,0,2016-02-09 00:00:00,0,Weekday,Tuesday
193920,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/10/2016,00:00:00,REGULAR,2084,62,0,0,0,2016-02-10 00:00:00,0,Weekday,Wednesday
193926,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/11/2016,00:00:00,REGULAR,2085,62,0,0,0,2016-02-11 00:00:00,0,Weekday,Thursday
193932,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/12/2016,00:00:00,REGULAR,2085,62,0,0,0,2016-02-12 00:00:00,0,Weekday,Friday
193939,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/06/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-06 00:00:00,0,Weekend,Saturday
193945,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/07/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-07 00:00:00,0,Weekend,Sunday
193951,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/08/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-08 00:00:00,0,Weekday,Monday
193957,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/09/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-09 00:00:00,0,Weekday,Tuesday
193963,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/10/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-10 00:00:00,0,Weekday,Wednesday
193969,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/11/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-11 00:00:00,0,Weekday,Thursday
193975,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/12/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-12 00:00:00,0,Weekday,Friday

In [15]:
data_grouped = data_0to4.groupby(['DATE','STATION']).sum()

In [16]:
data_grouped

                                 ENTRY        EXIT  dENTRY  dEXIT  dTOTAL  \
DATE       STATION
02/06/2016 103 ST            150848114   593357271     511    497    1008
           111 ST             56039639    20708175       3      2       5
           116 ST            435130082   443827793     627    807    1434
           116 ST-COLUMBIA  1209750947   255981771     256    249     505
           125 ST            147541879   106467659     968    988    1956
           135 ST            202987844    30428030      79    109     188
           137 ST CITY COL    52005477    41170027     186    656     842
           14 ST             264335769    53125369     980    412    1392
           14 ST-UNION SQ   1294207716   500010299    4864   1587    6451
           14TH STREET         2807320      384251     101    110     211
           155 ST             30941148    23639371     103    275     378
           157 ST             31831629    21367412     219    689     908
           163 ST-AMSTERDM    16808923    11321239      75    133     208
           170 ST           1284767182  2348659090     107    245     352
           174 ST             21764258    14571634     116    304     420
           18 AV              20647745    21212015      12    174     186
           181 ST             51723488    43010385      96    427     523
           20 AV              14626105    12625968       2     50      52
           21 ST               5637062     6378214     167    105     272
           219 ST              9677845     5934880      69     63     132
           225 ST             10761433     6356489      67    110     177
           23 ST            2189466615  1832027969    1107    443    1550
           233 ST             95383496     4563351      75    101     176
           238 ST             19079020      877101      48      6      54
           25 AV               3673260     1240978      52     67     119
           28 ST            1512723072  2082719869    1316    516    1832
           3 AV 138 ST        17708236    15100651     142    382     524
           33 ST             346007464   136939842     868    311    1179
           34 ST-PENN STA   1881599400  1219074981     671    520    1191
           36 ST             327492832  1233553515     283    537     820
...                                ...         ...     ...    ...     ...
02/12/2016 RALPH AV           21143685    16774809      96    168     264
           RIT-MANHATTAN       2516672       29111      43      2      45
           RIT-ROOSEVELT       7319840      445379      13      5      18
           ROCKAWAY AV       716760614    42381203      67    173     240
           ROCKAWAY BLVD     263964236    10967648      98     98     196
           ROCKAWAY PARK B   105097504    10852674      16     49      65
           SENECA AVE          5162911     5754395      18     73      91
           SHEEPSHEAD BAY     39992102    36123987     104    293     397
           SHEPHERD AV        16810683    14396444      42    111     153
           SIMPSON ST         37360331    10304670     110     33     143
           SOUTH FERRY        35323940    31062278     100    314     414
           SUTPHIN BLVD       18032344     9709814      36    135     171
           SUTTER AV          10763453    14884983      77    176     253
           THIRTY ST           2700166     5367839      55     26      81
           THIRTY THIRD ST    10614047     6372503     279    133     412
           TOMPKINSVILLE       8638563     2414988       6      0       6
           TREMONT AV        129183748    10885749     132    435     567
           TWENTY THIRD ST     3005962     1650409      71     56     127
           UTICA AV          102965684    50163794     205    520     725
           VAN SICLEN AV      12269546    12024824      32     75     107
           VAN SICLEN AVE     13300799    13800059      37    180     217
           W 4 ST-WASH SQ    803868675   896459716    1798    517    2315
           WAKEFIELD/241      16193657    16751501     105    257     362
           WALL ST           533602698   278198449      73     52     125
           WEST FARMS SQ     438297982    72965983     131    204     335
           WHITEHALL S-FRY   265758420    62473093     116    149     265
           WINTHROP ST        31586920     5591057      47     41      88
           WOODHAVEN BLVD     55487457    36697174     139    340     479
           YORK ST            31585785    28922052      97     80     177
           ZEREGA AV          53559492      545314      17     63      80

                            HOUR
DATE       STATION
02/06/2016 103 ST              0
           111 ST              0
           116 ST              0
           116 ST-COLUMBIA     0
           125 ST              0
           135 ST              0
           137 ST CITY COL     0
           14 ST               0
           14 ST-UNION SQ      0
           14TH STREET         4
           155 ST              0
           157 ST              0
           163 ST-AMSTERDM     0
           170 ST              0
           174 ST              0
           18 AV               0
           181 ST              0
           20 AV               0
           21 ST               0
           219 ST              0
           225 ST              0
           23 ST               0
           233 ST              0
           238 ST              0
           25 AV               0
           28 ST               0
           3 AV 138 ST         0
           33 ST               0
           34 ST-PENN STA     21
           36 ST               0
...                          ...
02/12/2016 RALPH AV            0
           RIT-MANHATTAN       0
           RIT-ROOSEVELT       0
           ROCKAWAY AV         0
           ROCKAWAY BLVD       0
           ROCKAWAY PARK B     0
           SENECA AVE          0
           SHEEPSHEAD BAY      0
           SHEPHERD AV         0
           SIMPSON ST          0
           SOUTH FERRY         0
           SUTPHIN BLVD        0
           SUTTER AV           0
           THIRTY ST           6
           THIRTY THIRD ST     7
           TOMPKINSVILLE       7
           TREMONT AV          0
           TWENTY THIRD ST     5
           UTICA AV            0
           VAN SICLEN AV       0
           VAN SICLEN AVE      0
           W 4 ST-WASH SQ      0
           WAKEFIELD/241       0
           WALL ST            28
           WEST FARMS SQ       0
           WHITEHALL S-FRY     0
           WINTHROP ST         0
           WOODHAVEN BLVD      0
           YORK ST             0
           ZEREGA AV           0

[1373 rows x 6 columns]

In [19]:
data_reset = (data_grouped
    .reset_index()
    .sort_values(['dTOTAL'], ascending=(False))
)
data_reset

,DATE,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR
206,02/07/2016,14 ST-UNION SQ,1294280919,500076323,4818,1873,6691,0
8,02/06/2016,14 ST-UNION SQ,1294207716,500010299,4864,1587,6451,0
189,02/06/2016,W 4 ST-WASH SQ,803644809,896244242,3724,1414,5138,0
381,02/07/2016,W 4 ST-WASH SQ,803676841,896279619,3789,1203,4992,0
91,02/06/2016,DELANCEY/ESSEX,1711568696,1111628489,1662,1885,3547,0
1185,02/12/2016,14 ST-UNION SQ,1294750635,500479903,2605,882,3487,0
249,02/07/2016,96 ST,771872841,1417251738,1355,1970,3325,0
243,02/07/2016,8 AV,198296085,91606454,2305,985,3290,0
287,02/07/2016,DELANCEY/ESSEX,1711588264,1111650122,1839,1361,3200,0
45,02/06/2016,8 AV,198264613,91583186,2229,887,3116,0
228,02/07/2016,42 ST-PORT AUTH,323590294,102897390,2326,786,3112,19
51,02/06/2016,96 ST,771830269,1417219023,1185,1700,2885,0
986,02/11/2016,14 ST-UNION SQ,1294644736,500388448,2140,658,2798,0
30,02/06/2016,42 ST-PORT AUTH,323559983,102876229,2018,659,2677,19
795,02/10/2016,14 ST-UNION SQ,1294535753,500295479,2058,591,2649,0
597,02/09/2016,14 ST-UNION SQ,1294430026,500206023,1791,558,2349,0
1364,02/12/2016,W 4 ST-WASH SQ,803868675,896459716,1798,517,2315,0
1135,02/11/2016,NORTHERN BLVD,22519413,22763045,1728,577,2305,0
398,02/08/2016,14 ST-UNION SQ,1294336108,500123488,1406,729,2135,0
1168,02/11/2016,W 4 ST-WASH SQ,803825163,896418376,1598,485,2083,0
4,02/06/2016,125 ST,147541879,106467659,968,988,1956,0
202,02/07/2016,125 ST,147565216,106485837,955,963,1918,0
969,02/10/2016,W 4 ST-WASH SQ,803781446,896378248,1445,463,1908,0
140,02/06/2016,METROPOLITAN AV,29597446,21963902,1238,668,1906,0
112,02/06/2016,GRD CNTRL-42 ST,3967774257,1428836979,1380,504,1884,0
25,02/06/2016,28 ST,1512723072,2082719869,1316,516,1832,0
1207,02/12/2016,42 ST-PORT AUTH,323739264,103016891,1286,542,1828,19
1222,02/12/2016,8 AV,198462773,91721576,1315,509,1824,0
334,02/07/2016,METROPOLITAN AV,29607581,21970524,1254,550,1804,0
1267,02/12/2016,DELANCEY/ESSEX,1711700019,1111739626,789,950,1739,0
...,...,...,...,...,...,...,...,...
1248,02/12/2016,BROAD ST,21798802,12948108,2,4,6,0
1060,02/11/2016,CHRISTOPHER ST,266800,211840,5,1,6,0
709,02/09/2016,HUNTERS PT AV,2101576063,858859343,0,5,5,0
1,02/06/2016,111 ST,56039639,20708175,3,2,5,0
979,02/11/2016,111 ST,56041180,20708544,3,2,5,0
267,02/07/2016,BROAD CHANNEL,1765348,606718,4,1,5,0
461,02/08/2016,BROAD ST,21769745,12938317,3,1,4,0
542,02/08/2016,NEWARK C,2532285,291503,0,4,4,1
333,02/07/2016,MARCY AV,166938266,485565059,0,3,3,0
943,02/10/2016,PATH WTC,146358,44306,2,1,3,1
569,02/08/2016,SOUTH FERRY,35278441,31008362,1,1,2,0
529,02/08/2016,MARCY AV,159665039,483509228,1,1,2,0
1111,02/11/2016,LACKAWANNA,268526,116961,0,2,2,0
349,02/07/2016,NEWKIRK PLAZA,48102899,45747266,0,1,1,0
347,02/07/2016,NEWARK HW BMEBE,86511,3674,0,1,1,0
355,02/07/2016,PARKSIDE AV,33795639,30596164,0,0,0,0
422,02/08/2016,5 AV/53 ST,84009907,90443511,0,0,0,21
1130,02/11/2016,NEWARK C,325897,125018,0,0,0,0
356,02/07/2016,PATH WTC,145083,44177,0,0,0,1
152,02/06/2016,NEWARK C,1026509,87167,0,0,0,6
546,02/08/2016,NEWKIRK PLAZA,48102899,45747273,0,0,0,0
162,02/06/2016,PARKSIDE AV,33795639,30596161,0,0,0,0
345,02/07/2016,NEWARK C,115034,2531,0,0,0,0
374,02/07/2016,THIRTY THIRD ST,9,958156,0,0,0,0
230,02/07/2016,5 AV/53 ST,84009907,90443511,0,0,0,21
869,02/10/2016,CITY / BUS,998,6186,0,0,0,0
280,02/07/2016,CITY / BUS,959,6077,0,0,0,0
32,02/06/2016,5 AV/53 ST,84009907,90443509,0,0,0,21
552,02/08/2016,PARKSIDE AV,33795640,30596165,0,0,0,0
370,02/07/2016,SOUTH FERRY,35278436,31008348,0,0,0,0

In [18]:
for r in range(data_reset.shape[0]):
    if data_reset.ix[r,'WEEKDAY'] =='Weekday':
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(5)
    else:
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(2)

KeyError: 'WEEKDAY'

In [ ]:
data_reset

In [ ]:
testweekend = data_reset[(data_reset.WEEKDAY == 'Weekday')]

In [ ]:
testweekend

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#data_reset[data_reset.STATION=='WORLD TRADE CTR'].dTOTAL.plot(kind='bar');
data_reset[data_reset.STATION=='WORLD TRADE CTR'].hist(by = data_reset.DATE, bins = 25, figsize = (100,50));