In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
"""
list_data =[]
list_weeks = ['160102', '160109', '160116','160130','160206','160213',
              '160220','160227','160305','160312','160319','160326','160402']
for u in list_weeks:
    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'
    print(url)
    list_data.append(pd.read_csv(url))

data = pd.concat(list_data)
del list_data"""

"\nlist_data =[]\nlist_weeks = ['160102', '160109', '160116','160130','160206','160213',\n              '160220','160227','160305','160312','160319','160326','160402']\nfor u in list_weeks:\n    url = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_' + u + '.txt'\n    print(url)\n    list_data.append(pd.read_csv(url))\n\ndata = pd.concat(list_data)\ndel list_data"

In [3]:
data = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_160206.txt")

In [4]:
data.columns = [column.strip() for column in data.columns]
data.columns

Index([u'C/A', u'UNIT', u'SCP', u'STATION', u'LINENAME', u'DIVISION', u'DATE',
       u'TIME', u'DESC', u'ENTRIES', u'EXITS'],
      dtype='object')

In [5]:
data.rename(columns={"EXITS": "EXIT", "ENTRIES": "ENTRY"}, inplace=True)

In [6]:
data['dENTRY'] = 0
data['dEXIT'] = 0

In [7]:
data['dENTRY'] = data.ENTRY.shift(-1) - data.ENTRY
data['dEXIT'] = data.EXIT.shift(-1) - data.EXIT
data['dTOTAL'] = data.dENTRY + data.dEXIT

In [8]:
#diff = data['ENTRY'].iloc[1:].values - data['ENTRY'].iloc[:-1].values
#data['DENTRY'][1:] = diff
#diff = data['EXIT'].iloc[:-1].values - data['EXIT'].iloc[1:].values
#data['DEXIT'][1:] = diff

In [9]:
data['DATETIME'] = pd.to_datetime(data.DATE + data.TIME, format='%m/%d/%Y%H:%M:%S')
data['HOUR'] = data['DATETIME'].apply(lambda x: x.hour)

In [10]:
data['WEEKDAY']=data.DATETIME.apply(lambda x: 'Weekday' if 0<=x.weekday()<5 else 'Weekend')

In [11]:
daysofweek = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

whatdayofweek = lambda x: daysofweek[x.weekday()]


data['DAYOFWEEK'] = data.DATETIME.apply(whatdayofweek)

In [12]:
data_cleaned = data[(data['dENTRY'] >= 0) & (data['dENTRY'] <= 5000) & (data['dEXIT'] >= 0) & (data['dEXIT'] <= 5000)]

In [13]:
data_0to4 = data_cleaned[(data_cleaned.HOUR ==0)|(data_cleaned.HOUR==1)]

In [14]:
data_0to4

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,DATETIME,HOUR,WEEKDAY,DAYOFWEEK
504,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/30/2016,01:00:00,REGULAR,2071399,3649713,13,12,25,2016-01-30 01:00:00,1,Weekend,Saturday
510,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,01/31/2016,01:00:00,REGULAR,2072386,3651174,13,9,22,2016-01-31 01:00:00,1,Weekend,Sunday
516,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/01/2016,01:00:00,REGULAR,2073175,3652331,8,14,22,2016-02-01 01:00:00,1,Weekday,Monday
522,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/02/2016,01:00:00,REGULAR,2074961,3655252,5,9,14,2016-02-02 01:00:00,1,Weekday,Tuesday
528,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/03/2016,01:00:00,REGULAR,2076925,3658152,16,8,24,2016-02-03 01:00:00,1,Weekday,Wednesday
534,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/04/2016,01:00:00,REGULAR,2078755,3660957,5,9,14,2016-02-04 01:00:00,1,Weekday,Thursday
540,A006,R079,00-00-00,5 AV/59 ST,NQR,BMT,02/05/2016,01:00:00,REGULAR,2080647,3663751,14,20,34,2016-02-05 01:00:00,1,Weekday,Friday
546,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/30/2016,01:00:00,REGULAR,3338790,2179636,6,1,7,2016-01-30 01:00:00,1,Weekend,Saturday
552,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,01/31/2016,01:00:00,REGULAR,3339617,2180169,11,3,14,2016-01-31 01:00:00,1,Weekend,Sunday
558,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/01/2016,01:00:00,REGULAR,3340305,2180534,5,2,7,2016-02-01 01:00:00,1,Weekday,Monday
564,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/02/2016,01:00:00,REGULAR,3342000,2181397,6,2,8,2016-02-02 01:00:00,1,Weekday,Tuesday
570,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/03/2016,01:00:00,REGULAR,3343810,2182241,11,3,14,2016-02-03 01:00:00,1,Weekday,Wednesday
576,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/04/2016,01:00:00,REGULAR,3345582,2182990,3,3,6,2016-02-04 01:00:00,1,Weekday,Thursday
582,A006,R079,00-00-01,5 AV/59 ST,NQR,BMT,02/05/2016,01:00:00,REGULAR,3347318,2183858,13,3,16,2016-02-05 01:00:00,1,Weekday,Friday
588,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/30/2016,01:00:00,REGULAR,7226694,3208474,5,1,6,2016-01-30 01:00:00,1,Weekend,Saturday
593,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,01/31/2016,01:00:00,REGULAR,7227297,3208739,8,0,8,2016-01-31 01:00:00,1,Weekend,Sunday
599,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/01/2016,01:00:00,REGULAR,7227793,3208910,7,1,8,2016-02-01 01:00:00,1,Weekday,Monday
605,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/02/2016,01:00:00,REGULAR,7229101,3209361,4,2,6,2016-02-02 01:00:00,1,Weekday,Tuesday
611,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/03/2016,01:00:00,REGULAR,7230511,3209871,3,2,5,2016-02-03 01:00:00,1,Weekday,Wednesday
617,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/04/2016,01:00:00,REGULAR,7231861,3210364,3,0,3,2016-02-04 01:00:00,1,Weekday,Thursday
623,A006,R079,00-00-02,5 AV/59 ST,NQR,BMT,02/05/2016,01:00:00,REGULAR,7233176,3210874,11,3,14,2016-02-05 01:00:00,1,Weekday,Friday
629,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/30/2016,01:00:00,REGULAR,1908196,716755,2,1,3,2016-01-30 01:00:00,1,Weekend,Saturday
635,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,01/31/2016,01:00:00,REGULAR,1908712,716899,6,0,6,2016-01-31 01:00:00,1,Weekend,Sunday
641,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/01/2016,01:00:00,REGULAR,1909098,716989,6,1,7,2016-02-01 01:00:00,1,Weekday,Monday
647,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/02/2016,01:00:00,REGULAR,1910101,717311,4,1,5,2016-02-02 01:00:00,1,Weekday,Tuesday
653,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/03/2016,01:00:00,REGULAR,1911176,717714,3,1,4,2016-02-03 01:00:00,1,Weekday,Wednesday
659,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/04/2016,01:00:00,REGULAR,1912242,718086,6,0,6,2016-02-04 01:00:00,1,Weekday,Thursday
665,A006,R079,00-00-03,5 AV/59 ST,NQR,BMT,02/05/2016,01:00:00,REGULAR,1913266,718452,7,0,7,2016-02-05 01:00:00,1,Weekday,Friday
671,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,01/30/2016,01:00:00,REGULAR,6631499,2940532,3,1,4,2016-01-30 01:00:00,1,Weekend,Saturday
677,A006,R079,00-00-04,5 AV/59 ST,NQR,BMT,01/31/2016,01:00:00,REGULAR,6631974,2940730,6,0,6,2016-01-31 01:00:00,1,Weekend,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195172,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,02/04/2016,00:00:00,REGULAR,1465647,15223,6,1,7,2016-02-04 00:00:00,0,Weekday,Thursday
195179,TRAM2,R469,00-00-01,RIT-ROOSEVELT,R,RIT,02/05/2016,00:00:00,REGULAR,1467095,15234,2,1,3,2016-02-05 00:00:00,0,Weekday,Friday
195186,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/30/2016,00:00:00,REGULAR,279072,11408,2,1,3,2016-01-30 00:00:00,0,Weekend,Saturday
195192,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,01/31/2016,00:00:00,REGULAR,279314,11412,0,1,1,2016-01-31 00:00:00,0,Weekend,Sunday
195198,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/01/2016,00:00:00,REGULAR,279524,11424,2,1,3,2016-02-01 00:00:00,0,Weekday,Monday
195204,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/02/2016,00:00:00,REGULAR,279710,11449,3,0,3,2016-02-02 00:00:00,0,Weekday,Tuesday
195210,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/03/2016,00:00:00,REGULAR,279885,11458,1,0,1,2016-02-03 00:00:00,0,Weekday,Wednesday
195217,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/04/2016,00:00:00,REGULAR,280050,11464,0,1,1,2016-02-04 00:00:00,0,Weekday,Thursday
195224,TRAM2,R469,00-03-00,RIT-ROOSEVELT,R,RIT,02/05/2016,00:00:00,REGULAR,280222,11472,0,1,1,2016-02-05 00:00:00,0,Weekday,Friday
195231,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/30/2016,00:00:00,REGULAR,2590999,376106,1,0,1,2016-01-30 00:00:00,0,Weekend,Saturday
195237,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/31/2016,00:00:00,REGULAR,2591292,376125,2,0,2,2016-01-31 00:00:00,0,Weekend,Sunday
195243,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/01/2016,00:00:00,REGULAR,2591580,376140,2,0,2,2016-02-01 00:00:00,0,Weekday,Monday
195249,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/02/2016,00:00:00,REGULAR,2591815,376146,0,4,4,2016-02-02 00:00:00,0,Weekday,Tuesday
195255,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/03/2016,00:00:00,REGULAR,2592006,376157,2,1,3,2016-02-03 00:00:00,0,Weekday,Wednesday
195262,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/04/2016,00:00:00,REGULAR,2592229,376164,2,0,2,2016-02-04 00:00:00,0,Weekday,Thursday
195269,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,02/05/2016,00:00:00,REGULAR,2592447,376177,1,0,1,2016-02-05 00:00:00,0,Weekday,Friday
195276,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/30/2016,00:00:00,REGULAR,2076,62,0,0,0,2016-01-30 00:00:00,0,Weekend,Saturday
195282,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,01/31/2016,00:00:00,REGULAR,2078,62,0,0,0,2016-01-31 00:00:00,0,Weekend,Sunday
195288,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/01/2016,00:00:00,REGULAR,2078,62,0,0,0,2016-02-01 00:00:00,0,Weekday,Monday
195294,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/02/2016,00:00:00,REGULAR,2078,62,0,0,0,2016-02-02 00:00:00,0,Weekday,Tuesday
195300,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/03/2016,00:00:00,REGULAR,2078,62,0,0,0,2016-02-03 00:00:00,0,Weekday,Wednesday
195307,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/04/2016,00:00:00,REGULAR,2079,62,0,0,0,2016-02-04 00:00:00,0,Weekday,Thursday
195314,TRAM2,R469,00-05-00,RIT-ROOSEVELT,R,RIT,02/05/2016,00:00:00,REGULAR,2081,62,0,0,0,2016-02-05 00:00:00,0,Weekday,Friday
195321,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/30/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-01-30 00:00:00,0,Weekend,Saturday
195327,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/31/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-01-31 00:00:00,0,Weekend,Sunday
195333,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/01/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-01 00:00:00,0,Weekday,Monday
195339,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/02/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-02 00:00:00,0,Weekday,Tuesday
195345,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/03/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-03 00:00:00,0,Weekday,Wednesday
195352,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/04/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-04 00:00:00,0,Weekday,Thursday
195359,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,02/05/2016,00:00:00,REGULAR,5554,231,0,0,0,2016-02-05 00:00:00,0,Weekday,Friday

In [15]:
data_grouped = data_0to4.groupby(['DATE','STATION']).sum()

In [16]:
data_grouped

                                 ENTRY        EXIT  dENTRY  dEXIT  dTOTAL  \
DATE       STATION
01/30/2016 103 ST            150660801   593258607     478    578    1056
           111 ST             56037434    20707646       0      0       0
           116 ST            434903388   443712329     805   1038    1843
           116 ST-COLUMBIA  1209640397   255927497     427    205     632
           125 ST            150202459   109499131    1034    958    1992
           135 ST            202952478    30401242      84    194     278
           137 ST CITY COL    51912113    41103266     164    669     833
           14 ST             264208303    53014467    1093    458    1551
           14 ST-UNION SQ   1293542597   499435093    5051   1765    6816
           14TH STREET         2919853      437970     124     97     221
           155 ST             30897679    23611661     131    326     457
           157 ST             31758293    21319687     195    596     791
           163 ST-AMSTERDM    16786156    11312741      68    178     246
           170 ST           1284721388  2348637447      94    206     300
           174 ST             21724709    14536636     115    321     436
           18 AV              20632863    21184632      11    151     162
           181 ST             51650786    42951647      96    485     581
           20 AV              14615889    12623155       8     48      56
           21 ST               5625463     6365405     118     96     214
           219 ST              9655519     5924753      74     74     148
           225 ST             10732522     6344388      55    117     172
           23 ST            2189198721  1831808490    1168    758    1926
           233 ST             95348208     4551390      99     77     176
           238 ST             19051162      876114      76      7      83
           25 AV               3631615     1231460      52     78     130
           28 ST            1512486087  2082516456    1337    520    1857
           3 AV 138 ST        17657223    15056950     168    819     987
           33 ST             345816670   136790373     879    369    1248
           34 ST-PENN STA   1883553699  1220743530     701    515    1216
           36 ST             327382632  1233482392     273    558     831
...                                ...         ...     ...    ...     ...
02/05/2016 QUEENS PLAZA       88589121    39519277      78    109     187
           RALPH AV           21106664    16757053      99    187     286
           RIT-MANHATTAN       2495031       28834      32      4      36
           RIT-ROOSEVELT       7297988      445046      10      2      12
           ROCKAWAY AV       716724570    42361406      73    161     234
           ROCKAWAY PARK B   105093677    10847855      11     39      50
           SENECA AVE          5147160     5739592      16     95     111
           SHEEPSHEAD BAY     39911530    36051676     126    286     412
           SHEPHERD AV        16789432    14385726      46    137     183
           SIMPSON ST         37298316    10293956     131     43     174
           SOUTH FERRY        35267066    30996261     148    359     507
           SUTPHIN BLVD       18003975     9694022      49    152     201
           SUTTER AV          10734372    14866738      92    178     270
           THIRTY ST           4555725     4782218      89     22     111
           THIRTY THIRD ST    12420456     7174334     325    133     458
           TOMPKINSVILLE       8634308     2414988      10      0      10
           TREMONT AV        129121400    10841080     142    442     584
           TWENTY THIRD ST     2967892     1583621      60     57     117
           UTICA AV          102866606    50090379     213    512     725
           VAN SICLEN AV      12250985    12006522      40    108     148
           VAN SICLEN AVE     13280522    13781865      44    171     215
           W 4 ST-WASH SQ    803600370   896200617    2060    575    2635
           WAKEFIELD/241      16160977    16718474     115    255     370
           WALL ST           533474060   278101480      74     74     148
           WEST FARMS SQ     438249333    72934176     155    205     360
           WHITEHALL S-FRY   265669373    62388106     183    185     368
           WINTHROP ST        31540513     5580849      63     39     102
           WOODHAVEN BLVD     55353259    36616894     144    447     591
           YORK ST            31524372    28876736      81     81     162
           ZEREGA AV          53544029      530994      24     84     108

                            HOUR
DATE       STATION
01/30/2016 103 ST              0
           111 ST              0
           116 ST              0
           116 ST-COLUMBIA     0
           125 ST              0
           135 ST              0
           137 ST CITY COL     0
           14 ST               0
           14 ST-UNION SQ      0
           14TH STREET         7
           155 ST              0
           157 ST              0
           163 ST-AMSTERDM     0
           170 ST              0
           174 ST              0
           18 AV               0
           181 ST              0
           20 AV               0
           21 ST               0
           219 ST              0
           225 ST              0
           23 ST               0
           233 ST              0
           238 ST              0
           25 AV               0
           28 ST               0
           3 AV 138 ST         0
           33 ST               0
           34 ST-PENN STA     21
           36 ST               0
...                          ...
02/05/2016 QUEENS PLAZA        0
           RALPH AV            0
           RIT-MANHATTAN       0
           RIT-ROOSEVELT       0
           ROCKAWAY AV         0
           ROCKAWAY PARK B     0
           SENECA AVE          0
           SHEEPSHEAD BAY      0
           SHEPHERD AV         0
           SIMPSON ST          0
           SOUTH FERRY         0
           SUTPHIN BLVD        0
           SUTTER AV           0
           THIRTY ST           6
           THIRTY THIRD ST     4
           TOMPKINSVILLE       7
           TREMONT AV          0
           TWENTY THIRD ST     5
           UTICA AV            0
           VAN SICLEN AV       0
           VAN SICLEN AVE      0
           W 4 ST-WASH SQ      0
           WAKEFIELD/241       0
           WALL ST            28
           WEST FARMS SQ       0
           WHITEHALL S-FRY     0
           WINTHROP ST         0
           WOODHAVEN BLVD      0
           YORK ST             0
           ZEREGA AV           0

[1358 rows x 6 columns]

In [19]:
data_reset = (data_grouped
    .reset_index()
    .sort_values(['dTOTAL'], ascending=(False))
)
data_reset

,DATE,STATION,ENTRY,EXIT,dENTRY,dEXIT,dTOTAL,HOUR
206,01/31/2016,14 ST-UNION SQ,1293618130,499503816,5019,1871,6890,0
8,01/30/2016,14 ST-UNION SQ,1293542597,499435093,5051,1765,6816,0
372,01/31/2016,W 4 ST-WASH SQ,803400733,896015233,4210,1369,5579,0
189,01/30/2016,W 4 ST-WASH SQ,803366012,895980564,4157,1228,5385,0
242,01/31/2016,8 AV,198050137,91434375,2832,895,3727,0
227,01/31/2016,42 ST-PORT AUTH,323373235,102723460,2705,854,3559,19
91,01/30/2016,DELANCEY/ESSEX,1711407520,1111503009,2177,1377,3554,0
1168,02/05/2016,14 ST-UNION SQ,1294102075,499918309,2612,871,3483,0
45,01/30/2016,8 AV,198017312,91409566,2382,910,3292,0
248,01/31/2016,96 ST,771447201,1416969923,1304,1746,3050,0
970,02/04/2016,14 ST-UNION SQ,1293992274,499824185,2309,598,2907,0
51,01/30/2016,96 ST,771404894,1416938823,1227,1639,2866,0
285,01/31/2016,DELANCEY/ESSEX,1711427216,1111518470,1896,911,2807,0
30,01/30/2016,42 ST-PORT AUTH,323341795,102697015,2055,737,2792,19
786,02/03/2016,14 ST-UNION SQ,1293887581,499733216,2098,634,2732,0
1349,02/05/2016,W 4 ST-WASH SQ,803600370,896200617,2060,575,2635,0
588,02/02/2016,14 ST-UNION SQ,1293778906,499640944,1925,560,2485,0
953,02/03/2016,W 4 ST-WASH SQ,803512271,896118222,1651,461,2112,0
389,02/01/2016,14 ST-UNION SQ,1293677346,499553490,1508,517,2025,0
330,01/31/2016,METROPOLITAN AV,29543160,21932465,1407,618,2025,0
202,01/31/2016,125 ST,150226041,109517570,1012,991,2003,0
4,01/30/2016,125 ST,150202459,109499131,1034,958,1992,0
21,01/30/2016,23 ST,2189198721,1831808490,1168,758,1926,0
1251,02/05/2016,DELANCEY/ESSEX,1711541807,1111606700,833,1090,1923,0
77,01/30/2016,CANAL ST,2984066566,1622071736,1133,755,1888,0
1151,02/04/2016,W 4 ST-WASH SQ,803554445,896157841,1450,436,1886,0
252,01/31/2016,ASTOR PL,29048024,23341731,1448,431,1879,0
25,01/30/2016,28 ST,1512486087,2082516456,1337,520,1857,0
2,01/30/2016,116 ST,434903388,443712329,805,1038,1843,0
1205,02/05/2016,8 AV,198226279,91555907,1341,490,1831,0
...,...,...,...,...,...,...,...,...
294,01/31/2016,EXCHANGE PLACE,379,84,3,4,7,0
931,02/03/2016,PAVONIA/NEWPORT,389738,766612,0,7,7,1
267,01/31/2016,BROAD ST,21733056,12925773,5,2,7,0
565,02/01/2016,TOMPKINSVILLE,8631173,2414988,6,0,6,7
430,02/01/2016,88 ST,8791901,8698607,0,6,6,0
971,02/04/2016,14TH STREET,2732107,55729,0,6,6,0
452,02/01/2016,BROAD ST,21733077,12925797,5,1,6,0
329,01/31/2016,MARCY AV,166874234,485516715,2,3,5,0
1077,02/04/2016,HARRISON,324585,11800,3,1,4,0
948,02/03/2016,TOMPKINSVILLE,8632790,2414988,4,0,4,7
520,02/01/2016,MARCY AV,166874250,485516735,1,2,3,0
581,02/02/2016,111 ST,56037886,20707765,2,1,3,0
199,01/31/2016,111 ST,56037445,20707660,0,2,2,0
152,01/30/2016,NEWARK C,1079720,93861,2,0,2,8
875,02/03/2016,EXCHANGE PLACE,2455,403,0,2,2,0
243,01/31/2016,80 ST,130685503,6699418,0,1,1,0
382,02/01/2016,111 ST,56037448,20707673,0,1,1,0
533,02/01/2016,NEWARK C,2751400,311034,0,1,1,1
246,01/31/2016,88 ST,8791901,8698606,0,0,0,0
1113,02/04/2016,NEWARK C,535617,144747,0,0,0,0
427,02/01/2016,80 ST,130685517,6699433,0,0,0,0
366,01/31/2016,THIRTY ST,0,749019,0,0,0,0
930,02/03/2016,PATH WTC,143117,44005,0,0,0,1
537,02/01/2016,NEWKIRK PLAZA,48047799,45696096,0,0,0,0
343,01/31/2016,NEWKIRK PLAZA,48047798,45696094,0,0,0,0
162,01/30/2016,PARKSIDE AV,33769784,30576398,0,0,0,0
1,01/30/2016,111 ST,56037434,20707646,0,0,0,0
349,01/31/2016,PARKSIDE AV,33769784,30576398,0,0,0,0
543,02/01/2016,PARKSIDE AV,33769784,30576398,0,0,0,0
341,01/31/2016,NEWARK C,112910,2517,0,0,0,0

In [18]:
for r in range(data_reset.shape[0]):
    if data_reset.ix[r,'WEEKDAY'] =='Weekday':
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(5)
    else:
        data_reset.ix[r,'dTOTALACTUAL'] = data_reset.ix[r, 'dTOTAL']/(2)

KeyError: 'WEEKDAY'

In [ ]:
data_reset

In [ ]:
testweekend = data_reset[(data_reset.WEEKDAY == 'Weekday')]

In [ ]:
testweekend

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#data_reset[data_reset.STATION=='WORLD TRADE CTR'].dTOTAL.plot(kind='bar');
data_reset[data_reset.STATION=='WORLD TRADE CTR'].hist(by = data_reset.DATE, bins = 25, figsize = (100,50));